// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for UnderstandingAttemptState.
const (
	UnderstandingAttemptStateDone    UnderstandingAttemptState = "done"
	UnderstandingAttemptStateFailed  UnderstandingAttemptState = "failed"
	UnderstandingAttemptStateQueued  UnderstandingAttemptState = "queued"
	UnderstandingAttemptStateRunning UnderstandingAttemptState = "running"
)

// Valid indicates whether the value is a known member of the UnderstandingAttemptState enum.
func (e UnderstandingAttemptState) Valid() bool {
	switch e {
	case UnderstandingAttemptStateDone:
		return true
	case UnderstandingAttemptStateFailed:
		return true
	case UnderstandingAttemptStateQueued:
		return true
	case UnderstandingAttemptStateRunning:
		return true
	default:
		return false
	}
}

// Defines values for UnderstandingDetailsStatus.
const (
	UnderstandingDetailsStatusDone       UnderstandingDetailsStatus = "done"
	UnderstandingDetailsStatusFailed     UnderstandingDetailsStatus = "failed"
	UnderstandingDetailsStatusNotStarted UnderstandingDetailsStatus = "not_started"
	UnderstandingDetailsStatusQueued     UnderstandingDetailsStatus = "queued"
	UnderstandingDetailsStatusRunning    UnderstandingDetailsStatus = "running"
)

// Valid indicates whether the value is a known member of the UnderstandingDetailsStatus enum.
func (e UnderstandingDetailsStatus) Valid() bool {
	switch e {
	case UnderstandingDetailsStatusDone:
		return true
	case UnderstandingDetailsStatusFailed:
		return true
	case UnderstandingDetailsStatusNotStarted:
		return true
	case UnderstandingDetailsStatusQueued:
		return true
	case UnderstandingDetailsStatusRunning:
		return true
	default:
		return false
	}
}

// CostEstimate defines model for CostEstimate.
type CostEstimate struct {
	AmountUsd   float64 `json:"amount_usd"`
	Basis       string  `json:"basis"`
	PricingDate *string `json:"pricing_date,omitempty"`
	PricingUrl  *string `json:"pricing_url,omitempty"`
}

// DerivedContent Independent text artifact belonging to its containing Run.
type DerivedContent struct {
	BlobHash string `json:"blob_hash"`
	ByteSize int64  `json:"byte_size"`

	// Content Literal UTF-8 text content.
	Content     string             `json:"content"`
	ContentType string             `json:"content_type"`
	Id          openapi_types.UUID `json:"id"`

	// Provenance Optional opaque plugin-defined JSON metadata.
	Provenance interface{} `json:"provenance,omitempty"`

	// Scope Optional opaque plugin-defined JSON metadata.
	Scope interface{} `json:"scope,omitempty"`
}

// DuplicateMemory defines model for DuplicateMemory.
type DuplicateMemory struct {
	Id openapi_types.UUID `json:"id"`
}

// Error defines model for Error.
type Error struct {
	// Code Example: memory_not_found
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`

	// ExistingMemory Present on a duplicate import conflict so clients can recover.
	ExistingMemory *DuplicateMemory `json:"existing_memory,omitempty"`
	Message        string           `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status  HealthResponseStatus `json:"status"`
	Version *string              `json:"version,omitempty"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// ImportContext Stored provenance from the first successful import.
type ImportContext struct {
	FilesystemCreatedAt  *time.Time `json:"filesystem_created_at,omitempty"`
	FilesystemModifiedAt *time.Time `json:"filesystem_modified_at,omitempty"`
	FullPath             *string    `json:"full_path,omitempty"`
	OriginalFilename     string     `json:"original_filename"`
	RelativePath         *string    `json:"relative_path,omitempty"`
}

// ImportContextInput Optional client-observed provenance sent as one application/json
// multipart part. The original filename comes from the Blob part. Omitted
// values remain unknown; malformed timestamps reject the import.
type ImportContextInput struct {
	FilesystemCreatedAt  *time.Time `json:"filesystem_created_at,omitempty"`
	FilesystemModifiedAt *time.Time `json:"filesystem_modified_at,omitempty"`
	FullPath             *string    `json:"full_path,omitempty"`
	RelativePath         *string    `json:"relative_path,omitempty"`
}

// ImportMultipart defines model for ImportMultipart.
type ImportMultipart struct {
	// File One Blob of at most 100 MiB with a nonblank filename in
	// Content-Disposition. The server detects its Media Type from content
	// first and may fall back to a valid, specific part Content-Type.
	File openapi_types.File `json:"file"`

	// ImportContext Optional client-observed provenance sent as one application/json
	// multipart part. The original filename comes from the Blob part. Omitted
	// values remain unknown; malformed timestamps reject the import.
	ImportContext *ImportContextInput `json:"import_context,omitempty"`
}

// MemoryDetail defines model for MemoryDetail.
type MemoryDetail struct {
	// ContentUrl Relative URL of the content download endpoint.
	ContentUrl *string `json:"content_url,omitempty"`

	// ImportContext Stored provenance from the first successful import.
	ImportContext ImportContext        `json:"import_context"`
	Memory        MemorySummary        `json:"memory"`
	Understanding UnderstandingDetails `json:"understanding"`
}

// MemoryPage defines model for MemoryPage.
type MemoryPage struct {
	Items      []MemorySummary `json:"items"`
	NextCursor *string         `json:"next_cursor,omitempty"`
}

// MemorySummary defines model for MemorySummary.
type MemorySummary struct {
	// BlobHash Canonical SHA-256 Blobref of the immutable Blob.
	BlobHash           string             `json:"blob_hash"`
	ByteSize           int64              `json:"byte_size"`
	Id                 openapi_types.UUID `json:"id"`
	ImportedAt         time.Time          `json:"imported_at"`
	MediaType          string             `json:"media_type"`
	OriginalCreatedAt  *time.Time         `json:"original_created_at,omitempty"`
	OriginalFilename   string             `json:"original_filename"`
	OriginalModifiedAt *time.Time         `json:"original_modified_at,omitempty"`
}

// RebuildRequest defines model for RebuildRequest.
type RebuildRequest struct {
	// UserNote Optional owner guidance; null reuses the saved note, empty string clears it.
	UserNote *string `json:"user_note,omitempty"`
}

// RebuildStatus defines model for RebuildStatus.
type RebuildStatus struct {
	Attempt   UnderstandingAttempt `json:"attempt"`
	MemoryId  openapi_types.UUID   `json:"memory_id"`
	StatusUrl string               `json:"status_url"`
}

// SearchExcerptPart defines model for SearchExcerptPart.
type SearchExcerptPart struct {
	Match bool   `json:"match"`
	Text  string `json:"text"`
}

// SearchHit defines model for SearchHit.
type SearchHit struct {
	Excerpt []SearchExcerptPart `json:"excerpt"`

	// MatchTier 0 for complete whole-word/stem matches; 1 for fragment-dependent matches. Lower tiers sort first.
	MatchTier int           `json:"match_tier"`
	Memory    MemorySummary `json:"memory"`

	// Score SQLite BM25 from the word index for tier 0 and trigram index for tier 1. When no indexed fragments match, tier 1 falls back to word-index BM25 or 0. Lower scores sort first within each match tier; ties sort by Memory ID. Scores from different indexes are not comparable across tiers.
	Score float64 `json:"score"`
}

// SearchPage defines model for SearchPage.
type SearchPage struct {
	Items      []SearchHit     `json:"items"`
	NextCursor *string         `json:"next_cursor,omitempty"`
	QueryPlan  SearchQueryPlan `json:"query_plan"`
	Total      int64           `json:"total"`
}

// SearchQueryPlan defines model for SearchQueryPlan.
type SearchQueryPlan struct {
	Query string   `json:"query"`
	Terms []string `json:"terms"`
}

// Statistics defines model for Statistics.
type Statistics struct {
	Usage *TokenUsage `json:"usage,omitempty"`
}

// TokenUsage defines model for TokenUsage.
type TokenUsage struct {
	CacheWriteInputTokens *int64 `json:"cache_write_input_tokens,omitempty"`
	CachedInputTokens     *int64 `json:"cached_input_tokens,omitempty"`
	InputTokens           *int64 `json:"input_tokens,omitempty"`
	OutputTokens          *int64 `json:"output_tokens,omitempty"`
	ReasoningOutputTokens *int64 `json:"reasoning_output_tokens,omitempty"`
	TotalTokens           *int64 `json:"total_tokens,omitempty"`
}

// UnderstandingAttempt defines model for UnderstandingAttempt.
type UnderstandingAttempt struct {
	CompletedAt *time.Time                `json:"completed_at,omitempty"`
	Diagnostics *UnderstandingDiagnostics `json:"diagnostics,omitempty"`
	Id          openapi_types.UUID        `json:"id"`

	// PluginId Configured plugin ID; empty when no plugin is selected.
	PluginId  string                    `json:"plugin_id"`
	QueuedAt  time.Time                 `json:"queued_at"`
	StartedAt *time.Time                `json:"started_at,omitempty"`
	Status    UnderstandingAttemptState `json:"status"`
}

// UnderstandingAttemptState defines model for UnderstandingAttemptState.
type UnderstandingAttemptState string

// UnderstandingDetails defines model for UnderstandingDetails.
type UnderstandingDetails struct {
	// ActiveRun The last complete successful Run; failed attempts do not replace it.
	ActiveRun     *UnderstandingRun          `json:"active_run"`
	LatestAttempt *UnderstandingAttempt      `json:"latest_attempt"`
	Status        UnderstandingDetailsStatus `json:"status"`

	// StatusUrl Process-local polling URL; absent for durable history after restart.
	StatusUrl *string `json:"status_url,omitempty"`

	// UserNote Latest saved owner guidance for this Memory; empty when absent or cleared.
	UserNote string `json:"user_note"`
}

// UnderstandingDetailsStatus defines model for UnderstandingDetails.Status.
type UnderstandingDetailsStatus string

// UnderstandingDiagnostics defines model for UnderstandingDiagnostics.
type UnderstandingDiagnostics struct {
	Error    string `json:"error"`
	ExitCode *int   `json:"exit_code,omitempty"`

	// Stderr Captured plugin diagnostics; may contain private source content.
	Stderr string `json:"stderr"`

	// Stdout Captured plugin stdout, including invalid protocol output.
	Stdout string `json:"stdout"`
}

// UnderstandingRun defines model for UnderstandingRun.
type UnderstandingRun struct {
	Artifacts   []DerivedContent   `json:"artifacts"`
	AttemptId   openapi_types.UUID `json:"attempt_id"`
	CompletedAt time.Time          `json:"completed_at"`

	// CostEstimate Optional API-equivalent estimate, not subscription charges.
	CostEstimate  *CostEstimate      `json:"cost_estimate,omitempty"`
	CreatedAt     time.Time          `json:"created_at"`
	Id            openapi_types.UUID `json:"id"`
	PluginId      string             `json:"plugin_id"`
	PluginVersion string             `json:"plugin_version"`
	SourceBlobref string             `json:"source_blobref"`

	// Statistics Optional plugin-reported Run totals.
	Statistics *Statistics `json:"statistics,omitempty"`

	// UserNote Owner guidance captured by this successful Run; empty when absent.
	UserNote string   `json:"user_note"`
	Warnings []string `json:"warnings"`
}

// Cursor defines model for Cursor.
type Cursor = string

// Limit defines model for Limit.
type Limit = int32

// MemoryId defines model for MemoryId.
type MemoryId = openapi_types.UUID

// SearchLimit defines model for SearchLimit.
type SearchLimit = int64

// SearchQuery defines model for SearchQuery.
type SearchQuery = string

// BrowseMemoriesParams defines parameters for BrowseMemories.
type BrowseMemoriesParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// SearchMemoriesParams defines parameters for SearchMemories.
type SearchMemoriesParams struct {
	Query  SearchQuery  `form:"query" json:"query"`
	Limit  *SearchLimit `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *Cursor      `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ImportMemoryMultipartRequestBody defines body for ImportMemory for multipart/form-data ContentType.
type ImportMemoryMultipartRequestBody = ImportMultipart

// RebuildMemoryJSONRequestBody defines body for RebuildMemory for application/json ContentType.
type RebuildMemoryJSONRequestBody = RebuildRequest

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetLiveness Check whether the process is alive
	//
	// Corresponds with GET /livez (the `GetLiveness` operationId).
	GetLiveness(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BrowseMemories Browse committed Memories
	//
	// Corresponds with GET /memories (the `BrowseMemories` operationId).
	BrowseMemories(ctx context.Context, params *BrowseMemoriesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ImportMemoryWithBody Durably import one Blob as a Memory
	//
	// Upload one Blob and return after its bytes are durably published and
	// the Memory is committed. A Blob may contain at most 100 MiB
	// (104857600 bytes). The server permits bounded multipart protocol
	// overhead in addition to that Blob limit. Duplicate content is rejected
	// with HTTP 409. Document Understanding is not performed by this request.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /memories/import (the `ImportMemory` operationId).
	ImportMemoryWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SearchMemories Search committed Memories
	//
	// Search results are returned in ranked pages. Supply the returned cursor
	// with the same trimmed query to continue. Cursors do not snapshot Vault
	// mutations between requests.
	//
	// Corresponds with GET /memories/search (the `SearchMemories` operationId).
	SearchMemories(ctx context.Context, params *SearchMemoriesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteMemory Delete one Memory and its Blob
	//
	// Permanently deletes the Memory, its Understanding Runs, and the
	// immutable Blob referenced by it. The Vault reuses the Blob only when
	// its content is imported again.
	//
	// Corresponds with DELETE /memories/{memoryId} (the `DeleteMemory` operationId).
	DeleteMemory(ctx context.Context, memoryId MemoryId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetMemory Get committed Memory details
	//
	// Corresponds with GET /memories/{memoryId} (the `GetMemory` operationId).
	GetMemory(ctx context.Context, memoryId MemoryId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetMemoryContent Download and verify a Memory's immutable Blob
	//
	// Corresponds with GET /memories/{memoryId}/content (the `GetMemoryContent` operationId).
	GetMemoryContent(ctx context.Context, memoryId MemoryId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RebuildMemoryWithBody Request a Memory Rebuild
	//
	// Accept process-local work using current Document Understanding methods.
	// An optional user_note replaces the saved Memory guidance; absent or
	// null user_note reuses the saved note, and an empty string clears it.
	// The original Blob and previous active Run remain unchanged. Acceptance
	// is best effort: queued/running work and polling handles are lost on
	// restart. Competing queued/running work returns 409 without scheduling
	// or changing the saved note.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /memories/{memoryId}/rebuild (the `RebuildMemory` operationId).
	RebuildMemoryWithBody(ctx context.Context, memoryId MemoryId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RebuildMemory Request a Memory Rebuild
	//
	// Accept process-local work using current Document Understanding methods.
	// An optional user_note replaces the saved Memory guidance; absent or
	// null user_note reuses the saved note, and an empty string clears it.
	// The original Blob and previous active Run remain unchanged. Acceptance
	// is best effort: queued/running work and polling handles are lost on
	// restart. Competing queued/running work returns 409 without scheduling
	// or changing the saved note.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /memories/{memoryId}/rebuild (the `RebuildMemory` operationId).
	RebuildMemory(ctx context.Context, memoryId MemoryId, body RebuildMemoryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetReadiness Check whether the server can accept requests
	//
	// Corresponds with GET /readyz (the `GetReadiness` operationId).
	GetReadiness(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetRebuildStatus Poll a retained process-local Rebuild
	//
	// Retained until superseded by a newly accepted attempt, Memory deletion,
	// or restart. Terminal handles remain readable; no artifacts are returned.
	//
	// Corresponds with GET /rebuild-status/{rebuildId} (the `GetRebuildStatus` operationId).
	GetRebuildStatus(ctx context.Context, rebuildId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetLiveness Check whether the process is alive
//
// Corresponds with GET /livez (the `GetLiveness` operationId).
func (c *Client) GetLiveness(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetLivenessRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// BrowseMemories Browse committed Memories
//
// Corresponds with GET /memories (the `BrowseMemories` operationId).
func (c *Client) BrowseMemories(ctx context.Context, params *BrowseMemoriesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBrowseMemoriesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ImportMemoryWithBody Durably import one Blob as a Memory
//
// Upload one Blob and return after its bytes are durably published and
// the Memory is committed. A Blob may contain at most 100 MiB
// (104857600 bytes). The server permits bounded multipart protocol
// overhead in addition to that Blob limit. Duplicate content is rejected
// with HTTP 409. Document Understanding is not performed by this request.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /memories/import (the `ImportMemory` operationId).
func (c *Client) ImportMemoryWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewImportMemoryRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// SearchMemories Search committed Memories
//
// Search results are returned in ranked pages. Supply the returned cursor
// with the same trimmed query to continue. Cursors do not snapshot Vault
// mutations between requests.
//
// Corresponds with GET /memories/search (the `SearchMemories` operationId).
func (c *Client) SearchMemories(ctx context.Context, params *SearchMemoriesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSearchMemoriesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteMemory Delete one Memory and its Blob
//
// Permanently deletes the Memory, its Understanding Runs, and the
// immutable Blob referenced by it. The Vault reuses the Blob only when
// its content is imported again.
//
// Corresponds with DELETE /memories/{memoryId} (the `DeleteMemory` operationId).
func (c *Client) DeleteMemory(ctx context.Context, memoryId MemoryId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteMemoryRequest(c.Server, memoryId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetMemory Get committed Memory details
//
// Corresponds with GET /memories/{memoryId} (the `GetMemory` operationId).
func (c *Client) GetMemory(ctx context.Context, memoryId MemoryId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMemoryRequest(c.Server, memoryId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetMemoryContent Download and verify a Memory's immutable Blob
//
// Corresponds with GET /memories/{memoryId}/content (the `GetMemoryContent` operationId).
func (c *Client) GetMemoryContent(ctx context.Context, memoryId MemoryId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMemoryContentRequest(c.Server, memoryId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// RebuildMemoryWithBody Request a Memory Rebuild
//
// Accept process-local work using current Document Understanding methods.
// An optional user_note replaces the saved Memory guidance; absent or
// null user_note reuses the saved note, and an empty string clears it.
// The original Blob and previous active Run remain unchanged. Acceptance
// is best effort: queued/running work and polling handles are lost on
// restart. Competing queued/running work returns 409 without scheduling
// or changing the saved note.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /memories/{memoryId}/rebuild (the `RebuildMemory` operationId).
func (c *Client) RebuildMemoryWithBody(ctx context.Context, memoryId MemoryId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRebuildMemoryRequestWithBody(c.Server, memoryId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// RebuildMemory Request a Memory Rebuild
//
// Accept process-local work using current Document Understanding methods.
// An optional user_note replaces the saved Memory guidance; absent or
// null user_note reuses the saved note, and an empty string clears it.
// The original Blob and previous active Run remain unchanged. Acceptance
// is best effort: queued/running work and polling handles are lost on
// restart. Competing queued/running work returns 409 without scheduling
// or changing the saved note.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /memories/{memoryId}/rebuild (the `RebuildMemory` operationId).
func (c *Client) RebuildMemory(ctx context.Context, memoryId MemoryId, body RebuildMemoryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRebuildMemoryRequest(c.Server, memoryId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetReadiness Check whether the server can accept requests
//
// Corresponds with GET /readyz (the `GetReadiness` operationId).
func (c *Client) GetReadiness(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetReadinessRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetRebuildStatus Poll a retained process-local Rebuild
//
// Retained until superseded by a newly accepted attempt, Memory deletion,
// or restart. Terminal handles remain readable; no artifacts are returned.
//
// Corresponds with GET /rebuild-status/{rebuildId} (the `GetRebuildStatus` operationId).
func (c *Client) GetRebuildStatus(ctx context.Context, rebuildId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRebuildStatusRequest(c.Server, rebuildId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetLivenessRequest constructs an http.Request for the GetLiveness method
func NewGetLivenessRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/livez")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewBrowseMemoriesRequest constructs an http.Request for the BrowseMemories method
func NewBrowseMemoriesRequest(server string, params *BrowseMemoriesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/memories")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "cursor", *params.Cursor, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewImportMemoryRequestWithBody constructs an http.Request for the ImportMemory method, with any body, and a specified content type
func NewImportMemoryRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/memories/import")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewSearchMemoriesRequest constructs an http.Request for the SearchMemories method
func NewSearchMemoriesRequest(server string, params *SearchMemoriesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/memories/search")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "query", params.Query, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int64"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "cursor", *params.Cursor, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteMemoryRequest constructs an http.Request for the DeleteMemory method
func NewDeleteMemoryRequest(server string, memoryId MemoryId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "memoryId", memoryId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/memories/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetMemoryRequest constructs an http.Request for the GetMemory method
func NewGetMemoryRequest(server string, memoryId MemoryId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "memoryId", memoryId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/memories/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetMemoryContentRequest constructs an http.Request for the GetMemoryContent method
func NewGetMemoryContentRequest(server string, memoryId MemoryId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "memoryId", memoryId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/memories/%s/content", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRebuildMemoryRequest calls the generic RebuildMemory builder with application/json body
func NewRebuildMemoryRequest(server string, memoryId MemoryId, body RebuildMemoryJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRebuildMemoryRequestWithBody(server, memoryId, "application/json", bodyReader)
}

// NewRebuildMemoryRequestWithBody constructs an http.Request for the RebuildMemory method, with any body, and a specified content type
func NewRebuildMemoryRequestWithBody(server string, memoryId MemoryId, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "memoryId", memoryId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/memories/%s/rebuild", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetReadinessRequest constructs an http.Request for the GetReadiness method
func NewGetReadinessRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/readyz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetRebuildStatusRequest constructs an http.Request for the GetRebuildStatus method
func NewGetRebuildStatusRequest(server string, rebuildId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "rebuildId", rebuildId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/rebuild-status/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetLivenessWithResponse Check whether the process is alive
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /livez (the `GetLiveness` operationId).
	GetLivenessWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetLivenessResponse, error)

	// BrowseMemoriesWithResponse Browse committed Memories
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /memories (the `BrowseMemories` operationId).
	BrowseMemoriesWithResponse(ctx context.Context, params *BrowseMemoriesParams, reqEditors ...RequestEditorFn) (*BrowseMemoriesResponse, error)

	// ImportMemoryWithBodyWithResponse Durably import one Blob as a Memory
	//
	// Upload one Blob and return after its bytes are durably published and
	// the Memory is committed. A Blob may contain at most 100 MiB
	// (104857600 bytes). The server permits bounded multipart protocol
	// overhead in addition to that Blob limit. Duplicate content is rejected
	// with HTTP 409. Document Understanding is not performed by this request.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /memories/import (the `ImportMemory` operationId).
	ImportMemoryWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ImportMemoryResponse, error)

	// SearchMemoriesWithResponse Search committed Memories
	//
	// Search results are returned in ranked pages. Supply the returned cursor
	// with the same trimmed query to continue. Cursors do not snapshot Vault
	// mutations between requests.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /memories/search (the `SearchMemories` operationId).
	SearchMemoriesWithResponse(ctx context.Context, params *SearchMemoriesParams, reqEditors ...RequestEditorFn) (*SearchMemoriesResponse, error)

	// DeleteMemoryWithResponse Delete one Memory and its Blob
	//
	// Permanently deletes the Memory, its Understanding Runs, and the
	// immutable Blob referenced by it. The Vault reuses the Blob only when
	// its content is imported again.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /memories/{memoryId} (the `DeleteMemory` operationId).
	DeleteMemoryWithResponse(ctx context.Context, memoryId MemoryId, reqEditors ...RequestEditorFn) (*DeleteMemoryResponse, error)

	// GetMemoryWithResponse Get committed Memory details
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /memories/{memoryId} (the `GetMemory` operationId).
	GetMemoryWithResponse(ctx context.Context, memoryId MemoryId, reqEditors ...RequestEditorFn) (*GetMemoryResponse, error)

	// GetMemoryContentWithResponse Download and verify a Memory's immutable Blob
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /memories/{memoryId}/content (the `GetMemoryContent` operationId).
	GetMemoryContentWithResponse(ctx context.Context, memoryId MemoryId, reqEditors ...RequestEditorFn) (*GetMemoryContentResponse, error)

	// RebuildMemoryWithBodyWithResponse Request a Memory Rebuild
	//
	// Accept process-local work using current Document Understanding methods.
	// An optional user_note replaces the saved Memory guidance; absent or
	// null user_note reuses the saved note, and an empty string clears it.
	// The original Blob and previous active Run remain unchanged. Acceptance
	// is best effort: queued/running work and polling handles are lost on
	// restart. Competing queued/running work returns 409 without scheduling
	// or changing the saved note.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /memories/{memoryId}/rebuild (the `RebuildMemory` operationId).
	RebuildMemoryWithBodyWithResponse(ctx context.Context, memoryId MemoryId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RebuildMemoryResponse, error)

	// RebuildMemoryWithResponse Request a Memory Rebuild
	//
	// Accept process-local work using current Document Understanding methods.
	// An optional user_note replaces the saved Memory guidance; absent or
	// null user_note reuses the saved note, and an empty string clears it.
	// The original Blob and previous active Run remain unchanged. Acceptance
	// is best effort: queued/running work and polling handles are lost on
	// restart. Competing queued/running work returns 409 without scheduling
	// or changing the saved note.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /memories/{memoryId}/rebuild (the `RebuildMemory` operationId).
	RebuildMemoryWithResponse(ctx context.Context, memoryId MemoryId, body RebuildMemoryJSONRequestBody, reqEditors ...RequestEditorFn) (*RebuildMemoryResponse, error)

	// GetReadinessWithResponse Check whether the server can accept requests
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /readyz (the `GetReadiness` operationId).
	GetReadinessWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetReadinessResponse, error)

	// GetRebuildStatusWithResponse Poll a retained process-local Rebuild
	//
	// Retained until superseded by a newly accepted attempt, Memory deletion,
	// or restart. Terminal handles remain readable; no artifacts are returned.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /rebuild-status/{rebuildId} (the `GetRebuildStatus` operationId).
	GetRebuildStatusWithResponse(ctx context.Context, rebuildId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetRebuildStatusResponse, error)
}

type GetLivenessResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *HealthResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetLivenessResponse) GetJSON200() *HealthResponse {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetLivenessResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetLivenessResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetLivenessResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetLivenessResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type BrowseMemoriesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *MemoryPage
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r BrowseMemoriesResponse) GetJSON200() *MemoryPage {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r BrowseMemoriesResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetBody returns the raw response body bytes
func (r BrowseMemoriesResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r BrowseMemoriesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BrowseMemoriesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r BrowseMemoriesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ImportMemoryResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *MemorySummary
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Error
	// JSON413 the response for an HTTP 413 `application/json` response
	JSON413 *Error
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *Error
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r ImportMemoryResponse) GetJSON201() *MemorySummary {
	return r.JSON201
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r ImportMemoryResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r ImportMemoryResponse) GetJSON409() *Error {
	return r.JSON409
}

// GetJSON413 returns the response for an HTTP 413 `application/json` response
func (r ImportMemoryResponse) GetJSON413() *Error {
	return r.JSON413
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r ImportMemoryResponse) GetJSON500() *Error {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r ImportMemoryResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ImportMemoryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ImportMemoryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ImportMemoryResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// SearchMemoriesResponse200Headers the declared response headers of an HTTP 200 response for SearchMemories
type SearchMemoriesResponse200Headers struct {
	CacheControl *string
}

// SearchMemoriesResponse400Headers the declared response headers of an HTTP 400 response for SearchMemories
type SearchMemoriesResponse400Headers struct {
	CacheControl *string
}

type SearchMemoriesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *SearchPage
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// Headers200 the parsed response headers for an HTTP 200 response
	Headers200 *SearchMemoriesResponse200Headers
	// Headers400 the parsed response headers for an HTTP 400 response
	Headers400 *SearchMemoriesResponse400Headers
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r SearchMemoriesResponse) GetJSON200() *SearchPage {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r SearchMemoriesResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetBody returns the raw response body bytes
func (r SearchMemoriesResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r SearchMemoriesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SearchMemoriesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r SearchMemoriesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteMemoryResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r DeleteMemoryResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r DeleteMemoryResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeleteMemoryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteMemoryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteMemoryResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetMemoryResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *MemoryDetail
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetMemoryResponse) GetJSON200() *MemoryDetail {
	return r.JSON200
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetMemoryResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r GetMemoryResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetMemoryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMemoryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetMemoryResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetMemoryContentResponse200Headers the declared response headers of an HTTP 200 response for GetMemoryContent
type GetMemoryContentResponse200Headers struct {
	ContentDisposition *string
	ETag               *string
}

type GetMemoryContentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *Error
	// JSON507 the response for an HTTP 507 `application/json` response
	JSON507 *Error
	// Headers200 the parsed response headers for an HTTP 200 response
	Headers200 *GetMemoryContentResponse200Headers
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetMemoryContentResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r GetMemoryContentResponse) GetJSON500() *Error {
	return r.JSON500
}

// GetJSON507 returns the response for an HTTP 507 `application/json` response
func (r GetMemoryContentResponse) GetJSON507() *Error {
	return r.JSON507
}

// GetBody returns the raw response body bytes
func (r GetMemoryContentResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetMemoryContentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMemoryContentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetMemoryContentResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// RebuildMemoryResponse202Headers the declared response headers of an HTTP 202 response for RebuildMemory
type RebuildMemoryResponse202Headers struct {
	CacheControl *string
}

// RebuildMemoryResponse409Headers the declared response headers of an HTTP 409 response for RebuildMemory
type RebuildMemoryResponse409Headers struct {
	CacheControl *string
}

type RebuildMemoryResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON202 the response for an HTTP 202 `application/json` response
	JSON202 *RebuildStatus
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *RebuildStatus
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *Error
	// Headers202 the parsed response headers for an HTTP 202 response
	Headers202 *RebuildMemoryResponse202Headers
	// Headers409 the parsed response headers for an HTTP 409 response
	Headers409 *RebuildMemoryResponse409Headers
}

// GetJSON202 returns the response for an HTTP 202 `application/json` response
func (r RebuildMemoryResponse) GetJSON202() *RebuildStatus {
	return r.JSON202
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r RebuildMemoryResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r RebuildMemoryResponse) GetJSON409() *RebuildStatus {
	return r.JSON409
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r RebuildMemoryResponse) GetJSON503() *Error {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r RebuildMemoryResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r RebuildMemoryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RebuildMemoryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RebuildMemoryResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetReadinessResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *HealthResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetReadinessResponse) GetJSON200() *HealthResponse {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetReadinessResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetReadinessResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetReadinessResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetReadinessResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetRebuildStatusResponse200Headers the declared response headers of an HTTP 200 response for GetRebuildStatus
type GetRebuildStatusResponse200Headers struct {
	CacheControl *string
}

// GetRebuildStatusResponse404Headers the declared response headers of an HTTP 404 response for GetRebuildStatus
type GetRebuildStatusResponse404Headers struct {
	CacheControl *string
}

type GetRebuildStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *RebuildStatus
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// Headers200 the parsed response headers for an HTTP 200 response
	Headers200 *GetRebuildStatusResponse200Headers
	// Headers404 the parsed response headers for an HTTP 404 response
	Headers404 *GetRebuildStatusResponse404Headers
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetRebuildStatusResponse) GetJSON200() *RebuildStatus {
	return r.JSON200
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetRebuildStatusResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r GetRebuildStatusResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetRebuildStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRebuildStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetRebuildStatusResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetLivenessWithResponse Check whether the process is alive
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /livez (the `GetLiveness` operationId).
func (c *ClientWithResponses) GetLivenessWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetLivenessResponse, error) {
	rsp, err := c.GetLiveness(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetLivenessResponse(rsp)
}

// BrowseMemoriesWithResponse Browse committed Memories
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /memories (the `BrowseMemories` operationId).
func (c *ClientWithResponses) BrowseMemoriesWithResponse(ctx context.Context, params *BrowseMemoriesParams, reqEditors ...RequestEditorFn) (*BrowseMemoriesResponse, error) {
	rsp, err := c.BrowseMemories(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBrowseMemoriesResponse(rsp)
}

// ImportMemoryWithBodyWithResponse Durably import one Blob as a Memory
//
// Upload one Blob and return after its bytes are durably published and
// the Memory is committed. A Blob may contain at most 100 MiB
// (104857600 bytes). The server permits bounded multipart protocol
// overhead in addition to that Blob limit. Duplicate content is rejected
// with HTTP 409. Document Understanding is not performed by this request.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /memories/import (the `ImportMemory` operationId).
func (c *ClientWithResponses) ImportMemoryWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ImportMemoryResponse, error) {
	rsp, err := c.ImportMemoryWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseImportMemoryResponse(rsp)
}

// SearchMemoriesWithResponse Search committed Memories
//
// Search results are returned in ranked pages. Supply the returned cursor
// with the same trimmed query to continue. Cursors do not snapshot Vault
// mutations between requests.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /memories/search (the `SearchMemories` operationId).
func (c *ClientWithResponses) SearchMemoriesWithResponse(ctx context.Context, params *SearchMemoriesParams, reqEditors ...RequestEditorFn) (*SearchMemoriesResponse, error) {
	rsp, err := c.SearchMemories(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSearchMemoriesResponse(rsp)
}

// DeleteMemoryWithResponse Delete one Memory and its Blob
//
// Permanently deletes the Memory, its Understanding Runs, and the
// immutable Blob referenced by it. The Vault reuses the Blob only when
// its content is imported again.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /memories/{memoryId} (the `DeleteMemory` operationId).
func (c *ClientWithResponses) DeleteMemoryWithResponse(ctx context.Context, memoryId MemoryId, reqEditors ...RequestEditorFn) (*DeleteMemoryResponse, error) {
	rsp, err := c.DeleteMemory(ctx, memoryId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteMemoryResponse(rsp)
}

// GetMemoryWithResponse Get committed Memory details
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /memories/{memoryId} (the `GetMemory` operationId).
func (c *ClientWithResponses) GetMemoryWithResponse(ctx context.Context, memoryId MemoryId, reqEditors ...RequestEditorFn) (*GetMemoryResponse, error) {
	rsp, err := c.GetMemory(ctx, memoryId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMemoryResponse(rsp)
}

// GetMemoryContentWithResponse Download and verify a Memory's immutable Blob
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /memories/{memoryId}/content (the `GetMemoryContent` operationId).
func (c *ClientWithResponses) GetMemoryContentWithResponse(ctx context.Context, memoryId MemoryId, reqEditors ...RequestEditorFn) (*GetMemoryContentResponse, error) {
	rsp, err := c.GetMemoryContent(ctx, memoryId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMemoryContentResponse(rsp)
}

// RebuildMemoryWithBodyWithResponse Request a Memory Rebuild
//
// Accept process-local work using current Document Understanding methods.
// An optional user_note replaces the saved Memory guidance; absent or
// null user_note reuses the saved note, and an empty string clears it.
// The original Blob and previous active Run remain unchanged. Acceptance
// is best effort: queued/running work and polling handles are lost on
// restart. Competing queued/running work returns 409 without scheduling
// or changing the saved note.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /memories/{memoryId}/rebuild (the `RebuildMemory` operationId).
func (c *ClientWithResponses) RebuildMemoryWithBodyWithResponse(ctx context.Context, memoryId MemoryId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RebuildMemoryResponse, error) {
	rsp, err := c.RebuildMemoryWithBody(ctx, memoryId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRebuildMemoryResponse(rsp)
}

// RebuildMemoryWithResponse Request a Memory Rebuild
//
// Accept process-local work using current Document Understanding methods.
// An optional user_note replaces the saved Memory guidance; absent or
// null user_note reuses the saved note, and an empty string clears it.
// The original Blob and previous active Run remain unchanged. Acceptance
// is best effort: queued/running work and polling handles are lost on
// restart. Competing queued/running work returns 409 without scheduling
// or changing the saved note.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /memories/{memoryId}/rebuild (the `RebuildMemory` operationId).
func (c *ClientWithResponses) RebuildMemoryWithResponse(ctx context.Context, memoryId MemoryId, body RebuildMemoryJSONRequestBody, reqEditors ...RequestEditorFn) (*RebuildMemoryResponse, error) {
	rsp, err := c.RebuildMemory(ctx, memoryId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRebuildMemoryResponse(rsp)
}

// GetReadinessWithResponse Check whether the server can accept requests
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /readyz (the `GetReadiness` operationId).
func (c *ClientWithResponses) GetReadinessWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetReadinessResponse, error) {
	rsp, err := c.GetReadiness(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetReadinessResponse(rsp)
}

// GetRebuildStatusWithResponse Poll a retained process-local Rebuild
//
// Retained until superseded by a newly accepted attempt, Memory deletion,
// or restart. Terminal handles remain readable; no artifacts are returned.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /rebuild-status/{rebuildId} (the `GetRebuildStatus` operationId).
func (c *ClientWithResponses) GetRebuildStatusWithResponse(ctx context.Context, rebuildId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetRebuildStatusResponse, error) {
	rsp, err := c.GetRebuildStatus(ctx, rebuildId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRebuildStatusResponse(rsp)
}

// ParseGetLivenessResponse parses an HTTP response from a GetLivenessWithResponse call
func ParseGetLivenessResponse(rsp *http.Response) (*GetLivenessResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetLivenessResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseBrowseMemoriesResponse parses an HTTP response from a BrowseMemoriesWithResponse call
func ParseBrowseMemoriesResponse(rsp *http.Response) (*BrowseMemoriesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BrowseMemoriesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MemoryPage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseImportMemoryResponse parses an HTTP response from a ImportMemoryWithResponse call
func ParseImportMemoryResponse(rsp *http.Response) (*ImportMemoryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ImportMemoryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest MemorySummary
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON413 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseSearchMemoriesResponse parses an HTTP response from a SearchMemoriesWithResponse call
func ParseSearchMemoriesResponse(rsp *http.Response) (*SearchMemoriesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SearchMemoriesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SearchPage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	switch {
	case rsp.StatusCode == 200:
		var headers SearchMemoriesResponse200Headers
		if values := rsp.Header.Values("Cache-Control"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Cache-Control", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.CacheControl = &value
		}
		response.Headers200 = &headers
	case rsp.StatusCode == 400:
		var headers SearchMemoriesResponse400Headers
		if values := rsp.Header.Values("Cache-Control"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Cache-Control", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.CacheControl = &value
		}
		response.Headers400 = &headers
	}

	return response, nil
}

// ParseDeleteMemoryResponse parses an HTTP response from a DeleteMemoryWithResponse call
func ParseDeleteMemoryResponse(rsp *http.Response) (*DeleteMemoryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteMemoryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetMemoryResponse parses an HTTP response from a GetMemoryWithResponse call
func ParseGetMemoryResponse(rsp *http.Response) (*GetMemoryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMemoryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MemoryDetail
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetMemoryContentResponse parses an HTTP response from a GetMemoryContentWithResponse call
func ParseGetMemoryContentResponse(rsp *http.Response) (*GetMemoryContentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMemoryContentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 507:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON507 = &dest

	}

	switch {
	case rsp.StatusCode == 200:
		var headers GetMemoryContentResponse200Headers
		if values := rsp.Header.Values("Content-Disposition"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Content-Disposition", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.ContentDisposition = &value
		}
		if values := rsp.Header.Values("ETag"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "ETag", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.ETag = &value
		}
		response.Headers200 = &headers
	}

	return response, nil
}

// ParseRebuildMemoryResponse parses an HTTP response from a RebuildMemoryWithResponse call
func ParseRebuildMemoryResponse(rsp *http.Response) (*RebuildMemoryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RebuildMemoryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest RebuildStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest RebuildStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	switch {
	case rsp.StatusCode == 202:
		var headers RebuildMemoryResponse202Headers
		if values := rsp.Header.Values("Cache-Control"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Cache-Control", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.CacheControl = &value
		}
		response.Headers202 = &headers
	case rsp.StatusCode == 409:
		var headers RebuildMemoryResponse409Headers
		if values := rsp.Header.Values("Cache-Control"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Cache-Control", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.CacheControl = &value
		}
		response.Headers409 = &headers
	}

	return response, nil
}

// ParseGetReadinessResponse parses an HTTP response from a GetReadinessWithResponse call
func ParseGetReadinessResponse(rsp *http.Response) (*GetReadinessResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetReadinessResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetRebuildStatusResponse parses an HTTP response from a GetRebuildStatusWithResponse call
func ParseGetRebuildStatusResponse(rsp *http.Response) (*GetRebuildStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRebuildStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RebuildStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	switch {
	case rsp.StatusCode == 200:
		var headers GetRebuildStatusResponse200Headers
		if values := rsp.Header.Values("Cache-Control"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Cache-Control", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.CacheControl = &value
		}
		response.Headers200 = &headers
	case rsp.StatusCode == 404:
		var headers GetRebuildStatusResponse404Headers
		if values := rsp.Header.Values("Cache-Control"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Cache-Control", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.CacheControl = &value
		}
		response.Headers404 = &headers
	}

	return response, nil
}
