// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ServerUrlLocalMemorydServer defines the Server URL for Local memoryd server
const ServerUrlLocalMemorydServer = "/api/v0"

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// DuplicateMemory defines model for DuplicateMemory.
type DuplicateMemory struct {
	Id openapi_types.UUID `json:"id"`
}

// Error defines model for Error.
type Error struct {
	// Code Example: memory_not_found
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`

	// ExistingMemory Present on a duplicate import conflict so clients can recover.
	ExistingMemory *DuplicateMemory `json:"existing_memory,omitempty"`
	Message        string           `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status HealthResponseStatus `json:"status"`

	// VaultPath Human-readable vault location, when configured.
	VaultPath *string `json:"vault_path,omitempty"`
	Version   *string `json:"version,omitempty"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// ImportContext Stored provenance from the first successful import.
type ImportContext struct {
	ByteSize             *int64     `json:"byte_size,omitempty"`
	ContentHash          *string    `json:"content_hash,omitempty"`
	FilesystemCreatedAt  *time.Time `json:"filesystem_created_at,omitempty"`
	FilesystemModifiedAt *time.Time `json:"filesystem_modified_at,omitempty"`
	FullPath             *string    `json:"full_path,omitempty"`
	MediaType            *string    `json:"media_type,omitempty"`
	OriginalFilename     string     `json:"original_filename"`
	RelativePath         *string    `json:"relative_path,omitempty"`
}

// ImportContextInput Optional client-observed provenance sent as one application/json
// multipart part. The original filename comes from the Blob part. Omitted
// values remain unknown; malformed timestamps reject the import.
type ImportContextInput struct {
	FilesystemCreatedAt  *time.Time `json:"filesystem_created_at,omitempty"`
	FilesystemModifiedAt *time.Time `json:"filesystem_modified_at,omitempty"`
	FullPath             *string    `json:"full_path,omitempty"`
	RelativePath         *string    `json:"relative_path,omitempty"`
}

// ImportMultipart defines model for ImportMultipart.
type ImportMultipart struct {
	// File One Blob of at most 100 MiB with a nonblank filename in
	// Content-Disposition. The server detects its Media Type from content
	// first and may fall back to a valid, specific part Content-Type.
	File openapi_types.File `json:"file"`

	// ImportContext Optional client-observed provenance sent as one application/json
	// multipart part. The original filename comes from the Blob part. Omitted
	// values remain unknown; malformed timestamps reject the import.
	ImportContext *ImportContextInput `json:"import_context,omitempty"`
}

// MemoryDetail defines model for MemoryDetail.
type MemoryDetail struct {
	// ContentUrl Relative URL of the content download endpoint.
	ContentUrl *string `json:"content_url,omitempty"`

	// ImportContext Stored provenance from the first successful import.
	ImportContext ImportContext `json:"import_context"`
	Memory        MemorySummary `json:"memory"`
}

// MemoryPage defines model for MemoryPage.
type MemoryPage struct {
	Items      []MemorySummary `json:"items"`
	NextCursor *string         `json:"next_cursor,omitempty"`
}

// MemorySummary defines model for MemorySummary.
type MemorySummary struct {
	// BlobHash Canonical SHA-256 Blobref of the immutable Blob.
	BlobHash           string             `json:"blob_hash"`
	ByteSize           int64              `json:"byte_size"`
	Id                 openapi_types.UUID `json:"id"`
	ImportedAt         time.Time          `json:"imported_at"`
	MediaType          string             `json:"media_type"`
	OriginalCreatedAt  *time.Time         `json:"original_created_at,omitempty"`
	OriginalFilename   string             `json:"original_filename"`
	OriginalModifiedAt *time.Time         `json:"original_modified_at,omitempty"`
}

// Cursor defines model for Cursor.
type Cursor = string

// Limit defines model for Limit.
type Limit = int32

// MemoryId defines model for MemoryId.
type MemoryId = openapi_types.UUID

// BrowseMemoriesParams defines parameters for BrowseMemories.
type BrowseMemoriesParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ImportMemoryMultipartRequestBody defines body for ImportMemory for multipart/form-data ContentType.
type ImportMemoryMultipartRequestBody = ImportMultipart

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetLiveness Check whether the process is alive
	// (GET /livez)
	GetLiveness(ctx echo.Context) error
	// BrowseMemories Browse committed Memories
	// (GET /memories)
	BrowseMemories(ctx echo.Context, params BrowseMemoriesParams) error
	// ImportMemory Durably import one Blob as a Memory
	// (POST /memories/import)
	ImportMemory(ctx echo.Context) error
	// GetMemory Get committed Memory details
	// (GET /memories/{memoryId})
	GetMemory(ctx echo.Context, memoryId MemoryId) error
	// GetMemoryContent Download and verify a Memory's immutable Blob
	// (GET /memories/{memoryId}/content)
	GetMemoryContent(ctx echo.Context, memoryId MemoryId) error
	// GetReadiness Check whether the server can accept requests
	// (GET /readyz)
	GetReadiness(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetLiveness converts echo context to params.
func (w *ServerInterfaceWrapper) GetLiveness(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetLiveness(ctx)
	return err
}

// BrowseMemories converts echo context to params.
func (w *ServerInterfaceWrapper) BrowseMemories(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params BrowseMemoriesParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", ctx.QueryParams(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cursor: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.BrowseMemories(ctx, params)
	return err
}

// ImportMemory converts echo context to params.
func (w *ServerInterfaceWrapper) ImportMemory(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ImportMemory(ctx)
	return err
}

// GetMemory converts echo context to params.
func (w *ServerInterfaceWrapper) GetMemory(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memoryId" -------------
	var memoryId MemoryId

	err = runtime.BindStyledParameterWithOptions("simple", "memoryId", ctx.Param("memoryId"), &memoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memoryId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMemory(ctx, memoryId)
	return err
}

// GetMemoryContent converts echo context to params.
func (w *ServerInterfaceWrapper) GetMemoryContent(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memoryId" -------------
	var memoryId MemoryId

	err = runtime.BindStyledParameterWithOptions("simple", "memoryId", ctx.Param("memoryId"), &memoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memoryId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMemoryContent(ctx, memoryId)
	return err
}

// GetReadiness converts echo context to params.
func (w *ServerInterfaceWrapper) GetReadiness(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetReadiness(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/livez", wrapper.GetLiveness, options.OperationMiddlewares["getLiveness"]...)
	router.GET(options.BaseURL+"/readyz", wrapper.GetReadiness, options.OperationMiddlewares["getReadiness"]...)
	router.GET(options.BaseURL+"/memories", wrapper.BrowseMemories, options.OperationMiddlewares["browseMemories"]...)
	router.GET(options.BaseURL+"/memories/:memoryId", wrapper.GetMemory, options.OperationMiddlewares["getMemory"]...)
	router.GET(options.BaseURL+"/memories/:memoryId/content", wrapper.GetMemoryContent, options.OperationMiddlewares["getMemoryContent"]...)
	router.POST(options.BaseURL+"/memories/import", wrapper.ImportMemory, options.OperationMiddlewares["importMemory"]...)

}

type GetLivenessRequestObject struct {
}

type GetLivenessResponseObject interface {
	VisitGetLivenessResponse(w http.ResponseWriter) error
}

type GetLiveness200JSONResponse HealthResponse

func (response GetLiveness200JSONResponse) VisitGetLivenessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type BrowseMemoriesRequestObject struct {
	Params BrowseMemoriesParams
}

type BrowseMemoriesResponseObject interface {
	VisitBrowseMemoriesResponse(w http.ResponseWriter) error
}

type BrowseMemories200JSONResponse MemoryPage

func (response BrowseMemories200JSONResponse) VisitBrowseMemoriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type BrowseMemories400JSONResponse Error

func (response BrowseMemories400JSONResponse) VisitBrowseMemoriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ImportMemoryRequestObject struct {
	Body *multipart.Reader
}

type ImportMemoryResponseObject interface {
	VisitImportMemoryResponse(w http.ResponseWriter) error
}

type ImportMemory201JSONResponse MemorySummary

func (response ImportMemory201JSONResponse) VisitImportMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type ImportMemory400JSONResponse Error

func (response ImportMemory400JSONResponse) VisitImportMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ImportMemory409JSONResponse Error

func (response ImportMemory409JSONResponse) VisitImportMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ImportMemory413JSONResponse Error

func (response ImportMemory413JSONResponse) VisitImportMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type ImportMemory500JSONResponse Error

func (response ImportMemory500JSONResponse) VisitImportMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetMemoryRequestObject struct {
	MemoryId MemoryId `json:"memoryId"`
}

type GetMemoryResponseObject interface {
	VisitGetMemoryResponse(w http.ResponseWriter) error
}

type GetMemory200JSONResponse MemoryDetail

func (response GetMemory200JSONResponse) VisitGetMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMemory404JSONResponse Error

func (response GetMemory404JSONResponse) VisitGetMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetMemoryContentRequestObject struct {
	MemoryId MemoryId `json:"memoryId"`
}

type GetMemoryContentResponseObject interface {
	VisitGetMemoryContentResponse(w http.ResponseWriter) error
}

type GetMemoryContent200ResponseHeaders struct {
	ContentDisposition *string
	ETag               *string
}

type GetMemoryContent200AsteriskResponse struct {
	Body          io.Reader
	Headers       GetMemoryContent200ResponseHeaders
	ContentType   string
	ContentLength int64
}

func (response GetMemoryContent200AsteriskResponse) VisitGetMemoryContentResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", response.ContentType)
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	if response.Headers.ContentDisposition != nil {
		w.Header().Set("Content-Disposition", fmt.Sprint(*response.Headers.ContentDisposition))
	}
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetMemoryContent404JSONResponse Error

func (response GetMemoryContent404JSONResponse) VisitGetMemoryContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetMemoryContent500JSONResponse Error

func (response GetMemoryContent500JSONResponse) VisitGetMemoryContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadinessRequestObject struct {
}

type GetReadinessResponseObject interface {
	VisitGetReadinessResponse(w http.ResponseWriter) error
}

type GetReadiness200JSONResponse HealthResponse

func (response GetReadiness200JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetLiveness Check whether the process is alive
	// (GET /livez)
	GetLiveness(ctx context.Context, request GetLivenessRequestObject) (GetLivenessResponseObject, error)
	// BrowseMemories Browse committed Memories
	// (GET /memories)
	BrowseMemories(ctx context.Context, request BrowseMemoriesRequestObject) (BrowseMemoriesResponseObject, error)
	// ImportMemory Durably import one Blob as a Memory
	// (POST /memories/import)
	ImportMemory(ctx context.Context, request ImportMemoryRequestObject) (ImportMemoryResponseObject, error)
	// GetMemory Get committed Memory details
	// (GET /memories/{memoryId})
	GetMemory(ctx context.Context, request GetMemoryRequestObject) (GetMemoryResponseObject, error)
	// GetMemoryContent Download and verify a Memory's immutable Blob
	// (GET /memories/{memoryId}/content)
	GetMemoryContent(ctx context.Context, request GetMemoryContentRequestObject) (GetMemoryContentResponseObject, error)
	// GetReadiness Check whether the server can accept requests
	// (GET /readyz)
	GetReadiness(ctx context.Context, request GetReadinessRequestObject) (GetReadinessResponseObject, error)
}

type StrictHandlerFunc func(ctx echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetLiveness operation middleware
func (sh *strictHandler) GetLiveness(ctx echo.Context) error {
	var request GetLivenessRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetLiveness(ctx.Request().Context(), request.(GetLivenessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLiveness")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetLivenessResponseObject); ok {
		return validResponse.VisitGetLivenessResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// BrowseMemories operation middleware
func (sh *strictHandler) BrowseMemories(ctx echo.Context, params BrowseMemoriesParams) error {
	var request BrowseMemoriesRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.BrowseMemories(ctx.Request().Context(), request.(BrowseMemoriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "BrowseMemories")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(BrowseMemoriesResponseObject); ok {
		return validResponse.VisitBrowseMemoriesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ImportMemory operation middleware
func (sh *strictHandler) ImportMemory(ctx echo.Context) error {
	var request ImportMemoryRequestObject

	if reader, err := ctx.Request().MultipartReader(); err != nil {
		return err
	} else {
		request.Body = reader
	}

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ImportMemory(ctx.Request().Context(), request.(ImportMemoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ImportMemory")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ImportMemoryResponseObject); ok {
		return validResponse.VisitImportMemoryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetMemory operation middleware
func (sh *strictHandler) GetMemory(ctx echo.Context, memoryId MemoryId) error {
	var request GetMemoryRequestObject

	request.MemoryId = memoryId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMemory(ctx.Request().Context(), request.(GetMemoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMemory")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetMemoryResponseObject); ok {
		return validResponse.VisitGetMemoryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetMemoryContent operation middleware
func (sh *strictHandler) GetMemoryContent(ctx echo.Context, memoryId MemoryId) error {
	var request GetMemoryContentRequestObject

	request.MemoryId = memoryId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMemoryContent(ctx.Request().Context(), request.(GetMemoryContentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMemoryContent")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetMemoryContentResponseObject); ok {
		return validResponse.VisitGetMemoryContentResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetReadiness operation middleware
func (sh *strictHandler) GetReadiness(ctx echo.Context) error {
	var request GetReadinessRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadiness(ctx.Request().Context(), request.(GetReadinessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadiness")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetReadinessResponseObject); ok {
		return validResponse.VisitGetReadinessResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFltj9NIEv4rpb6V9m6VSTIwcEfuEzCrBQkEguG+kLmoY5eTXtrdprscJjvKf19Vt+04tjMv4kV8gUzc",
	"rqqueuqpl1yLxOaFNWjIi9m1KKSTORK68Nfz0nnr+JMyYiY+l+i2YiSMzFHMRBKfjoRP1phLPkbbgp94",
	"csqsxG43Eq9UruiYBB0etgWkmMlSk5g9mo5EZl0uScyEMvTwgRiJXF6pvMzF7HQ6HYlcmeqvUa1YGcIV",
	"uqD5NebWbV+mjfJC0nqvO68fj4TDz6VymIoZuRLb5jQWlKVKRaOmud+uPhzcdV4WWiWSMKoO/nS2QEcK",
	"wwGV3kVo26CP/M5lc8Yu/8SExG4kfnfOur6GxKbI/+OVzAu9v+fCWFpktjQDCkciRZJKBwEyTRUpa6R+",
	"2xIc/dIzAq+UJ2VWi7y5sNT6TSZmH6/FLw4zMRP/mOwRNqmcNel6anfJRvjEqYKVi5l469CjIbAGJKT1",
	"cVB5YR1BYk2mVULgLSRasWxIpAGHid2gG3OYS63lUmM0fjcSOXovVzgM07bHgw/354e8/wKlpvU79IU1",
	"Hvth8CSpDJ/QMEI/CvupJWjv+Q2jfRGQObvuuOBFmUtz4lCmfA8IR0HbRPLzEXxZowmOUKvSYToeCuwG",
	"nQ/CbrtzZfDQXV8Glz+3hvCK+la+J+swhcLZDRppEoTM2RxojZAp5wl8mSTofVbqKnps6aG7llvChVd/",
	"4UF6KEOPz0Qrz6f9PB+JhA0ztFhLv44MRoSOLfu/X8sHjx6ffJQn2fTkyeX147PdL0NeypRGv/WE+SJx",
	"KAnThaQDU1JJeEIqxx6wbhaX21Rl6mvllVo3EOk9zTFVchG/HnhsnVopI/WCrYrUN3DKoZakNnhMTQct",
	"faG3AuelKUo6TjCZ1B67HPCmiAerFD+xS49ucwi2QBLSgzUIsog0oayZ/OmtmZu81KQK6Qj4nzFcrBFq",
	"46E2HhKbo9/D9pm2y+r8m1wRYTo3G6lL9OAwl8pAaT4Z+8X8F3KpOaaYAgfTk8wLPsQeCKIqwM9ND/L3",
	"w9zXYuyemLoDHI5E+3Xt8D4nssl9+nhjKofbDCRBbj3B6XQKr9Uz+KJoDRKMNUstzad9wJSZm+cx70/O",
	"lS+sD5CK8Q0YcZAiYUIeFHl4zTkCF9uiIqeKM+YmMpQ0KeRyC5nUGpYy+QRkQcJGapWOwBeYqEwlARJQ",
	"q2VhMa6Nw5fKyNDd5PLqFZoVu+50evafR/9+PJ0OxCCCY5HsmfWmkjmQTd20DB4eysRYZc9DlR/qGSKD",
	"lk734/OuggJ8ePeKY8Sorl6A1H4x2soU0KSFVYbG4tteM/Jb3Vrc9Fq84fsyzzkEXcdUMnq2HPfV26pT",
	"6PRvhPnhh3vY1OiSzsnwt8ErWiRNj31LIejcKZpw/Aa13t4lltoum2p5GOzn0lijEqnh/YunJw8ePQ6p",
	"6TCrI6/yvKTQjfCDUMjvX26/ptrfqYOu43xPTrxrJf0WPcLdynJz6hv0Ef2xYtSCwsHt2yEaMvXQv30I",
	"si5lMjvQ0l5cvA304WRCkFkX+aR0Dg3pLddLjTkawjR0uhoimOF/ofn1WiU4hqdzU32tYuEvPbqTjfKK",
	"kUlrZVZQOKyaheU2KIkSmOqVB5WioeDRuame16Rms1AyAr4Dv5Oi1iCVwtO3L0WrsxbT8el4GqJVoJGF",
	"EjPxcDwdP4zJsQ45N9Fqg3/xpxWGCHJChkaF51PxB9IrtUGD3odxNI4V4c0H02mLo/ljt8vh7/YT602E",
	"1JlaQpwO48P1s3A2Qe/ZTZLNHgfs+JpOxPM1Jp94+qA1xvh132CnyZVnmK2DSnHJIibBgxULDfrhmbNf",
	"PL6uj40O1hFHRsr9kUncNexGtx6s9hq7y+/o7FYdGXD0UyjkChls9W3HDKGzb2hA3BAcCTJTAXoKuWBC",
	"o9MNc4wF98axB4ZWWOroNgE9jO8k0kMoPdYPzIwfitA22Lr346x0SKUzIDNCFzKQOciDdAhp6eRSb6Eo",
	"l1r5Nab8wtww9PY80Bg6hqdRKrd07Enu2Dut5dz8s+nMoqJ/HTSPBbo82MAbE0yhNUc4Szaxem540bBG",
	"mQKLr4YabhxpLSkaENZbY2iWHQ3HqHpIYP4JXW4gxrPpkzGc26RkBoQPJkXnSZqU+Ux5MJbYsGrgCLSl",
	"fB3JyFWH6VS15HXzU518ZtNtB2TN9SYs/CSVJO+Os27jvzssNdX2pZNnp984z/ad3yDcOyje/gTJxvqf",
	"/Bj9CWMoDeszD3KPx2jF6cMfY0Wc8txATrX8Q9aClm4VbXv0oyJUrRUzqTSnFmbWIbT4ZU8uHZY8r6ip",
	"ErBnNHZ0k3m38eV1vYze3dQitBL5u9asak484qrKI6GRIg8+rv8iCUA1t1XwPvuh6dUkN6QWI1uG/XQ3",
	"ZH8g9fgA6g34YKzu24c0vzzsLo+EedLyys3hrvYNt0f9t8lvh/7s7yUGfr3oe7NZj9U9fl2IQ2GmNSoH",
	"PBkEBDSbALVCT3OzlhuEJaKBDbrQX4NcSWU8VT12h4ZD0eIiWv/g1F/qDGycy9UqxrtZCPEkUW8jxrf8",
	"IvX7hVz1hV60RgCeiEbwubSsgzPZxPqMhhRtgeTqZh27nwv9P5BHuwH+NQ5SzOy58p4bGesgsc6VRS8x",
	"z+t1EiMr4GfbkOivvrN7+C6Zyr+1bG8c096hTNXPMadVrWpoAWW6DTvLJMGiqaf+9smtksE/nXXeHZzh",
	"WFp4Izr30KZXYV6vp+R4ToxE2CqKiSzUZDMNI1cl97r+JbaSvxs13zQR3V3u/h4A",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
