// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ServerUrlLocalMemorydServer defines the Server URL for Local memoryd server
const ServerUrlLocalMemorydServer = "/api/v0"

// Defines values for FactValueType.
const (
	Boolean  FactValueType = "boolean"
	Date     FactValueType = "date"
	Datetime FactValueType = "datetime"
	Integer  FactValueType = "integer"
	Json     FactValueType = "json"
	Null     FactValueType = "null"
	Number   FactValueType = "number"
	String   FactValueType = "string"
)

// Valid indicates whether the value is a known member of the FactValueType enum.
func (e FactValueType) Valid() bool {
	switch e {
	case Boolean:
		return true
	case Date:
		return true
	case Datetime:
		return true
	case Integer:
		return true
	case Json:
		return true
	case Null:
		return true
	case Number:
		return true
	case String:
		return true
	default:
		return false
	}
}

// Defines values for FactFilterOperator.
const (
	Contains           FactFilterOperator = "contains"
	Equals             FactFilterOperator = "equals"
	GreaterThan        FactFilterOperator = "greater_than"
	GreaterThanOrEqual FactFilterOperator = "greater_than_or_equal"
	LessThan           FactFilterOperator = "less_than"
	LessThanOrEqual    FactFilterOperator = "less_than_or_equal"
)

// Valid indicates whether the value is a known member of the FactFilterOperator enum.
func (e FactFilterOperator) Valid() bool {
	switch e {
	case Contains:
		return true
	case Equals:
		return true
	case GreaterThan:
		return true
	case GreaterThanOrEqual:
		return true
	case LessThan:
		return true
	case LessThanOrEqual:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for ImportCompletedEventEvent.
const (
	ImportCompleted ImportCompletedEventEvent = "import_completed"
)

// Valid indicates whether the value is a known member of the ImportCompletedEventEvent enum.
func (e ImportCompletedEventEvent) Valid() bool {
	switch e {
	case ImportCompleted:
		return true
	default:
		return false
	}
}

// Defines values for ProcessingLogKind.
const (
	ProcessingLogKindError            ProcessingLogKind = "error"
	ProcessingLogKindLifecycle        ProcessingLogKind = "lifecycle"
	ProcessingLogKindModelOutput      ProcessingLogKind = "model_output"
	ProcessingLogKindStderr           ProcessingLogKind = "stderr"
	ProcessingLogKindStdout           ProcessingLogKind = "stdout"
	ProcessingLogKindStructuredResult ProcessingLogKind = "structured_result"
	ProcessingLogKindTool             ProcessingLogKind = "tool"
	ProcessingLogKindUsage            ProcessingLogKind = "usage"
)

// Valid indicates whether the value is a known member of the ProcessingLogKind enum.
func (e ProcessingLogKind) Valid() bool {
	switch e {
	case ProcessingLogKindError:
		return true
	case ProcessingLogKindLifecycle:
		return true
	case ProcessingLogKindModelOutput:
		return true
	case ProcessingLogKindStderr:
		return true
	case ProcessingLogKindStdout:
		return true
	case ProcessingLogKindStructuredResult:
		return true
	case ProcessingLogKindTool:
		return true
	case ProcessingLogKindUsage:
		return true
	default:
		return false
	}
}

// Defines values for UnderstandingCompletedEventEvent.
const (
	CodexEnhancementCompleted UnderstandingCompletedEventEvent = "codex_enhancement_completed"
	RebuildCompleted          UnderstandingCompletedEventEvent = "rebuild_completed"
)

// Valid indicates whether the value is a known member of the UnderstandingCompletedEventEvent enum.
func (e UnderstandingCompletedEventEvent) Valid() bool {
	switch e {
	case CodexEnhancementCompleted:
		return true
	case RebuildCompleted:
		return true
	default:
		return false
	}
}

// Defines values for UnderstandingFailedEventEvent.
const (
	CodexEnhancementFailed UnderstandingFailedEventEvent = "codex_enhancement_failed"
	ImportFailed           UnderstandingFailedEventEvent = "import_failed"
	RebuildFailed          UnderstandingFailedEventEvent = "rebuild_failed"
)

// Valid indicates whether the value is a known member of the UnderstandingFailedEventEvent enum.
func (e UnderstandingFailedEventEvent) Valid() bool {
	switch e {
	case CodexEnhancementFailed:
		return true
	case ImportFailed:
		return true
	case RebuildFailed:
		return true
	default:
		return false
	}
}

// Defines values for UnderstandingProgressEventEvent.
const (
	ImportStarted         UnderstandingProgressEventEvent = "import_started"
	UnderstandingProgress UnderstandingProgressEventEvent = "understanding_progress"
	UnderstandingStarted  UnderstandingProgressEventEvent = "understanding_started"
)

// Valid indicates whether the value is a known member of the UnderstandingProgressEventEvent enum.
func (e UnderstandingProgressEventEvent) Valid() bool {
	switch e {
	case ImportStarted:
		return true
	case UnderstandingProgress:
		return true
	case UnderstandingStarted:
		return true
	default:
		return false
	}
}

// Defines values for UnderstandingRunPipeline.
const (
	CodexEnhancement UnderstandingRunPipeline = "codex_enhancement"
	Regular          UnderstandingRunPipeline = "regular"
)

// Valid indicates whether the value is a known member of the UnderstandingRunPipeline enum.
func (e UnderstandingRunPipeline) Valid() bool {
	switch e {
	case CodexEnhancement:
		return true
	case Regular:
		return true
	default:
		return false
	}
}

// Defines values for UnderstandingState.
const (
	Done       UnderstandingState = "Done"
	Failed     UnderstandingState = "Failed"
	InProgress UnderstandingState = "InProgress"
)

// Valid indicates whether the value is a known member of the UnderstandingState enum.
func (e UnderstandingState) Valid() bool {
	switch e {
	case Done:
		return true
	case Failed:
		return true
	case InProgress:
		return true
	default:
		return false
	}
}

// CodexEnhancementRequest defines model for CodexEnhancementRequest.
type CodexEnhancementRequest struct {
	// ConfirmRepeat Confirm repeating an equivalent prior Codex enhancement.
	ConfirmRepeat *bool `json:"confirm_repeat,omitempty"`

	// Instructions Optional user direction for the explicit Codex task.
	Instructions *string `json:"instructions,omitempty"`
}

// DerivedContent defines model for DerivedContent.
type DerivedContent struct {
	Kind     string                  `json:"kind"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Text     *string                 `json:"text,omitempty"`
}

// DuplicateMemory defines model for DuplicateMemory.
type DuplicateMemory struct {
	Id                 openapi_types.UUID `json:"id"`
	UnderstandingState UnderstandingState `json:"understanding_state"`
}

// Error defines model for Error.
type Error struct {
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`

	// ExistingMemory Present on a duplicate import conflict so clients can recover.
	ExistingMemory *DuplicateMemory `json:"existing_memory,omitempty"`
	Message        string           `json:"message"`
}

// Fact defines model for Fact.
type Fact struct {
	Confidence *float64 `json:"confidence,omitempty"`
	Name       string   `json:"name"`
	Namespace  string   `json:"namespace"`

	// Origin Extractor, plugin, or import provenance that asserted the Fact.
	Origin string `json:"origin"`

	// Value Typed JSON value asserted by the Fact.
	Value     interface{}   `json:"value"`
	ValueType FactValueType `json:"value_type"`
}

// FactValueType defines model for Fact.ValueType.
type FactValueType string

// FactFilter defines model for FactFilter.
type FactFilter struct {
	Name      string             `json:"name"`
	Namespace string             `json:"namespace"`
	Operator  FactFilterOperator `json:"operator"`

	// Value Typed value used for exact Fact filtering.
	Value interface{} `json:"value"`
}

// FactFilterOperator defines model for FactFilter.Operator.
type FactFilterOperator string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status HealthResponseStatus `json:"status"`

	// VaultPath Human-readable vault location, when configured.
	VaultPath *string `json:"vault_path,omitempty"`
	Version   *string `json:"version,omitempty"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// ImportCompletedEvent defines model for ImportCompletedEvent.
type ImportCompletedEvent struct {
	Event  ImportCompletedEventEvent `json:"event"`
	Memory MemorySummary             `json:"memory"`
}

// ImportCompletedEventEvent defines model for ImportCompletedEvent.Event.
type ImportCompletedEventEvent string

// ImportContext defines model for ImportContext.
type ImportContext struct {
	ByteSize             *int64     `json:"byte_size,omitempty"`
	ContentHash          *string    `json:"content_hash,omitempty"`
	FilesystemCreatedAt  *time.Time `json:"filesystem_created_at,omitempty"`
	FilesystemModifiedAt *time.Time `json:"filesystem_modified_at,omitempty"`
	FullPath             *string    `json:"full_path,omitempty"`
	MediaType            *string    `json:"media_type,omitempty"`
	OriginalFilename     string     `json:"original_filename"`
	RelativePath         *string    `json:"relative_path,omitempty"`
}

// ImportEvent One JSON payload carried by an SSE event.
type ImportEvent struct {
	union json.RawMessage
}

// ImportMultipart defines model for ImportMultipart.
type ImportMultipart struct {
	// File One PDF, JPEG, or PNG Blob.
	File                 openapi_types.File `json:"file"`
	FilesystemCreatedAt  *time.Time         `json:"filesystem_created_at,omitempty"`
	FilesystemModifiedAt *time.Time         `json:"filesystem_modified_at,omitempty"`

	// FullPath Original full path when the importing client can provide it.
	FullPath *string `json:"full_path,omitempty"`

	// MediaType Client-observed media type; the server validates the content.
	MediaType *string `json:"media_type,omitempty"`

	// RelativePath Browser-provided path relative to the selected directory.
	RelativePath *string `json:"relative_path,omitempty"`
}

// MemoryDetail defines model for MemoryDetail.
type MemoryDetail struct {
	ActiveRun *UnderstandingRun `json:"active_run,omitempty"`

	// ContentUrl Relative URL of the content download endpoint.
	ContentUrl     *string          `json:"content_url,omitempty"`
	DerivedContent []DerivedContent `json:"derived_content"`
	Facts          []Fact           `json:"facts"`
	ImportContext  ImportContext    `json:"import_context"`
	Memory         MemorySummary    `json:"memory"`
}

// MemoryPage defines model for MemoryPage.
type MemoryPage struct {
	Items      []MemorySummary `json:"items"`
	NextCursor *string         `json:"next_cursor,omitempty"`
}

// MemorySummary defines model for MemorySummary.
type MemorySummary struct {
	ActiveRunId *openapi_types.UUID `json:"active_run_id,omitempty"`

	// BlobHash SHA-256 content hash of the immutable Blob.
	BlobHash           string             `json:"blob_hash"`
	ByteSize           int64              `json:"byte_size"`
	Id                 openapi_types.UUID `json:"id"`
	ImportedAt         time.Time          `json:"imported_at"`
	MediaType          string             `json:"media_type"`
	OriginalCreatedAt  *time.Time         `json:"original_created_at,omitempty"`
	OriginalFilename   string             `json:"original_filename"`
	OriginalModifiedAt *time.Time         `json:"original_modified_at,omitempty"`
	UnderstandingState UnderstandingState `json:"understanding_state"`
}

// ProcessingLog defines model for ProcessingLog.
type ProcessingLog struct {
	AttemptId openapi_types.UUID      `json:"attempt_id"`
	Id        openapi_types.UUID      `json:"id"`
	Kind      ProcessingLogKind       `json:"kind"`
	MemoryId  openapi_types.UUID      `json:"memory_id"`
	Message   string                  `json:"message"`
	Metadata  *map[string]interface{} `json:"metadata,omitempty"`
	RunId     *openapi_types.UUID     `json:"run_id,omitempty"`
	Timestamp time.Time               `json:"timestamp"`
	Truncated *bool                   `json:"truncated,omitempty"`
}

// ProcessingLogKind defines model for ProcessingLog.Kind.
type ProcessingLogKind string

// ProcessingLogPage defines model for ProcessingLogPage.
type ProcessingLogPage struct {
	Items      []ProcessingLog `json:"items"`
	NextCursor *string         `json:"next_cursor,omitempty"`
}

// QueryPlan defines model for QueryPlan.
type QueryPlan struct {
	Explanation   *string      `json:"explanation,omitempty"`
	FactFilters   []FactFilter `json:"fact_filters"`
	FullTextTerms []string     `json:"full_text_terms"`
}

// RunPage defines model for RunPage.
type RunPage struct {
	Items      []UnderstandingRun `json:"items"`
	NextCursor *string            `json:"next_cursor,omitempty"`
}

// SearchRequest defines model for SearchRequest.
type SearchRequest struct {
	Cursor *string `json:"cursor,omitempty"`
	Limit  *int32  `json:"limit,omitempty"`
	Query  string  `json:"query"`
}

// SearchResponse defines model for SearchResponse.
type SearchResponse struct {
	Items      []SearchResult `json:"items"`
	NextCursor *string        `json:"next_cursor,omitempty"`
	Plan       QueryPlan      `json:"plan"`
	Query      string         `json:"query"`
}

// SearchResult defines model for SearchResult.
type SearchResult struct {
	MatchedFacts []Fact        `json:"matched_facts"`
	MatchedTerms []string      `json:"matched_terms"`
	Memory       MemorySummary `json:"memory"`
}

// UnderstandingCompletedEvent defines model for UnderstandingCompletedEvent.
type UnderstandingCompletedEvent struct {
	Event  UnderstandingCompletedEventEvent `json:"event"`
	Memory MemorySummary                    `json:"memory"`
	Run    UnderstandingRun                 `json:"run"`
}

// UnderstandingCompletedEventEvent defines model for UnderstandingCompletedEvent.Event.
type UnderstandingCompletedEventEvent string

// UnderstandingEvent One JSON payload carried by a rebuild or Codex SSE event.
type UnderstandingEvent struct {
	union json.RawMessage
}

// UnderstandingFailedEvent defines model for UnderstandingFailedEvent.
type UnderstandingFailedEvent struct {
	Error    Error                         `json:"error"`
	Event    UnderstandingFailedEventEvent `json:"event"`
	MemoryId openapi_types.UUID            `json:"memory_id"`
}

// UnderstandingFailedEventEvent defines model for UnderstandingFailedEvent.Event.
type UnderstandingFailedEventEvent string

// UnderstandingProgressEvent defines model for UnderstandingProgressEvent.
type UnderstandingProgressEvent struct {
	Event    UnderstandingProgressEventEvent `json:"event"`
	MemoryId openapi_types.UUID              `json:"memory_id"`
	Message  *string                         `json:"message,omitempty"`
	Percent  *float64                        `json:"percent,omitempty"`

	// Phase Current understanding phase.
	Phase string `json:"phase"`
}

// UnderstandingProgressEventEvent defines model for UnderstandingProgressEvent.Event.
type UnderstandingProgressEventEvent string

// UnderstandingRun defines model for UnderstandingRun.
type UnderstandingRun struct {
	Active            bool                     `json:"active"`
	CompletedAt       time.Time                `json:"completed_at"`
	CreatedAt         time.Time                `json:"created_at"`
	ExtractorVersions *map[string]string       `json:"extractor_versions,omitempty"`
	Id                openapi_types.UUID       `json:"id"`
	MemoryId          openapi_types.UUID       `json:"memory_id"`
	Pipeline          UnderstandingRunPipeline `json:"pipeline"`
	PluginVersions    *map[string]string       `json:"plugin_versions,omitempty"`
	Warnings          *[]string                `json:"warnings,omitempty"`
}

// UnderstandingRunPipeline defines model for UnderstandingRun.Pipeline.
type UnderstandingRunPipeline string

// UnderstandingState defines model for UnderstandingState.
type UnderstandingState string

// Cursor defines model for Cursor.
type Cursor = string

// Limit defines model for Limit.
type Limit = int32

// MemoryId defines model for MemoryId.
type MemoryId = openapi_types.UUID

// RunId defines model for RunId.
type RunId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// BrowseMemoriesParams defines parameters for BrowseMemories.
type BrowseMemoriesParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListProcessingLogsParams defines parameters for ListProcessingLogs.
type ListProcessingLogsParams struct {
	AttemptId *openapi_types.UUID `form:"attempt_id,omitempty" json:"attempt_id,omitempty"`
	Limit     *int32              `form:"limit,omitempty" json:"limit,omitempty"`
}

// ImportMemoryMultipartRequestBody defines body for ImportMemory for multipart/form-data ContentType.
type ImportMemoryMultipartRequestBody = ImportMultipart

// EnhanceMemoryWithCodexJSONRequestBody defines body for EnhanceMemoryWithCodex for application/json ContentType.
type EnhanceMemoryWithCodexJSONRequestBody = CodexEnhancementRequest

// SearchMemoriesJSONRequestBody defines body for SearchMemories for application/json ContentType.
type SearchMemoriesJSONRequestBody = SearchRequest

// AsUnderstandingProgressEvent returns the union data inside the ImportEvent as a UnderstandingProgressEvent
func (t ImportEvent) AsUnderstandingProgressEvent() (UnderstandingProgressEvent, error) {
	var body UnderstandingProgressEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUnderstandingProgressEvent overwrites any union data inside the ImportEvent as the provided UnderstandingProgressEvent
func (t *ImportEvent) FromUnderstandingProgressEvent(v UnderstandingProgressEvent) error {
	v.Event = "UnderstandingProgressEvent"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUnderstandingProgressEvent performs a merge with any union data inside the ImportEvent, using the provided UnderstandingProgressEvent
func (t *ImportEvent) MergeUnderstandingProgressEvent(v UnderstandingProgressEvent) error {
	v.Event = "UnderstandingProgressEvent"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsImportCompletedEvent returns the union data inside the ImportEvent as a ImportCompletedEvent
func (t ImportEvent) AsImportCompletedEvent() (ImportCompletedEvent, error) {
	var body ImportCompletedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromImportCompletedEvent overwrites any union data inside the ImportEvent as the provided ImportCompletedEvent
func (t *ImportEvent) FromImportCompletedEvent(v ImportCompletedEvent) error {
	v.Event = "ImportCompletedEvent"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeImportCompletedEvent performs a merge with any union data inside the ImportEvent, using the provided ImportCompletedEvent
func (t *ImportEvent) MergeImportCompletedEvent(v ImportCompletedEvent) error {
	v.Event = "ImportCompletedEvent"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUnderstandingFailedEvent returns the union data inside the ImportEvent as a UnderstandingFailedEvent
func (t ImportEvent) AsUnderstandingFailedEvent() (UnderstandingFailedEvent, error) {
	var body UnderstandingFailedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUnderstandingFailedEvent overwrites any union data inside the ImportEvent as the provided UnderstandingFailedEvent
func (t *ImportEvent) FromUnderstandingFailedEvent(v UnderstandingFailedEvent) error {
	v.Event = "UnderstandingFailedEvent"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUnderstandingFailedEvent performs a merge with any union data inside the ImportEvent, using the provided UnderstandingFailedEvent
func (t *ImportEvent) MergeUnderstandingFailedEvent(v UnderstandingFailedEvent) error {
	v.Event = "UnderstandingFailedEvent"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ImportEvent) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"event"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t ImportEvent) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "ImportCompletedEvent":
		return t.AsImportCompletedEvent()
	case "UnderstandingFailedEvent":
		return t.AsUnderstandingFailedEvent()
	case "UnderstandingProgressEvent":
		return t.AsUnderstandingProgressEvent()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t ImportEvent) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ImportEvent) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsUnderstandingProgressEvent returns the union data inside the UnderstandingEvent as a UnderstandingProgressEvent
func (t UnderstandingEvent) AsUnderstandingProgressEvent() (UnderstandingProgressEvent, error) {
	var body UnderstandingProgressEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUnderstandingProgressEvent overwrites any union data inside the UnderstandingEvent as the provided UnderstandingProgressEvent
func (t *UnderstandingEvent) FromUnderstandingProgressEvent(v UnderstandingProgressEvent) error {
	v.Event = "UnderstandingProgressEvent"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUnderstandingProgressEvent performs a merge with any union data inside the UnderstandingEvent, using the provided UnderstandingProgressEvent
func (t *UnderstandingEvent) MergeUnderstandingProgressEvent(v UnderstandingProgressEvent) error {
	v.Event = "UnderstandingProgressEvent"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUnderstandingCompletedEvent returns the union data inside the UnderstandingEvent as a UnderstandingCompletedEvent
func (t UnderstandingEvent) AsUnderstandingCompletedEvent() (UnderstandingCompletedEvent, error) {
	var body UnderstandingCompletedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUnderstandingCompletedEvent overwrites any union data inside the UnderstandingEvent as the provided UnderstandingCompletedEvent
func (t *UnderstandingEvent) FromUnderstandingCompletedEvent(v UnderstandingCompletedEvent) error {
	v.Event = "UnderstandingCompletedEvent"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUnderstandingCompletedEvent performs a merge with any union data inside the UnderstandingEvent, using the provided UnderstandingCompletedEvent
func (t *UnderstandingEvent) MergeUnderstandingCompletedEvent(v UnderstandingCompletedEvent) error {
	v.Event = "UnderstandingCompletedEvent"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUnderstandingFailedEvent returns the union data inside the UnderstandingEvent as a UnderstandingFailedEvent
func (t UnderstandingEvent) AsUnderstandingFailedEvent() (UnderstandingFailedEvent, error) {
	var body UnderstandingFailedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUnderstandingFailedEvent overwrites any union data inside the UnderstandingEvent as the provided UnderstandingFailedEvent
func (t *UnderstandingEvent) FromUnderstandingFailedEvent(v UnderstandingFailedEvent) error {
	v.Event = "UnderstandingFailedEvent"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUnderstandingFailedEvent performs a merge with any union data inside the UnderstandingEvent, using the provided UnderstandingFailedEvent
func (t *UnderstandingEvent) MergeUnderstandingFailedEvent(v UnderstandingFailedEvent) error {
	v.Event = "UnderstandingFailedEvent"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t UnderstandingEvent) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"event"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t UnderstandingEvent) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "UnderstandingCompletedEvent":
		return t.AsUnderstandingCompletedEvent()
	case "UnderstandingFailedEvent":
		return t.AsUnderstandingFailedEvent()
	case "UnderstandingProgressEvent":
		return t.AsUnderstandingProgressEvent()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t UnderstandingEvent) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *UnderstandingEvent) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Check whether the process is alive
	// (GET /livez)
	GetLiveness(ctx echo.Context) error
	// Browse Memories
	// (GET /memories)
	BrowseMemories(ctx echo.Context, params BrowseMemoriesParams) error
	// Import one Blob and understand it
	// (POST /memories/import)
	ImportMemory(ctx echo.Context) error
	// Get Memory details
	// (GET /memories/{memoryId})
	GetMemory(ctx echo.Context, memoryId MemoryId) error
	// Explicitly request Codex-assisted enhancement
	// (POST /memories/{memoryId}/codex-enhancement)
	EnhanceMemoryWithCodex(ctx echo.Context, memoryId MemoryId) error
	// Download a Memory's immutable Blob
	// (GET /memories/{memoryId}/content)
	GetMemoryContent(ctx echo.Context, memoryId MemoryId) error
	// List processing logs for a Memory
	// (GET /memories/{memoryId}/logs)
	ListProcessingLogs(ctx echo.Context, memoryId MemoryId, params ListProcessingLogsParams) error
	// Rebuild a Memory's understanding
	// (POST /memories/{memoryId}/rebuild)
	RebuildMemory(ctx echo.Context, memoryId MemoryId) error
	// List successful Understanding Runs
	// (GET /memories/{memoryId}/runs)
	ListUnderstandingRuns(ctx echo.Context, memoryId MemoryId) error
	// Get one Understanding Run
	// (GET /memories/{memoryId}/runs/{runId})
	GetUnderstandingRun(ctx echo.Context, memoryId MemoryId, runId RunId) error
	// List logs associated with an Understanding Run
	// (GET /memories/{memoryId}/runs/{runId}/logs)
	ListRunLogs(ctx echo.Context, memoryId MemoryId, runId RunId) error
	// Check whether the server can accept requests
	// (GET /readyz)
	GetReadiness(ctx echo.Context) error
	// Search Memories with a natural-language query
	// (POST /search)
	SearchMemories(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetLiveness converts echo context to params.
func (w *ServerInterfaceWrapper) GetLiveness(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetLiveness(ctx)
	return err
}

// BrowseMemories converts echo context to params.
func (w *ServerInterfaceWrapper) BrowseMemories(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params BrowseMemoriesParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", ctx.QueryParams(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cursor: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.BrowseMemories(ctx, params)
	return err
}

// ImportMemory converts echo context to params.
func (w *ServerInterfaceWrapper) ImportMemory(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ImportMemory(ctx)
	return err
}

// GetMemory converts echo context to params.
func (w *ServerInterfaceWrapper) GetMemory(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memoryId" -------------
	var memoryId MemoryId

	err = runtime.BindStyledParameterWithOptions("simple", "memoryId", ctx.Param("memoryId"), &memoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memoryId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMemory(ctx, memoryId)
	return err
}

// EnhanceMemoryWithCodex converts echo context to params.
func (w *ServerInterfaceWrapper) EnhanceMemoryWithCodex(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memoryId" -------------
	var memoryId MemoryId

	err = runtime.BindStyledParameterWithOptions("simple", "memoryId", ctx.Param("memoryId"), &memoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memoryId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.EnhanceMemoryWithCodex(ctx, memoryId)
	return err
}

// GetMemoryContent converts echo context to params.
func (w *ServerInterfaceWrapper) GetMemoryContent(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memoryId" -------------
	var memoryId MemoryId

	err = runtime.BindStyledParameterWithOptions("simple", "memoryId", ctx.Param("memoryId"), &memoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memoryId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMemoryContent(ctx, memoryId)
	return err
}

// ListProcessingLogs converts echo context to params.
func (w *ServerInterfaceWrapper) ListProcessingLogs(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memoryId" -------------
	var memoryId MemoryId

	err = runtime.BindStyledParameterWithOptions("simple", "memoryId", ctx.Param("memoryId"), &memoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memoryId: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListProcessingLogsParams
	// ------------- Optional query parameter "attempt_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "attempt_id", ctx.QueryParams(), &params.AttemptId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter attempt_id: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListProcessingLogs(ctx, memoryId, params)
	return err
}

// RebuildMemory converts echo context to params.
func (w *ServerInterfaceWrapper) RebuildMemory(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memoryId" -------------
	var memoryId MemoryId

	err = runtime.BindStyledParameterWithOptions("simple", "memoryId", ctx.Param("memoryId"), &memoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memoryId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RebuildMemory(ctx, memoryId)
	return err
}

// ListUnderstandingRuns converts echo context to params.
func (w *ServerInterfaceWrapper) ListUnderstandingRuns(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memoryId" -------------
	var memoryId MemoryId

	err = runtime.BindStyledParameterWithOptions("simple", "memoryId", ctx.Param("memoryId"), &memoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memoryId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListUnderstandingRuns(ctx, memoryId)
	return err
}

// GetUnderstandingRun converts echo context to params.
func (w *ServerInterfaceWrapper) GetUnderstandingRun(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memoryId" -------------
	var memoryId MemoryId

	err = runtime.BindStyledParameterWithOptions("simple", "memoryId", ctx.Param("memoryId"), &memoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memoryId: %s", err))
	}

	// ------------- Path parameter "runId" -------------
	var runId RunId

	err = runtime.BindStyledParameterWithOptions("simple", "runId", ctx.Param("runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter runId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUnderstandingRun(ctx, memoryId, runId)
	return err
}

// ListRunLogs converts echo context to params.
func (w *ServerInterfaceWrapper) ListRunLogs(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memoryId" -------------
	var memoryId MemoryId

	err = runtime.BindStyledParameterWithOptions("simple", "memoryId", ctx.Param("memoryId"), &memoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memoryId: %s", err))
	}

	// ------------- Path parameter "runId" -------------
	var runId RunId

	err = runtime.BindStyledParameterWithOptions("simple", "runId", ctx.Param("runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter runId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListRunLogs(ctx, memoryId, runId)
	return err
}

// GetReadiness converts echo context to params.
func (w *ServerInterfaceWrapper) GetReadiness(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetReadiness(ctx)
	return err
}

// SearchMemories converts echo context to params.
func (w *ServerInterfaceWrapper) SearchMemories(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SearchMemories(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/livez", wrapper.GetLiveness, options.OperationMiddlewares["getLiveness"]...)
	router.GET(options.BaseURL+"/memories", wrapper.BrowseMemories, options.OperationMiddlewares["browseMemories"]...)
	router.POST(options.BaseURL+"/memories/import", wrapper.ImportMemory, options.OperationMiddlewares["importMemory"]...)
	router.GET(options.BaseURL+"/memories/:memoryId", wrapper.GetMemory, options.OperationMiddlewares["getMemory"]...)
	router.POST(options.BaseURL+"/memories/:memoryId/codex-enhancement", wrapper.EnhanceMemoryWithCodex, options.OperationMiddlewares["enhanceMemoryWithCodex"]...)
	router.GET(options.BaseURL+"/memories/:memoryId/content", wrapper.GetMemoryContent, options.OperationMiddlewares["getMemoryContent"]...)
	router.GET(options.BaseURL+"/memories/:memoryId/logs", wrapper.ListProcessingLogs, options.OperationMiddlewares["listProcessingLogs"]...)
	router.POST(options.BaseURL+"/memories/:memoryId/rebuild", wrapper.RebuildMemory, options.OperationMiddlewares["rebuildMemory"]...)
	router.GET(options.BaseURL+"/memories/:memoryId/runs", wrapper.ListUnderstandingRuns, options.OperationMiddlewares["listUnderstandingRuns"]...)
	router.GET(options.BaseURL+"/memories/:memoryId/runs/:runId", wrapper.GetUnderstandingRun, options.OperationMiddlewares["getUnderstandingRun"]...)
	router.GET(options.BaseURL+"/memories/:memoryId/runs/:runId/logs", wrapper.ListRunLogs, options.OperationMiddlewares["listRunLogs"]...)
	router.GET(options.BaseURL+"/readyz", wrapper.GetReadiness, options.OperationMiddlewares["getReadiness"]...)
	router.POST(options.BaseURL+"/search", wrapper.SearchMemories, options.OperationMiddlewares["searchMemories"]...)

}

type BadRequestJSONResponse Error

type NotFoundJSONResponse Error

type UnderstandingEventStreamTexteventStreamResponse struct {
	Body io.Reader

	ContentLength int64
}

type GetLivenessRequestObject struct {
}

type GetLivenessResponseObject interface {
	VisitGetLivenessResponse(w http.ResponseWriter) error
}

type GetLiveness200JSONResponse HealthResponse

func (response GetLiveness200JSONResponse) VisitGetLivenessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type BrowseMemoriesRequestObject struct {
	Params BrowseMemoriesParams
}

type BrowseMemoriesResponseObject interface {
	VisitBrowseMemoriesResponse(w http.ResponseWriter) error
}

type BrowseMemories200JSONResponse MemoryPage

func (response BrowseMemories200JSONResponse) VisitBrowseMemoriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type BrowseMemories400JSONResponse struct{ BadRequestJSONResponse }

func (response BrowseMemories400JSONResponse) VisitBrowseMemoriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ImportMemoryRequestObject struct {
	Body *multipart.Reader
}

type ImportMemoryResponseObject interface {
	VisitImportMemoryResponse(w http.ResponseWriter) error
}

type ImportMemory200TexteventStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response ImportMemory200TexteventStreamResponse) VisitImportMemoryResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	flusher, ok := w.(http.Flusher)
	if !ok {
		// If w doesn't support flushing, fall back to io.Copy.
		_, err := io.Copy(w, response.Body)
		return err
	}
	// text/event-stream messages are typically small; use a
	// modest buffer and flush after each chunk so clients see
	// events immediately instead of waiting on OS buffering.
	buf := make([]byte, 4096)
	for {
		n, err := response.Body.Read(buf)
		if n > 0 {
			if _, writeErr := w.Write(buf[:n]); writeErr != nil {
				return writeErr
			}
			flusher.Flush()
		}
		if err != nil {
			if err == io.EOF {
				return nil
			}
			return err
		}
	}
}

type ImportMemory400JSONResponse struct{ BadRequestJSONResponse }

func (response ImportMemory400JSONResponse) VisitImportMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ImportMemory409JSONResponse Error

func (response ImportMemory409JSONResponse) VisitImportMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ImportMemory413JSONResponse Error

func (response ImportMemory413JSONResponse) VisitImportMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type ImportMemory415JSONResponse Error

func (response ImportMemory415JSONResponse) VisitImportMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type GetMemoryRequestObject struct {
	MemoryId MemoryId `json:"memoryId"`
}

type GetMemoryResponseObject interface {
	VisitGetMemoryResponse(w http.ResponseWriter) error
}

type GetMemory200JSONResponse MemoryDetail

func (response GetMemory200JSONResponse) VisitGetMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMemory404JSONResponse struct{ NotFoundJSONResponse }

func (response GetMemory404JSONResponse) VisitGetMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type EnhanceMemoryWithCodexRequestObject struct {
	MemoryId MemoryId `json:"memoryId"`
	Body     *EnhanceMemoryWithCodexJSONRequestBody
}

type EnhanceMemoryWithCodexResponseObject interface {
	VisitEnhanceMemoryWithCodexResponse(w http.ResponseWriter) error
}

type EnhanceMemoryWithCodex200TexteventStreamResponse struct {
	UnderstandingEventStreamTexteventStreamResponse
}

func (response EnhanceMemoryWithCodex200TexteventStreamResponse) VisitEnhanceMemoryWithCodexResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	flusher, ok := w.(http.Flusher)
	if !ok {
		// If w doesn't support flushing, fall back to io.Copy.
		_, err := io.Copy(w, response.Body)
		return err
	}
	// text/event-stream messages are typically small; use a
	// modest buffer and flush after each chunk so clients see
	// events immediately instead of waiting on OS buffering.
	buf := make([]byte, 4096)
	for {
		n, err := response.Body.Read(buf)
		if n > 0 {
			if _, writeErr := w.Write(buf[:n]); writeErr != nil {
				return writeErr
			}
			flusher.Flush()
		}
		if err != nil {
			if err == io.EOF {
				return nil
			}
			return err
		}
	}
}

type EnhanceMemoryWithCodex404JSONResponse struct{ NotFoundJSONResponse }

func (response EnhanceMemoryWithCodex404JSONResponse) VisitEnhanceMemoryWithCodexResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type EnhanceMemoryWithCodex409JSONResponse Error

func (response EnhanceMemoryWithCodex409JSONResponse) VisitEnhanceMemoryWithCodexResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type EnhanceMemoryWithCodex413JSONResponse Error

func (response EnhanceMemoryWithCodex413JSONResponse) VisitEnhanceMemoryWithCodexResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type GetMemoryContentRequestObject struct {
	MemoryId MemoryId `json:"memoryId"`
}

type GetMemoryContentResponseObject interface {
	VisitGetMemoryContentResponse(w http.ResponseWriter) error
}

type GetMemoryContent200ResponseHeaders struct {
	ContentDisposition *string
	ETag               *string
}

type GetMemoryContent200ApplicationoctetStreamResponse struct {
	Body          io.Reader
	Headers       GetMemoryContent200ResponseHeaders
	ContentLength int64
}

func (response GetMemoryContent200ApplicationoctetStreamResponse) VisitGetMemoryContentResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	if response.Headers.ContentDisposition != nil {
		w.Header().Set("Content-Disposition", fmt.Sprint(*response.Headers.ContentDisposition))
	}
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetMemoryContent200ApplicationpdfResponse struct {
	Body          io.Reader
	Headers       GetMemoryContent200ResponseHeaders
	ContentLength int64
}

func (response GetMemoryContent200ApplicationpdfResponse) VisitGetMemoryContentResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/pdf")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	if response.Headers.ContentDisposition != nil {
		w.Header().Set("Content-Disposition", fmt.Sprint(*response.Headers.ContentDisposition))
	}
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetMemoryContent200ImagejpegResponse struct {
	Body          io.Reader
	Headers       GetMemoryContent200ResponseHeaders
	ContentLength int64
}

func (response GetMemoryContent200ImagejpegResponse) VisitGetMemoryContentResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "image/jpeg")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	if response.Headers.ContentDisposition != nil {
		w.Header().Set("Content-Disposition", fmt.Sprint(*response.Headers.ContentDisposition))
	}
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetMemoryContent200ImagepngResponse struct {
	Body          io.Reader
	Headers       GetMemoryContent200ResponseHeaders
	ContentLength int64
}

func (response GetMemoryContent200ImagepngResponse) VisitGetMemoryContentResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "image/png")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	if response.Headers.ContentDisposition != nil {
		w.Header().Set("Content-Disposition", fmt.Sprint(*response.Headers.ContentDisposition))
	}
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetMemoryContent404JSONResponse struct{ NotFoundJSONResponse }

func (response GetMemoryContent404JSONResponse) VisitGetMemoryContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListProcessingLogsRequestObject struct {
	MemoryId MemoryId `json:"memoryId"`
	Params   ListProcessingLogsParams
}

type ListProcessingLogsResponseObject interface {
	VisitListProcessingLogsResponse(w http.ResponseWriter) error
}

type ListProcessingLogs200JSONResponse ProcessingLogPage

func (response ListProcessingLogs200JSONResponse) VisitListProcessingLogsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListProcessingLogs404JSONResponse struct{ NotFoundJSONResponse }

func (response ListProcessingLogs404JSONResponse) VisitListProcessingLogsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RebuildMemoryRequestObject struct {
	MemoryId MemoryId `json:"memoryId"`
}

type RebuildMemoryResponseObject interface {
	VisitRebuildMemoryResponse(w http.ResponseWriter) error
}

type RebuildMemory200TexteventStreamResponse struct {
	UnderstandingEventStreamTexteventStreamResponse
}

func (response RebuildMemory200TexteventStreamResponse) VisitRebuildMemoryResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	flusher, ok := w.(http.Flusher)
	if !ok {
		// If w doesn't support flushing, fall back to io.Copy.
		_, err := io.Copy(w, response.Body)
		return err
	}
	// text/event-stream messages are typically small; use a
	// modest buffer and flush after each chunk so clients see
	// events immediately instead of waiting on OS buffering.
	buf := make([]byte, 4096)
	for {
		n, err := response.Body.Read(buf)
		if n > 0 {
			if _, writeErr := w.Write(buf[:n]); writeErr != nil {
				return writeErr
			}
			flusher.Flush()
		}
		if err != nil {
			if err == io.EOF {
				return nil
			}
			return err
		}
	}
}

type RebuildMemory404JSONResponse struct{ NotFoundJSONResponse }

func (response RebuildMemory404JSONResponse) VisitRebuildMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RebuildMemory409JSONResponse Error

func (response RebuildMemory409JSONResponse) VisitRebuildMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ListUnderstandingRunsRequestObject struct {
	MemoryId MemoryId `json:"memoryId"`
}

type ListUnderstandingRunsResponseObject interface {
	VisitListUnderstandingRunsResponse(w http.ResponseWriter) error
}

type ListUnderstandingRuns200JSONResponse RunPage

func (response ListUnderstandingRuns200JSONResponse) VisitListUnderstandingRunsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListUnderstandingRuns404JSONResponse struct{ NotFoundJSONResponse }

func (response ListUnderstandingRuns404JSONResponse) VisitListUnderstandingRunsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetUnderstandingRunRequestObject struct {
	MemoryId MemoryId `json:"memoryId"`
	RunId    RunId    `json:"runId"`
}

type GetUnderstandingRunResponseObject interface {
	VisitGetUnderstandingRunResponse(w http.ResponseWriter) error
}

type GetUnderstandingRun200JSONResponse UnderstandingRun

func (response GetUnderstandingRun200JSONResponse) VisitGetUnderstandingRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetUnderstandingRun404JSONResponse struct{ NotFoundJSONResponse }

func (response GetUnderstandingRun404JSONResponse) VisitGetUnderstandingRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListRunLogsRequestObject struct {
	MemoryId MemoryId `json:"memoryId"`
	RunId    RunId    `json:"runId"`
}

type ListRunLogsResponseObject interface {
	VisitListRunLogsResponse(w http.ResponseWriter) error
}

type ListRunLogs200JSONResponse ProcessingLogPage

func (response ListRunLogs200JSONResponse) VisitListRunLogsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListRunLogs404JSONResponse struct{ NotFoundJSONResponse }

func (response ListRunLogs404JSONResponse) VisitListRunLogsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadinessRequestObject struct {
}

type GetReadinessResponseObject interface {
	VisitGetReadinessResponse(w http.ResponseWriter) error
}

type GetReadiness200JSONResponse HealthResponse

func (response GetReadiness200JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SearchMemoriesRequestObject struct {
	Body *SearchMemoriesJSONRequestBody
}

type SearchMemoriesResponseObject interface {
	VisitSearchMemoriesResponse(w http.ResponseWriter) error
}

type SearchMemories200JSONResponse SearchResponse

func (response SearchMemories200JSONResponse) VisitSearchMemoriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SearchMemories400JSONResponse struct{ BadRequestJSONResponse }

func (response SearchMemories400JSONResponse) VisitSearchMemoriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SearchMemories422JSONResponse Error

func (response SearchMemories422JSONResponse) VisitSearchMemoriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Check whether the process is alive
	// (GET /livez)
	GetLiveness(ctx context.Context, request GetLivenessRequestObject) (GetLivenessResponseObject, error)
	// Browse Memories
	// (GET /memories)
	BrowseMemories(ctx context.Context, request BrowseMemoriesRequestObject) (BrowseMemoriesResponseObject, error)
	// Import one Blob and understand it
	// (POST /memories/import)
	ImportMemory(ctx context.Context, request ImportMemoryRequestObject) (ImportMemoryResponseObject, error)
	// Get Memory details
	// (GET /memories/{memoryId})
	GetMemory(ctx context.Context, request GetMemoryRequestObject) (GetMemoryResponseObject, error)
	// Explicitly request Codex-assisted enhancement
	// (POST /memories/{memoryId}/codex-enhancement)
	EnhanceMemoryWithCodex(ctx context.Context, request EnhanceMemoryWithCodexRequestObject) (EnhanceMemoryWithCodexResponseObject, error)
	// Download a Memory's immutable Blob
	// (GET /memories/{memoryId}/content)
	GetMemoryContent(ctx context.Context, request GetMemoryContentRequestObject) (GetMemoryContentResponseObject, error)
	// List processing logs for a Memory
	// (GET /memories/{memoryId}/logs)
	ListProcessingLogs(ctx context.Context, request ListProcessingLogsRequestObject) (ListProcessingLogsResponseObject, error)
	// Rebuild a Memory's understanding
	// (POST /memories/{memoryId}/rebuild)
	RebuildMemory(ctx context.Context, request RebuildMemoryRequestObject) (RebuildMemoryResponseObject, error)
	// List successful Understanding Runs
	// (GET /memories/{memoryId}/runs)
	ListUnderstandingRuns(ctx context.Context, request ListUnderstandingRunsRequestObject) (ListUnderstandingRunsResponseObject, error)
	// Get one Understanding Run
	// (GET /memories/{memoryId}/runs/{runId})
	GetUnderstandingRun(ctx context.Context, request GetUnderstandingRunRequestObject) (GetUnderstandingRunResponseObject, error)
	// List logs associated with an Understanding Run
	// (GET /memories/{memoryId}/runs/{runId}/logs)
	ListRunLogs(ctx context.Context, request ListRunLogsRequestObject) (ListRunLogsResponseObject, error)
	// Check whether the server can accept requests
	// (GET /readyz)
	GetReadiness(ctx context.Context, request GetReadinessRequestObject) (GetReadinessResponseObject, error)
	// Search Memories with a natural-language query
	// (POST /search)
	SearchMemories(ctx context.Context, request SearchMemoriesRequestObject) (SearchMemoriesResponseObject, error)
}

type StrictHandlerFunc func(ctx echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetLiveness operation middleware
func (sh *strictHandler) GetLiveness(ctx echo.Context) error {
	var request GetLivenessRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetLiveness(ctx.Request().Context(), request.(GetLivenessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLiveness")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetLivenessResponseObject); ok {
		return validResponse.VisitGetLivenessResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// BrowseMemories operation middleware
func (sh *strictHandler) BrowseMemories(ctx echo.Context, params BrowseMemoriesParams) error {
	var request BrowseMemoriesRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.BrowseMemories(ctx.Request().Context(), request.(BrowseMemoriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "BrowseMemories")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(BrowseMemoriesResponseObject); ok {
		return validResponse.VisitBrowseMemoriesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ImportMemory operation middleware
func (sh *strictHandler) ImportMemory(ctx echo.Context) error {
	var request ImportMemoryRequestObject

	if reader, err := ctx.Request().MultipartReader(); err != nil {
		return err
	} else {
		request.Body = reader
	}

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ImportMemory(ctx.Request().Context(), request.(ImportMemoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ImportMemory")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ImportMemoryResponseObject); ok {
		return validResponse.VisitImportMemoryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetMemory operation middleware
func (sh *strictHandler) GetMemory(ctx echo.Context, memoryId MemoryId) error {
	var request GetMemoryRequestObject

	request.MemoryId = memoryId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMemory(ctx.Request().Context(), request.(GetMemoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMemory")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetMemoryResponseObject); ok {
		return validResponse.VisitGetMemoryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// EnhanceMemoryWithCodex operation middleware
func (sh *strictHandler) EnhanceMemoryWithCodex(ctx echo.Context, memoryId MemoryId) error {
	var request EnhanceMemoryWithCodexRequestObject

	request.MemoryId = memoryId

	var body EnhanceMemoryWithCodexJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			return err
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.EnhanceMemoryWithCodex(ctx.Request().Context(), request.(EnhanceMemoryWithCodexRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EnhanceMemoryWithCodex")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(EnhanceMemoryWithCodexResponseObject); ok {
		return validResponse.VisitEnhanceMemoryWithCodexResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetMemoryContent operation middleware
func (sh *strictHandler) GetMemoryContent(ctx echo.Context, memoryId MemoryId) error {
	var request GetMemoryContentRequestObject

	request.MemoryId = memoryId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMemoryContent(ctx.Request().Context(), request.(GetMemoryContentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMemoryContent")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetMemoryContentResponseObject); ok {
		return validResponse.VisitGetMemoryContentResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListProcessingLogs operation middleware
func (sh *strictHandler) ListProcessingLogs(ctx echo.Context, memoryId MemoryId, params ListProcessingLogsParams) error {
	var request ListProcessingLogsRequestObject

	request.MemoryId = memoryId
	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListProcessingLogs(ctx.Request().Context(), request.(ListProcessingLogsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProcessingLogs")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListProcessingLogsResponseObject); ok {
		return validResponse.VisitListProcessingLogsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RebuildMemory operation middleware
func (sh *strictHandler) RebuildMemory(ctx echo.Context, memoryId MemoryId) error {
	var request RebuildMemoryRequestObject

	request.MemoryId = memoryId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RebuildMemory(ctx.Request().Context(), request.(RebuildMemoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RebuildMemory")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RebuildMemoryResponseObject); ok {
		return validResponse.VisitRebuildMemoryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListUnderstandingRuns operation middleware
func (sh *strictHandler) ListUnderstandingRuns(ctx echo.Context, memoryId MemoryId) error {
	var request ListUnderstandingRunsRequestObject

	request.MemoryId = memoryId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListUnderstandingRuns(ctx.Request().Context(), request.(ListUnderstandingRunsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListUnderstandingRuns")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListUnderstandingRunsResponseObject); ok {
		return validResponse.VisitListUnderstandingRunsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetUnderstandingRun operation middleware
func (sh *strictHandler) GetUnderstandingRun(ctx echo.Context, memoryId MemoryId, runId RunId) error {
	var request GetUnderstandingRunRequestObject

	request.MemoryId = memoryId
	request.RunId = runId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUnderstandingRun(ctx.Request().Context(), request.(GetUnderstandingRunRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUnderstandingRun")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetUnderstandingRunResponseObject); ok {
		return validResponse.VisitGetUnderstandingRunResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListRunLogs operation middleware
func (sh *strictHandler) ListRunLogs(ctx echo.Context, memoryId MemoryId, runId RunId) error {
	var request ListRunLogsRequestObject

	request.MemoryId = memoryId
	request.RunId = runId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListRunLogs(ctx.Request().Context(), request.(ListRunLogsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRunLogs")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListRunLogsResponseObject); ok {
		return validResponse.VisitListRunLogsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetReadiness operation middleware
func (sh *strictHandler) GetReadiness(ctx echo.Context) error {
	var request GetReadinessRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadiness(ctx.Request().Context(), request.(GetReadinessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadiness")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetReadinessResponseObject); ok {
		return validResponse.VisitGetReadinessResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SearchMemories operation middleware
func (sh *strictHandler) SearchMemories(ctx echo.Context) error {
	var request SearchMemoriesRequestObject

	var body SearchMemoriesJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SearchMemories(ctx.Request().Context(), request.(SearchMemoriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchMemories")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SearchMemoriesResponseObject); ok {
		return validResponse.VisitSearchMemoriesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3DxpbyM3ln+FqB1gvpQs2e04ae2nPtxJDzqJ13bPAtvyClTxSWJSRVaTLNsaQ/99wUeyVKcOXxsMECCy",
	"RPI9vvtiP0SJzHIpQBgdjR+inCqagQGFf30olJbKfuIiGkffC1CrKI4EzSAaR4n7NY50soSM2mVmldtf",
	"tFFcLKL1Oo6+8IybvhNS/LF6AIM5LVITjX8YxdFcqoyaaBxxYd6cRHGU0XueFVk0Ph6N4ijjwv8VB8Bc",
	"GFiAQsi/QibV6jMrgefULDews/BzHCn4XnAFLBobVUAVnRKDouAsKsFU7ndZiF4QqhBPPH9tN+tcCg3I",
	"kPeUXcL3AjSSNJHCgMCPNM9TnlDDpRj+oaWw323A/E3BPBpH/zHcMHvoftXDc6WkcqAY6ETx3B4SjaPr",
	"JRDlgBGuCRe3NOXsKFrH0W/SfJKFYK+KBDDiWEqkIpeFIEyCJkIaAvdcG0Tsq2CgtKGCcbE4vwVhrowC",
	"mjUQNXBvhmB/Hujy96oQVlH4ev1p8BO5AnULanAFwhA8WB+Rc5osCaOGkjmHlFkq/ePq99+OuhlZP/VC",
	"yYUCrQmioclcpqm8A0ZmKyIFEAMq44KmRMGs4CmzlwaxpCKBzOKA245QBD0RUWElg/vzzbKKsORK5qAM",
	"d4KUSDHnKpsqyIGamubNaaqhie4Ht5649VwsCBXEivUtTS06ueJSEQRfRbNCipmUKVBhucSFNqpI7NG6",
	"Te/f8QNNSaFBEcYV4Eoyl4qYJRC4t1LGjYdmqP7zqFM1/Tdy9gckxsL9CIrfAvuwEYQ6Uf7kTqThnmZ5",
	"avfCvVE0McCmVmTaUOIoA0OtCKD8M8Yd7heVc53Ot5DBAztN5sZcfHMo3XTdpXC6Bk4n2pfhbA8DE0dF",
	"VWOm2lADu5S1pmRXuKOJNsLqOrrrKk75O0SUQZ0bzmRPhTTTOZqfjvswMJSn+mB2oA2xeGYlPWma/j6P",
	"xt+2U6PJiPVNW9VBWx2RglDCwnLCs1wqQ6wmpjwxREuSpByNQUIFUZDIW1BWtEWRpnSWgkMehU5ruoDd",
	"4oM03Kzvov4nmvTZBwYigZoUMVlYPKqeuOKHR+XxoshmoKJ1cIVVLnKtC5gyaqCLf3a9zmnS2DTjadq1",
	"XCq+4KJtRM6d4koVkzwtFlzE1oB6kudK3oKwNoqYJTWEag3K+hdrXiw9jrpA3dK0gDak61UODO0+wRWb",
	"02ar2oEtLuLyqYPzEIGwJPwWAMZlLBMHasalDY0jTz77P8Mz+xEdroNS4XOPXGyo7DkUrlfDqiRvn9x8",
	"4qmBDtUNTN/O3TYzc1DUSFUlB3wvaKqjGN035cJ+XCigBtTULKlo/DmVaopbojhKQeuwpvy8WXBzKI8d",
	"ewsNDH0R3NPEIHfJHOnAxaKDz7spX147wO8i9y9AU7O89MFgm+TWvBa6Sjn5Z88Vi9RMMVBt3fOXIqNi",
	"oIAyewGCS0kqXUgXk7slCLRXfFEoYN1aAkpzF/ptF0GPcNddP6OafpBW9w0wDLfaN4bwdbiw0+5pEvZ1",
	"Xn9j3rcZdWfLr4oso2rVQt1BLs/adgUR3Hwd99nKwFTzf9WtKxfm7DTqNKhlYhOHOHa6pBpZmFNjQFn2",
	"/e83Opi/G3waDd7ePJydrv/WxaA5T0GvtIFsmqDisCk1NTSsURl4q1IX5u3HZZLxOX/qeUWaltLZwT3G",
	"aWkye7wBTacWq14jpCClht9CH5gGt9uH9jO8FNVGSCvAeYicrlJJGUmoUty5CCrI1dV5iOfjiHG708b+",
	"phYVrX7D+3jhs5cVsEd4UgvWQtJx7s/YvrVTDdfxAfA+UZ6WG29KKv1apIbnVHUohqVxN/0uPn6KyT8u",
	"zn9GT37x28/kfSpnlmKloM24oFheyOj9FxALy93j0elPP/x4Nho9WRWeKvrbRb1xYS9zxK4hdo0zvjae",
	"cGbOpmAuXMRo0YY0nAHh3bFLXW8aqR2eMpAzbVNcRnAtsWv/E+Hh14pg9k8NaPzSG6FOYC39qsN7r+Sd",
	"BjXwKDN3vbCJGOmhppDYKMolgFKtupO8qqai8HQppzPnHzE1aMscTRBbVYj9o/6amF8WAsP+VoQXTHWh",
	"0jYdLsONv15+IXJeJSth8k6goQDBcsl7CM1cPjutVDa4gUzv8m6NPHiTKlOl6ApFkyZG730ephAdp5QO",
	"ufSC+5gbt/iZXLU/o4VLuGKbiP3yc+FTrkaeHSi0F6ka2LZpJuDeTJOy7rrDXzbTbkSh/wYB7hYVmHbX",
	"DXb67VkqZ2VIUhf0q1/eDU5+OCuF264KAs+zrDAYbAZrfmA485RIas8SiROdA437vpHKc8Rg+4U95apn",
	"idNesG60EaUaGau87rpzN0519nWpxoWSCWjNxeKLXHSohjGQ5Wa6r7Dst6wsNfrcJeVzSFYJ1laMlGkU",
	"R9owWRj3AZSyxJAM0qksTO6/t0VUm4lNFWhbu42jAus8cQRYU+tPgPa9Tn+l6QmlzyeYGSue2tAs318T",
	"jSpEYnWsq8rdLE53yeOGYnFVGqrIeIZur7TVBO05nEntwFd0Jv9lu3gXKRXtC9jiPBXUdJcAnNedunLJ",
	"YfGFLzV1xSo2jLZOfWpANajXFoba5mb8WEWufXAXKS4L8RycbIeTr8bMK6AqWfY3ikqALVqmobX7XE3b",
	"2PeHxw92WZnB7bqb27Ttbn1Fs8OYVJ5m7/pkBsVR7jVoG8yNqlWpsw89/PnxHqzHC7WIk1GTLIFNnycX",
	"CKcdrKPPnAfUb9XEq4tKNd08uCjp27eVqmSMXZn7aaVN+hI1S3Szh9ud7aVOd+hOKj2mDFZtdLvO7l+0",
	"LLZNHp5WHev9tS1moWW6x1BF3FspnyMIy1QvpOUXbQn1Pz01otwqXi6qaoauPTJWZ9re3QFtqHJa2MoW",
	"Or/PPZgXjqVzUIlHeFuzdTTqzGk37dZ8SXVXja9QCoQhtbsRXHz0KCY5ODuZdFmIvmJDhQyV0ZDSEB6U",
	"bD+meguhQzz1LastMwP9Tmpz772F4BCRyXkOKRdQ9yiLIqWqS0s7hdT1v5/plndUCS4WT4myWzlVecka",
	"IxuyEAex2SlzV6EWEQj2WQRbEcXRR4mAPvWZM4stF3PZ0Ry9vr7AGpbClq+fRrLd0TQMpv3ThsFH5F34",
	"m2uc5SpsufuWaz5LYSLMEnVPga+3+zEB3EuowDEyzkAYLNKEn0PxTM4JN9pVyyYCk1BTGY5h5N3F56jS",
	"ho1GR8dHI99dFzTn0Th6czQ6euNKbUtk4DDlt/Av+2kBqEKuJc0lzjZGP4P5wm9BOArWBhJPRqNnGwJs",
	"tLh7pgFzl/RaKlGLtp+BC5XN6MMSkj9tt8QswbGoucMSjVoR/hYtEWR0Y48YIgW9Jng6NCv2plBCk7ul",
	"TMHxmIMmXBAFluBAQlUKrQ6RirkBnjo5XQMkbI/i2tBtT9yyWTJ0E7XreOdCP727vnlBnlUq4x38ekdy",
	"ugArs+G2OKV5Ohr1nVsiOqyMutYZ7MhHKvQL3CwZWOfn0Ll+dERSd/D1a47RqFVVXeSuWug0jFSHYBVk",
	"lAtNrCKRQhieWvGaiLpT9RUiooAmS9CEVkc5NdoHd6i7KEqlmAgb7LpZVNd18709eSf0pgVGrEnzooSm",
	"okDMnTnQE6EtpsJwmqarI/K7G3AqO3hLqkkis4ybMOtkt+E5GxM5EY6lMbERtxQCEuw1lsO2iXU2qT9z",
	"oG3TsUaAo4lAbAhVQLBEYIFJcjwakV/5+yNSDsyVNo1rouAP1+6742ZJrKmdiNPRWzKDuVQQmuQl0Waw",
	"4EI7A1hXLt9hLtMVx7v3kq0aMp+FJvTQeuFBKGSCSKS9RrUZ7Xdde69WUZaczWPCM7qA4R85LMLn3EdR",
	"++lQsym+rntM30vcocKdI81+fs5P9IUUc/xQ0aarIklA63mRbuQ0BHx+GsoFgGPSnK+ZCEu0MXmYeOcz",
	"icYPk4izSTSeRCfsbH7KjunglJ2dDE5h/mbwdnaSDM4o/XF+PB+xs+RkEsWTTbkft42OT96c/nD2409v",
	"6SxhMD/0bzxy0zXAMxscc1BDL2ESje0R8aTdUsDNdvLwKOzq6DDgIhtV4IJKs8FRYXRyNhgdD0bH16PR",
	"GP/7n0m0XmNgFqKSGkO+1kP0TeTS4EZ3mtLiyfRQdmBkj1sWIEDRdOojZS6FJy6mMbjEj1laTK0ATqJ1",
	"Q+7/v0fpcUgvbYzUh9n5R3giu+Xt6zx7SCxrGU4K69rgsFTWHobxYSqsVcb01V3p+M3rvg2B+wSA6Yqn",
	"+bv2jsnZf4/WD6+DFvo0l1hZwiFxSqfug+lf/3nRDBudEUY5Kb3iRsUIN3vEGQ/hTdF6Wyhd8U0vGpT5",
	"cZceMgUvb5MJW7PVMfFjIcTPhcRIA5d12fc2XmFOdytM+TyoTuKfwYTEKEzpd9L00IC4fOi1vulhxxAz",
	"5UE1Ux4/PB5K3BNHfsDs1Spr8JFEwB2+VfLTy2goUXcwhych9fWhoZ1V1xMRntEonizxFQ253kSEWaHd",
	"owH7HMeHRz2vciai71lOR+DkXw25a/43N0vctTWEeryE9r1TWrefvJ3sY6J7330dLrKvZOH9gyoXymMA",
	"7OK9HSytcfFVzT1aRe9tZjaphpwqH7Bz4XMWWbDBzNKRcJEXprT/NTtw7h9wpavSh6A8DKjWHN/5VRV1",
	"YyJqEU+/7R1WaLHdBntDd5gplomB7meD7TnUdl21EYoefsAm2Xjs3lwcvLVTIEK4TELMS2xMrW3ItgTK",
	"whNiR8XBR65zqXkYDGhMiBWLhXvhGUJvrK+FKcijHW+Mz6/pouPRRqVqZtOLmHwvpIVBbcaNOSYBYbhZ",
	"EUMX22Gsn+j6PvqbEOo94N91Y/Tt1VxhKhf9Fa7PIkkLBprYVcgD1/cJVQ3tHkwxzlwtAB0eoS48aHqU",
	"L1yb2ohKR62r61V4bcbmgLfYB78xPxntmlfY9cr8JUtr7XGh7tzHL7Iss/IcSpLlRFkoQz5RhC03SV4D",
	"5yQkiPQWS/0CYuxbli8Sx10ZuugO48qIGOM8bgg1MuOJrbfZ553aFVPaqnDpsN0a+v+7RTjvyo4+Ft4V",
	"ULayghlKFc2wwNOoaiLrcnR4JKAKoXvDACvQzWbli/Y3wqxYB60s6LKlFFIzAXeg7eNCpc3zqK/eFPvq",
	"ZSZ/9dfU30Lo4QP+Cxlbs+Umh16SQR3TMG2pFhXHXaEnFwZUrsAg4GfJlaWANptehEu7e0nunznZj53N",
	"EKOtdpeF8OHAX8l7akK1lgmnZR/CauNzVD5Q+TohUPGXZDEa660N4UugjP81OsK+vYVJtPUxRhKaJJCb",
	"kF7q3T1if4Z9StfY29ct1jg82d9U/BwMgquMYlRqrYQklPhZAILTncSOd7rGf4aNCwOpLVxDUhjQE9F6",
	"Z66xTEQyKhjFrqACzVnhXwsObCEea92d/TE381lpnr5Eeac+U/yoftbTgfcLTYPs2M4f+MqkY6uvx+lH",
	"NwlOTl6nKuPEKpFF6jKyGWw8EbBS3uzbzYq0NfXBkWwz0eBMExHUFIqmg5SKRUEXHlpFIbwO3CByToWc",
	"Waoj+gVnZMKAilsXxRG+ioyGNOfD2xGG4/7c8A9IBIVbx+U3ZW5c+a5uJCs/ePTWN+v/GwA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
