// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ServerUrlLocalMemorydServer defines the Server URL for Local memoryd server
const ServerUrlLocalMemorydServer = "/api/v0"

// Defines values for FactValueType.
const (
	Boolean  FactValueType = "boolean"
	Date     FactValueType = "date"
	Datetime FactValueType = "datetime"
	Integer  FactValueType = "integer"
	Json     FactValueType = "json"
	Null     FactValueType = "null"
	Number   FactValueType = "number"
	String   FactValueType = "string"
)

// Valid indicates whether the value is a known member of the FactValueType enum.
func (e FactValueType) Valid() bool {
	switch e {
	case Boolean:
		return true
	case Date:
		return true
	case Datetime:
		return true
	case Integer:
		return true
	case Json:
		return true
	case Null:
		return true
	case Number:
		return true
	case String:
		return true
	default:
		return false
	}
}

// Defines values for FactFilterOperator.
const (
	Contains           FactFilterOperator = "contains"
	Equals             FactFilterOperator = "equals"
	GreaterThan        FactFilterOperator = "greater_than"
	GreaterThanOrEqual FactFilterOperator = "greater_than_or_equal"
	LessThan           FactFilterOperator = "less_than"
	LessThanOrEqual    FactFilterOperator = "less_than_or_equal"
)

// Valid indicates whether the value is a known member of the FactFilterOperator enum.
func (e FactFilterOperator) Valid() bool {
	switch e {
	case Contains:
		return true
	case Equals:
		return true
	case GreaterThan:
		return true
	case GreaterThanOrEqual:
		return true
	case LessThan:
		return true
	case LessThanOrEqual:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for ImportCompletedEventEvent.
const (
	ImportCompleted ImportCompletedEventEvent = "import_completed"
)

// Valid indicates whether the value is a known member of the ImportCompletedEventEvent enum.
func (e ImportCompletedEventEvent) Valid() bool {
	switch e {
	case ImportCompleted:
		return true
	default:
		return false
	}
}

// Defines values for ProcessingLogKind.
const (
	ProcessingLogKindError            ProcessingLogKind = "error"
	ProcessingLogKindLifecycle        ProcessingLogKind = "lifecycle"
	ProcessingLogKindModelOutput      ProcessingLogKind = "model_output"
	ProcessingLogKindStderr           ProcessingLogKind = "stderr"
	ProcessingLogKindStdout           ProcessingLogKind = "stdout"
	ProcessingLogKindStructuredResult ProcessingLogKind = "structured_result"
	ProcessingLogKindTool             ProcessingLogKind = "tool"
	ProcessingLogKindUsage            ProcessingLogKind = "usage"
)

// Valid indicates whether the value is a known member of the ProcessingLogKind enum.
func (e ProcessingLogKind) Valid() bool {
	switch e {
	case ProcessingLogKindError:
		return true
	case ProcessingLogKindLifecycle:
		return true
	case ProcessingLogKindModelOutput:
		return true
	case ProcessingLogKindStderr:
		return true
	case ProcessingLogKindStdout:
		return true
	case ProcessingLogKindStructuredResult:
		return true
	case ProcessingLogKindTool:
		return true
	case ProcessingLogKindUsage:
		return true
	default:
		return false
	}
}

// Defines values for UnderstandingCompletedEventEvent.
const (
	CodexEnhancementCompleted UnderstandingCompletedEventEvent = "codex_enhancement_completed"
	RebuildCompleted          UnderstandingCompletedEventEvent = "rebuild_completed"
)

// Valid indicates whether the value is a known member of the UnderstandingCompletedEventEvent enum.
func (e UnderstandingCompletedEventEvent) Valid() bool {
	switch e {
	case CodexEnhancementCompleted:
		return true
	case RebuildCompleted:
		return true
	default:
		return false
	}
}

// Defines values for UnderstandingFailedEventEvent.
const (
	CodexEnhancementFailed UnderstandingFailedEventEvent = "codex_enhancement_failed"
	ImportFailed           UnderstandingFailedEventEvent = "import_failed"
	RebuildFailed          UnderstandingFailedEventEvent = "rebuild_failed"
)

// Valid indicates whether the value is a known member of the UnderstandingFailedEventEvent enum.
func (e UnderstandingFailedEventEvent) Valid() bool {
	switch e {
	case CodexEnhancementFailed:
		return true
	case ImportFailed:
		return true
	case RebuildFailed:
		return true
	default:
		return false
	}
}

// Defines values for UnderstandingProgressEventEvent.
const (
	ImportStarted         UnderstandingProgressEventEvent = "import_started"
	UnderstandingProgress UnderstandingProgressEventEvent = "understanding_progress"
	UnderstandingStarted  UnderstandingProgressEventEvent = "understanding_started"
)

// Valid indicates whether the value is a known member of the UnderstandingProgressEventEvent enum.
func (e UnderstandingProgressEventEvent) Valid() bool {
	switch e {
	case ImportStarted:
		return true
	case UnderstandingProgress:
		return true
	case UnderstandingStarted:
		return true
	default:
		return false
	}
}

// Defines values for UnderstandingRunPipeline.
const (
	CodexEnhancement UnderstandingRunPipeline = "codex_enhancement"
	Regular          UnderstandingRunPipeline = "regular"
)

// Valid indicates whether the value is a known member of the UnderstandingRunPipeline enum.
func (e UnderstandingRunPipeline) Valid() bool {
	switch e {
	case CodexEnhancement:
		return true
	case Regular:
		return true
	default:
		return false
	}
}

// Defines values for UnderstandingState.
const (
	Done       UnderstandingState = "Done"
	Failed     UnderstandingState = "Failed"
	InProgress UnderstandingState = "InProgress"
)

// Valid indicates whether the value is a known member of the UnderstandingState enum.
func (e UnderstandingState) Valid() bool {
	switch e {
	case Done:
		return true
	case Failed:
		return true
	case InProgress:
		return true
	default:
		return false
	}
}

// CodexEnhancementRequest defines model for CodexEnhancementRequest.
type CodexEnhancementRequest struct {
	// ConfirmRepeat Confirm repeating an equivalent prior Codex enhancement.
	ConfirmRepeat *bool `json:"confirm_repeat,omitempty"`

	// Instructions Optional user direction for the explicit Codex task.
	Instructions *string `json:"instructions,omitempty"`
}

// DerivedContent defines model for DerivedContent.
type DerivedContent struct {
	Kind     string                  `json:"kind"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Text     *string                 `json:"text,omitempty"`
}

// DuplicateMemory defines model for DuplicateMemory.
type DuplicateMemory struct {
	Id                 openapi_types.UUID `json:"id"`
	UnderstandingState UnderstandingState `json:"understanding_state"`
}

// Error defines model for Error.
type Error struct {
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`

	// ExistingMemory Present on a duplicate import conflict so clients can recover.
	ExistingMemory *DuplicateMemory `json:"existing_memory,omitempty"`
	Message        string           `json:"message"`
}

// Fact defines model for Fact.
type Fact struct {
	Confidence *float64 `json:"confidence,omitempty"`
	Name       string   `json:"name"`
	Namespace  string   `json:"namespace"`

	// Origin Extractor, plugin, or import provenance that asserted the Fact.
	Origin string `json:"origin"`

	// Value Typed JSON value asserted by the Fact.
	Value     interface{}   `json:"value"`
	ValueType FactValueType `json:"value_type"`
}

// FactValueType defines model for Fact.ValueType.
type FactValueType string

// FactFilter defines model for FactFilter.
type FactFilter struct {
	Name      string             `json:"name"`
	Namespace string             `json:"namespace"`
	Operator  FactFilterOperator `json:"operator"`

	// Value Typed value used for exact Fact filtering.
	Value interface{} `json:"value"`
}

// FactFilterOperator defines model for FactFilter.Operator.
type FactFilterOperator string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status HealthResponseStatus `json:"status"`

	// VaultPath Human-readable vault location, when configured.
	VaultPath *string `json:"vault_path,omitempty"`
	Version   *string `json:"version,omitempty"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// ImportCompletedEvent defines model for ImportCompletedEvent.
type ImportCompletedEvent struct {
	Event  ImportCompletedEventEvent `json:"event"`
	Memory MemorySummary             `json:"memory"`
}

// ImportCompletedEventEvent defines model for ImportCompletedEvent.Event.
type ImportCompletedEventEvent string

// ImportContext defines model for ImportContext.
type ImportContext struct {
	ByteSize             *int64     `json:"byte_size,omitempty"`
	ContentHash          *string    `json:"content_hash,omitempty"`
	FilesystemCreatedAt  *time.Time `json:"filesystem_created_at,omitempty"`
	FilesystemModifiedAt *time.Time `json:"filesystem_modified_at,omitempty"`
	FullPath             *string    `json:"full_path,omitempty"`
	MediaType            *string    `json:"media_type,omitempty"`
	OriginalFilename     string     `json:"original_filename"`
	RelativePath         *string    `json:"relative_path,omitempty"`
}

// ImportEvent One JSON payload carried by an SSE event.
type ImportEvent struct {
	union json.RawMessage
}

// ImportMultipart defines model for ImportMultipart.
type ImportMultipart struct {
	// File One Blob. The server detects its Media Type from content first.
	// For inconclusive detection, the part's Content-Type is used if valid.
	File                 openapi_types.File `json:"file"`
	FilesystemCreatedAt  *time.Time         `json:"filesystem_created_at,omitempty"`
	FilesystemModifiedAt *time.Time         `json:"filesystem_modified_at,omitempty"`

	// FullPath Original full path when the importing client can provide it.
	FullPath *string `json:"full_path,omitempty"`

	// RelativePath Browser-provided path relative to the selected directory.
	RelativePath *string `json:"relative_path,omitempty"`
}

// MemoryDetail defines model for MemoryDetail.
type MemoryDetail struct {
	ActiveRun *UnderstandingRun `json:"active_run,omitempty"`

	// ContentUrl Relative URL of the content download endpoint.
	ContentUrl     *string          `json:"content_url,omitempty"`
	DerivedContent []DerivedContent `json:"derived_content"`
	Facts          []Fact           `json:"facts"`
	ImportContext  ImportContext    `json:"import_context"`
	Memory         MemorySummary    `json:"memory"`
}

// MemoryPage defines model for MemoryPage.
type MemoryPage struct {
	Items      []MemorySummary `json:"items"`
	NextCursor *string         `json:"next_cursor,omitempty"`
}

// MemorySummary defines model for MemorySummary.
type MemorySummary struct {
	ActiveRunId *openapi_types.UUID `json:"active_run_id,omitempty"`

	// BlobHash Canonical SHA-256 Blobref of the immutable Blob.
	BlobHash           string             `json:"blob_hash"`
	ByteSize           int64              `json:"byte_size"`
	Id                 openapi_types.UUID `json:"id"`
	ImportedAt         time.Time          `json:"imported_at"`
	MediaType          string             `json:"media_type"`
	OriginalCreatedAt  *time.Time         `json:"original_created_at,omitempty"`
	OriginalFilename   string             `json:"original_filename"`
	OriginalModifiedAt *time.Time         `json:"original_modified_at,omitempty"`
	UnderstandingState UnderstandingState `json:"understanding_state"`
}

// ProcessingLog defines model for ProcessingLog.
type ProcessingLog struct {
	AttemptId openapi_types.UUID      `json:"attempt_id"`
	Id        openapi_types.UUID      `json:"id"`
	Kind      ProcessingLogKind       `json:"kind"`
	MemoryId  openapi_types.UUID      `json:"memory_id"`
	Message   string                  `json:"message"`
	Metadata  *map[string]interface{} `json:"metadata,omitempty"`
	RunId     *openapi_types.UUID     `json:"run_id,omitempty"`
	Timestamp time.Time               `json:"timestamp"`
	Truncated *bool                   `json:"truncated,omitempty"`
}

// ProcessingLogKind defines model for ProcessingLog.Kind.
type ProcessingLogKind string

// ProcessingLogPage defines model for ProcessingLogPage.
type ProcessingLogPage struct {
	Items      []ProcessingLog `json:"items"`
	NextCursor *string         `json:"next_cursor,omitempty"`
}

// QueryPlan defines model for QueryPlan.
type QueryPlan struct {
	Explanation   *string      `json:"explanation,omitempty"`
	FactFilters   []FactFilter `json:"fact_filters"`
	FullTextTerms []string     `json:"full_text_terms"`
}

// RunPage defines model for RunPage.
type RunPage struct {
	Items      []UnderstandingRun `json:"items"`
	NextCursor *string            `json:"next_cursor,omitempty"`
}

// SearchRequest defines model for SearchRequest.
type SearchRequest struct {
	Cursor *string `json:"cursor,omitempty"`
	Limit  *int32  `json:"limit,omitempty"`
	Query  string  `json:"query"`
}

// SearchResponse defines model for SearchResponse.
type SearchResponse struct {
	Items      []SearchResult `json:"items"`
	NextCursor *string        `json:"next_cursor,omitempty"`
	Plan       QueryPlan      `json:"plan"`
	Query      string         `json:"query"`
}

// SearchResult defines model for SearchResult.
type SearchResult struct {
	MatchedFacts []Fact        `json:"matched_facts"`
	MatchedTerms []string      `json:"matched_terms"`
	Memory       MemorySummary `json:"memory"`
}

// UnderstandingCompletedEvent defines model for UnderstandingCompletedEvent.
type UnderstandingCompletedEvent struct {
	Event  UnderstandingCompletedEventEvent `json:"event"`
	Memory MemorySummary                    `json:"memory"`
	Run    UnderstandingRun                 `json:"run"`
}

// UnderstandingCompletedEventEvent defines model for UnderstandingCompletedEvent.Event.
type UnderstandingCompletedEventEvent string

// UnderstandingEvent One JSON payload carried by a rebuild or Codex SSE event.
type UnderstandingEvent struct {
	union json.RawMessage
}

// UnderstandingFailedEvent defines model for UnderstandingFailedEvent.
type UnderstandingFailedEvent struct {
	Error    Error                         `json:"error"`
	Event    UnderstandingFailedEventEvent `json:"event"`
	MemoryId openapi_types.UUID            `json:"memory_id"`
}

// UnderstandingFailedEventEvent defines model for UnderstandingFailedEvent.Event.
type UnderstandingFailedEventEvent string

// UnderstandingProgressEvent defines model for UnderstandingProgressEvent.
type UnderstandingProgressEvent struct {
	Event    UnderstandingProgressEventEvent `json:"event"`
	MemoryId openapi_types.UUID              `json:"memory_id"`
	Message  *string                         `json:"message,omitempty"`
	Percent  *float64                        `json:"percent,omitempty"`

	// Phase Current understanding phase.
	Phase string `json:"phase"`
}

// UnderstandingProgressEventEvent defines model for UnderstandingProgressEvent.Event.
type UnderstandingProgressEventEvent string

// UnderstandingRun defines model for UnderstandingRun.
type UnderstandingRun struct {
	Active            bool                     `json:"active"`
	CompletedAt       time.Time                `json:"completed_at"`
	CreatedAt         time.Time                `json:"created_at"`
	ExtractorVersions *map[string]string       `json:"extractor_versions,omitempty"`
	Id                openapi_types.UUID       `json:"id"`
	MemoryId          openapi_types.UUID       `json:"memory_id"`
	Pipeline          UnderstandingRunPipeline `json:"pipeline"`
	PluginVersions    *map[string]string       `json:"plugin_versions,omitempty"`
	Warnings          *[]string                `json:"warnings,omitempty"`
}

// UnderstandingRunPipeline defines model for UnderstandingRun.Pipeline.
type UnderstandingRunPipeline string

// UnderstandingState defines model for UnderstandingState.
type UnderstandingState string

// Cursor defines model for Cursor.
type Cursor = string

// Limit defines model for Limit.
type Limit = int32

// MemoryId defines model for MemoryId.
type MemoryId = openapi_types.UUID

// RunId defines model for RunId.
type RunId = openapi_types.UUID

// BrowseMemoriesParams defines parameters for BrowseMemories.
type BrowseMemoriesParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListProcessingLogsParams defines parameters for ListProcessingLogs.
type ListProcessingLogsParams struct {
	AttemptId *openapi_types.UUID `form:"attempt_id,omitempty" json:"attempt_id,omitempty"`
	Limit     *int32              `form:"limit,omitempty" json:"limit,omitempty"`
}

// ImportMemoryMultipartRequestBody defines body for ImportMemory for multipart/form-data ContentType.
type ImportMemoryMultipartRequestBody = ImportMultipart

// EnhanceMemoryWithCodexJSONRequestBody defines body for EnhanceMemoryWithCodex for application/json ContentType.
type EnhanceMemoryWithCodexJSONRequestBody = CodexEnhancementRequest

// SearchMemoriesJSONRequestBody defines body for SearchMemories for application/json ContentType.
type SearchMemoriesJSONRequestBody = SearchRequest

// AsUnderstandingProgressEvent returns the union data inside the ImportEvent as a UnderstandingProgressEvent
func (t ImportEvent) AsUnderstandingProgressEvent() (UnderstandingProgressEvent, error) {
	var body UnderstandingProgressEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUnderstandingProgressEvent overwrites any union data inside the ImportEvent as the provided UnderstandingProgressEvent
func (t *ImportEvent) FromUnderstandingProgressEvent(v UnderstandingProgressEvent) error {
	v.Event = "UnderstandingProgressEvent"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUnderstandingProgressEvent performs a merge with any union data inside the ImportEvent, using the provided UnderstandingProgressEvent
func (t *ImportEvent) MergeUnderstandingProgressEvent(v UnderstandingProgressEvent) error {
	v.Event = "UnderstandingProgressEvent"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsImportCompletedEvent returns the union data inside the ImportEvent as a ImportCompletedEvent
func (t ImportEvent) AsImportCompletedEvent() (ImportCompletedEvent, error) {
	var body ImportCompletedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromImportCompletedEvent overwrites any union data inside the ImportEvent as the provided ImportCompletedEvent
func (t *ImportEvent) FromImportCompletedEvent(v ImportCompletedEvent) error {
	v.Event = "ImportCompletedEvent"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeImportCompletedEvent performs a merge with any union data inside the ImportEvent, using the provided ImportCompletedEvent
func (t *ImportEvent) MergeImportCompletedEvent(v ImportCompletedEvent) error {
	v.Event = "ImportCompletedEvent"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUnderstandingFailedEvent returns the union data inside the ImportEvent as a UnderstandingFailedEvent
func (t ImportEvent) AsUnderstandingFailedEvent() (UnderstandingFailedEvent, error) {
	var body UnderstandingFailedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUnderstandingFailedEvent overwrites any union data inside the ImportEvent as the provided UnderstandingFailedEvent
func (t *ImportEvent) FromUnderstandingFailedEvent(v UnderstandingFailedEvent) error {
	v.Event = "UnderstandingFailedEvent"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUnderstandingFailedEvent performs a merge with any union data inside the ImportEvent, using the provided UnderstandingFailedEvent
func (t *ImportEvent) MergeUnderstandingFailedEvent(v UnderstandingFailedEvent) error {
	v.Event = "UnderstandingFailedEvent"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ImportEvent) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"event"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t ImportEvent) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "ImportCompletedEvent":
		return t.AsImportCompletedEvent()
	case "UnderstandingFailedEvent":
		return t.AsUnderstandingFailedEvent()
	case "UnderstandingProgressEvent":
		return t.AsUnderstandingProgressEvent()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t ImportEvent) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ImportEvent) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsUnderstandingProgressEvent returns the union data inside the UnderstandingEvent as a UnderstandingProgressEvent
func (t UnderstandingEvent) AsUnderstandingProgressEvent() (UnderstandingProgressEvent, error) {
	var body UnderstandingProgressEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUnderstandingProgressEvent overwrites any union data inside the UnderstandingEvent as the provided UnderstandingProgressEvent
func (t *UnderstandingEvent) FromUnderstandingProgressEvent(v UnderstandingProgressEvent) error {
	v.Event = "UnderstandingProgressEvent"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUnderstandingProgressEvent performs a merge with any union data inside the UnderstandingEvent, using the provided UnderstandingProgressEvent
func (t *UnderstandingEvent) MergeUnderstandingProgressEvent(v UnderstandingProgressEvent) error {
	v.Event = "UnderstandingProgressEvent"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUnderstandingCompletedEvent returns the union data inside the UnderstandingEvent as a UnderstandingCompletedEvent
func (t UnderstandingEvent) AsUnderstandingCompletedEvent() (UnderstandingCompletedEvent, error) {
	var body UnderstandingCompletedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUnderstandingCompletedEvent overwrites any union data inside the UnderstandingEvent as the provided UnderstandingCompletedEvent
func (t *UnderstandingEvent) FromUnderstandingCompletedEvent(v UnderstandingCompletedEvent) error {
	v.Event = "UnderstandingCompletedEvent"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUnderstandingCompletedEvent performs a merge with any union data inside the UnderstandingEvent, using the provided UnderstandingCompletedEvent
func (t *UnderstandingEvent) MergeUnderstandingCompletedEvent(v UnderstandingCompletedEvent) error {
	v.Event = "UnderstandingCompletedEvent"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUnderstandingFailedEvent returns the union data inside the UnderstandingEvent as a UnderstandingFailedEvent
func (t UnderstandingEvent) AsUnderstandingFailedEvent() (UnderstandingFailedEvent, error) {
	var body UnderstandingFailedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUnderstandingFailedEvent overwrites any union data inside the UnderstandingEvent as the provided UnderstandingFailedEvent
func (t *UnderstandingEvent) FromUnderstandingFailedEvent(v UnderstandingFailedEvent) error {
	v.Event = "UnderstandingFailedEvent"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUnderstandingFailedEvent performs a merge with any union data inside the UnderstandingEvent, using the provided UnderstandingFailedEvent
func (t *UnderstandingEvent) MergeUnderstandingFailedEvent(v UnderstandingFailedEvent) error {
	v.Event = "UnderstandingFailedEvent"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t UnderstandingEvent) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"event"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t UnderstandingEvent) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "UnderstandingCompletedEvent":
		return t.AsUnderstandingCompletedEvent()
	case "UnderstandingFailedEvent":
		return t.AsUnderstandingFailedEvent()
	case "UnderstandingProgressEvent":
		return t.AsUnderstandingProgressEvent()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t UnderstandingEvent) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *UnderstandingEvent) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Check whether the process is alive
	// (GET /livez)
	GetLiveness(ctx echo.Context) error
	// Browse Memories
	// (GET /memories)
	BrowseMemories(ctx echo.Context, params BrowseMemoriesParams) error
	// Import one Blob and understand it
	// (POST /memories/import)
	ImportMemory(ctx echo.Context) error
	// Get Memory details
	// (GET /memories/{memoryId})
	GetMemory(ctx echo.Context, memoryId MemoryId) error
	// Explicitly request Codex-assisted enhancement
	// (POST /memories/{memoryId}/codex-enhancement)
	EnhanceMemoryWithCodex(ctx echo.Context, memoryId MemoryId) error
	// Download a Memory's immutable Blob
	// (GET /memories/{memoryId}/content)
	GetMemoryContent(ctx echo.Context, memoryId MemoryId) error
	// List processing logs for a Memory
	// (GET /memories/{memoryId}/logs)
	ListProcessingLogs(ctx echo.Context, memoryId MemoryId, params ListProcessingLogsParams) error
	// Rebuild a Memory's understanding
	// (POST /memories/{memoryId}/rebuild)
	RebuildMemory(ctx echo.Context, memoryId MemoryId) error
	// List successful Understanding Runs
	// (GET /memories/{memoryId}/runs)
	ListUnderstandingRuns(ctx echo.Context, memoryId MemoryId) error
	// Get one Understanding Run
	// (GET /memories/{memoryId}/runs/{runId})
	GetUnderstandingRun(ctx echo.Context, memoryId MemoryId, runId RunId) error
	// List logs associated with an Understanding Run
	// (GET /memories/{memoryId}/runs/{runId}/logs)
	ListRunLogs(ctx echo.Context, memoryId MemoryId, runId RunId) error
	// Check whether the server can accept requests
	// (GET /readyz)
	GetReadiness(ctx echo.Context) error
	// Search Memories with a natural-language query
	// (POST /search)
	SearchMemories(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetLiveness converts echo context to params.
func (w *ServerInterfaceWrapper) GetLiveness(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetLiveness(ctx)
	return err
}

// BrowseMemories converts echo context to params.
func (w *ServerInterfaceWrapper) BrowseMemories(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params BrowseMemoriesParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", ctx.QueryParams(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cursor: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.BrowseMemories(ctx, params)
	return err
}

// ImportMemory converts echo context to params.
func (w *ServerInterfaceWrapper) ImportMemory(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ImportMemory(ctx)
	return err
}

// GetMemory converts echo context to params.
func (w *ServerInterfaceWrapper) GetMemory(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memoryId" -------------
	var memoryId MemoryId

	err = runtime.BindStyledParameterWithOptions("simple", "memoryId", ctx.Param("memoryId"), &memoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memoryId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMemory(ctx, memoryId)
	return err
}

// EnhanceMemoryWithCodex converts echo context to params.
func (w *ServerInterfaceWrapper) EnhanceMemoryWithCodex(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memoryId" -------------
	var memoryId MemoryId

	err = runtime.BindStyledParameterWithOptions("simple", "memoryId", ctx.Param("memoryId"), &memoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memoryId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.EnhanceMemoryWithCodex(ctx, memoryId)
	return err
}

// GetMemoryContent converts echo context to params.
func (w *ServerInterfaceWrapper) GetMemoryContent(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memoryId" -------------
	var memoryId MemoryId

	err = runtime.BindStyledParameterWithOptions("simple", "memoryId", ctx.Param("memoryId"), &memoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memoryId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMemoryContent(ctx, memoryId)
	return err
}

// ListProcessingLogs converts echo context to params.
func (w *ServerInterfaceWrapper) ListProcessingLogs(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memoryId" -------------
	var memoryId MemoryId

	err = runtime.BindStyledParameterWithOptions("simple", "memoryId", ctx.Param("memoryId"), &memoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memoryId: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListProcessingLogsParams
	// ------------- Optional query parameter "attempt_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "attempt_id", ctx.QueryParams(), &params.AttemptId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter attempt_id: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListProcessingLogs(ctx, memoryId, params)
	return err
}

// RebuildMemory converts echo context to params.
func (w *ServerInterfaceWrapper) RebuildMemory(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memoryId" -------------
	var memoryId MemoryId

	err = runtime.BindStyledParameterWithOptions("simple", "memoryId", ctx.Param("memoryId"), &memoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memoryId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RebuildMemory(ctx, memoryId)
	return err
}

// ListUnderstandingRuns converts echo context to params.
func (w *ServerInterfaceWrapper) ListUnderstandingRuns(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memoryId" -------------
	var memoryId MemoryId

	err = runtime.BindStyledParameterWithOptions("simple", "memoryId", ctx.Param("memoryId"), &memoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memoryId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListUnderstandingRuns(ctx, memoryId)
	return err
}

// GetUnderstandingRun converts echo context to params.
func (w *ServerInterfaceWrapper) GetUnderstandingRun(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memoryId" -------------
	var memoryId MemoryId

	err = runtime.BindStyledParameterWithOptions("simple", "memoryId", ctx.Param("memoryId"), &memoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memoryId: %s", err))
	}

	// ------------- Path parameter "runId" -------------
	var runId RunId

	err = runtime.BindStyledParameterWithOptions("simple", "runId", ctx.Param("runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter runId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUnderstandingRun(ctx, memoryId, runId)
	return err
}

// ListRunLogs converts echo context to params.
func (w *ServerInterfaceWrapper) ListRunLogs(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "memoryId" -------------
	var memoryId MemoryId

	err = runtime.BindStyledParameterWithOptions("simple", "memoryId", ctx.Param("memoryId"), &memoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memoryId: %s", err))
	}

	// ------------- Path parameter "runId" -------------
	var runId RunId

	err = runtime.BindStyledParameterWithOptions("simple", "runId", ctx.Param("runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter runId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListRunLogs(ctx, memoryId, runId)
	return err
}

// GetReadiness converts echo context to params.
func (w *ServerInterfaceWrapper) GetReadiness(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetReadiness(ctx)
	return err
}

// SearchMemories converts echo context to params.
func (w *ServerInterfaceWrapper) SearchMemories(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SearchMemories(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/livez", wrapper.GetLiveness, options.OperationMiddlewares["getLiveness"]...)
	router.GET(options.BaseURL+"/memories", wrapper.BrowseMemories, options.OperationMiddlewares["browseMemories"]...)
	router.POST(options.BaseURL+"/memories/import", wrapper.ImportMemory, options.OperationMiddlewares["importMemory"]...)
	router.GET(options.BaseURL+"/memories/:memoryId", wrapper.GetMemory, options.OperationMiddlewares["getMemory"]...)
	router.POST(options.BaseURL+"/memories/:memoryId/codex-enhancement", wrapper.EnhanceMemoryWithCodex, options.OperationMiddlewares["enhanceMemoryWithCodex"]...)
	router.GET(options.BaseURL+"/memories/:memoryId/content", wrapper.GetMemoryContent, options.OperationMiddlewares["getMemoryContent"]...)
	router.GET(options.BaseURL+"/memories/:memoryId/logs", wrapper.ListProcessingLogs, options.OperationMiddlewares["listProcessingLogs"]...)
	router.POST(options.BaseURL+"/memories/:memoryId/rebuild", wrapper.RebuildMemory, options.OperationMiddlewares["rebuildMemory"]...)
	router.GET(options.BaseURL+"/memories/:memoryId/runs", wrapper.ListUnderstandingRuns, options.OperationMiddlewares["listUnderstandingRuns"]...)
	router.GET(options.BaseURL+"/memories/:memoryId/runs/:runId", wrapper.GetUnderstandingRun, options.OperationMiddlewares["getUnderstandingRun"]...)
	router.GET(options.BaseURL+"/memories/:memoryId/runs/:runId/logs", wrapper.ListRunLogs, options.OperationMiddlewares["listRunLogs"]...)
	router.GET(options.BaseURL+"/readyz", wrapper.GetReadiness, options.OperationMiddlewares["getReadiness"]...)
	router.POST(options.BaseURL+"/search", wrapper.SearchMemories, options.OperationMiddlewares["searchMemories"]...)

}

type UnderstandingEventStreamTexteventStreamResponse struct {
	Body io.Reader

	ContentLength int64
}

type GetLivenessRequestObject struct {
}

type GetLivenessResponseObject interface {
	VisitGetLivenessResponse(w http.ResponseWriter) error
}

type GetLiveness200JSONResponse HealthResponse

func (response GetLiveness200JSONResponse) VisitGetLivenessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type BrowseMemoriesRequestObject struct {
	Params BrowseMemoriesParams
}

type BrowseMemoriesResponseObject interface {
	VisitBrowseMemoriesResponse(w http.ResponseWriter) error
}

type BrowseMemories200JSONResponse MemoryPage

func (response BrowseMemories200JSONResponse) VisitBrowseMemoriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type BrowseMemories400JSONResponse Error

func (response BrowseMemories400JSONResponse) VisitBrowseMemoriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ImportMemoryRequestObject struct {
	Body *multipart.Reader
}

type ImportMemoryResponseObject interface {
	VisitImportMemoryResponse(w http.ResponseWriter) error
}

type ImportMemory200TexteventStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response ImportMemory200TexteventStreamResponse) VisitImportMemoryResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	flusher, ok := w.(http.Flusher)
	if !ok {
		// If w doesn't support flushing, fall back to io.Copy.
		_, err := io.Copy(w, response.Body)
		return err
	}
	// text/event-stream messages are typically small; use a
	// modest buffer and flush after each chunk so clients see
	// events immediately instead of waiting on OS buffering.
	buf := make([]byte, 4096)
	for {
		n, err := response.Body.Read(buf)
		if n > 0 {
			if _, writeErr := w.Write(buf[:n]); writeErr != nil {
				return writeErr
			}
			flusher.Flush()
		}
		if err != nil {
			if err == io.EOF {
				return nil
			}
			return err
		}
	}
}

type ImportMemory400JSONResponse Error

func (response ImportMemory400JSONResponse) VisitImportMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ImportMemory409JSONResponse Error

func (response ImportMemory409JSONResponse) VisitImportMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ImportMemory413JSONResponse Error

func (response ImportMemory413JSONResponse) VisitImportMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type ImportMemory500JSONResponse Error

func (response ImportMemory500JSONResponse) VisitImportMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetMemoryRequestObject struct {
	MemoryId MemoryId `json:"memoryId"`
}

type GetMemoryResponseObject interface {
	VisitGetMemoryResponse(w http.ResponseWriter) error
}

type GetMemory200JSONResponse MemoryDetail

func (response GetMemory200JSONResponse) VisitGetMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMemory404JSONResponse Error

func (response GetMemory404JSONResponse) VisitGetMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type EnhanceMemoryWithCodexRequestObject struct {
	MemoryId MemoryId `json:"memoryId"`
	Body     *EnhanceMemoryWithCodexJSONRequestBody
}

type EnhanceMemoryWithCodexResponseObject interface {
	VisitEnhanceMemoryWithCodexResponse(w http.ResponseWriter) error
}

type EnhanceMemoryWithCodex200TexteventStreamResponse struct {
	UnderstandingEventStreamTexteventStreamResponse
}

func (response EnhanceMemoryWithCodex200TexteventStreamResponse) VisitEnhanceMemoryWithCodexResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	flusher, ok := w.(http.Flusher)
	if !ok {
		// If w doesn't support flushing, fall back to io.Copy.
		_, err := io.Copy(w, response.Body)
		return err
	}
	// text/event-stream messages are typically small; use a
	// modest buffer and flush after each chunk so clients see
	// events immediately instead of waiting on OS buffering.
	buf := make([]byte, 4096)
	for {
		n, err := response.Body.Read(buf)
		if n > 0 {
			if _, writeErr := w.Write(buf[:n]); writeErr != nil {
				return writeErr
			}
			flusher.Flush()
		}
		if err != nil {
			if err == io.EOF {
				return nil
			}
			return err
		}
	}
}

type EnhanceMemoryWithCodex404JSONResponse Error

func (response EnhanceMemoryWithCodex404JSONResponse) VisitEnhanceMemoryWithCodexResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type EnhanceMemoryWithCodex409JSONResponse Error

func (response EnhanceMemoryWithCodex409JSONResponse) VisitEnhanceMemoryWithCodexResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type EnhanceMemoryWithCodex413JSONResponse Error

func (response EnhanceMemoryWithCodex413JSONResponse) VisitEnhanceMemoryWithCodexResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type GetMemoryContentRequestObject struct {
	MemoryId MemoryId `json:"memoryId"`
}

type GetMemoryContentResponseObject interface {
	VisitGetMemoryContentResponse(w http.ResponseWriter) error
}

type GetMemoryContent200ResponseHeaders struct {
	ContentDisposition *string
	ETag               *string
}

type GetMemoryContent200AsteriskResponse struct {
	Body          io.Reader
	Headers       GetMemoryContent200ResponseHeaders
	ContentType   string
	ContentLength int64
}

func (response GetMemoryContent200AsteriskResponse) VisitGetMemoryContentResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", response.ContentType)
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	if response.Headers.ContentDisposition != nil {
		w.Header().Set("Content-Disposition", fmt.Sprint(*response.Headers.ContentDisposition))
	}
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetMemoryContent404JSONResponse Error

func (response GetMemoryContent404JSONResponse) VisitGetMemoryContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListProcessingLogsRequestObject struct {
	MemoryId MemoryId `json:"memoryId"`
	Params   ListProcessingLogsParams
}

type ListProcessingLogsResponseObject interface {
	VisitListProcessingLogsResponse(w http.ResponseWriter) error
}

type ListProcessingLogs200JSONResponse ProcessingLogPage

func (response ListProcessingLogs200JSONResponse) VisitListProcessingLogsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListProcessingLogs404JSONResponse Error

func (response ListProcessingLogs404JSONResponse) VisitListProcessingLogsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RebuildMemoryRequestObject struct {
	MemoryId MemoryId `json:"memoryId"`
}

type RebuildMemoryResponseObject interface {
	VisitRebuildMemoryResponse(w http.ResponseWriter) error
}

type RebuildMemory200TexteventStreamResponse struct {
	UnderstandingEventStreamTexteventStreamResponse
}

func (response RebuildMemory200TexteventStreamResponse) VisitRebuildMemoryResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	flusher, ok := w.(http.Flusher)
	if !ok {
		// If w doesn't support flushing, fall back to io.Copy.
		_, err := io.Copy(w, response.Body)
		return err
	}
	// text/event-stream messages are typically small; use a
	// modest buffer and flush after each chunk so clients see
	// events immediately instead of waiting on OS buffering.
	buf := make([]byte, 4096)
	for {
		n, err := response.Body.Read(buf)
		if n > 0 {
			if _, writeErr := w.Write(buf[:n]); writeErr != nil {
				return writeErr
			}
			flusher.Flush()
		}
		if err != nil {
			if err == io.EOF {
				return nil
			}
			return err
		}
	}
}

type RebuildMemory404JSONResponse Error

func (response RebuildMemory404JSONResponse) VisitRebuildMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RebuildMemory409JSONResponse Error

func (response RebuildMemory409JSONResponse) VisitRebuildMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ListUnderstandingRunsRequestObject struct {
	MemoryId MemoryId `json:"memoryId"`
}

type ListUnderstandingRunsResponseObject interface {
	VisitListUnderstandingRunsResponse(w http.ResponseWriter) error
}

type ListUnderstandingRuns200JSONResponse RunPage

func (response ListUnderstandingRuns200JSONResponse) VisitListUnderstandingRunsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListUnderstandingRuns404JSONResponse Error

func (response ListUnderstandingRuns404JSONResponse) VisitListUnderstandingRunsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetUnderstandingRunRequestObject struct {
	MemoryId MemoryId `json:"memoryId"`
	RunId    RunId    `json:"runId"`
}

type GetUnderstandingRunResponseObject interface {
	VisitGetUnderstandingRunResponse(w http.ResponseWriter) error
}

type GetUnderstandingRun200JSONResponse UnderstandingRun

func (response GetUnderstandingRun200JSONResponse) VisitGetUnderstandingRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetUnderstandingRun404JSONResponse Error

func (response GetUnderstandingRun404JSONResponse) VisitGetUnderstandingRunResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListRunLogsRequestObject struct {
	MemoryId MemoryId `json:"memoryId"`
	RunId    RunId    `json:"runId"`
}

type ListRunLogsResponseObject interface {
	VisitListRunLogsResponse(w http.ResponseWriter) error
}

type ListRunLogs200JSONResponse ProcessingLogPage

func (response ListRunLogs200JSONResponse) VisitListRunLogsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListRunLogs404JSONResponse Error

func (response ListRunLogs404JSONResponse) VisitListRunLogsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadinessRequestObject struct {
}

type GetReadinessResponseObject interface {
	VisitGetReadinessResponse(w http.ResponseWriter) error
}

type GetReadiness200JSONResponse HealthResponse

func (response GetReadiness200JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SearchMemoriesRequestObject struct {
	Body *SearchMemoriesJSONRequestBody
}

type SearchMemoriesResponseObject interface {
	VisitSearchMemoriesResponse(w http.ResponseWriter) error
}

type SearchMemories200JSONResponse SearchResponse

func (response SearchMemories200JSONResponse) VisitSearchMemoriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SearchMemories400JSONResponse Error

func (response SearchMemories400JSONResponse) VisitSearchMemoriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SearchMemories422JSONResponse Error

func (response SearchMemories422JSONResponse) VisitSearchMemoriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Check whether the process is alive
	// (GET /livez)
	GetLiveness(ctx context.Context, request GetLivenessRequestObject) (GetLivenessResponseObject, error)
	// Browse Memories
	// (GET /memories)
	BrowseMemories(ctx context.Context, request BrowseMemoriesRequestObject) (BrowseMemoriesResponseObject, error)
	// Import one Blob and understand it
	// (POST /memories/import)
	ImportMemory(ctx context.Context, request ImportMemoryRequestObject) (ImportMemoryResponseObject, error)
	// Get Memory details
	// (GET /memories/{memoryId})
	GetMemory(ctx context.Context, request GetMemoryRequestObject) (GetMemoryResponseObject, error)
	// Explicitly request Codex-assisted enhancement
	// (POST /memories/{memoryId}/codex-enhancement)
	EnhanceMemoryWithCodex(ctx context.Context, request EnhanceMemoryWithCodexRequestObject) (EnhanceMemoryWithCodexResponseObject, error)
	// Download a Memory's immutable Blob
	// (GET /memories/{memoryId}/content)
	GetMemoryContent(ctx context.Context, request GetMemoryContentRequestObject) (GetMemoryContentResponseObject, error)
	// List processing logs for a Memory
	// (GET /memories/{memoryId}/logs)
	ListProcessingLogs(ctx context.Context, request ListProcessingLogsRequestObject) (ListProcessingLogsResponseObject, error)
	// Rebuild a Memory's understanding
	// (POST /memories/{memoryId}/rebuild)
	RebuildMemory(ctx context.Context, request RebuildMemoryRequestObject) (RebuildMemoryResponseObject, error)
	// List successful Understanding Runs
	// (GET /memories/{memoryId}/runs)
	ListUnderstandingRuns(ctx context.Context, request ListUnderstandingRunsRequestObject) (ListUnderstandingRunsResponseObject, error)
	// Get one Understanding Run
	// (GET /memories/{memoryId}/runs/{runId})
	GetUnderstandingRun(ctx context.Context, request GetUnderstandingRunRequestObject) (GetUnderstandingRunResponseObject, error)
	// List logs associated with an Understanding Run
	// (GET /memories/{memoryId}/runs/{runId}/logs)
	ListRunLogs(ctx context.Context, request ListRunLogsRequestObject) (ListRunLogsResponseObject, error)
	// Check whether the server can accept requests
	// (GET /readyz)
	GetReadiness(ctx context.Context, request GetReadinessRequestObject) (GetReadinessResponseObject, error)
	// Search Memories with a natural-language query
	// (POST /search)
	SearchMemories(ctx context.Context, request SearchMemoriesRequestObject) (SearchMemoriesResponseObject, error)
}

type StrictHandlerFunc func(ctx echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetLiveness operation middleware
func (sh *strictHandler) GetLiveness(ctx echo.Context) error {
	var request GetLivenessRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetLiveness(ctx.Request().Context(), request.(GetLivenessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLiveness")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetLivenessResponseObject); ok {
		return validResponse.VisitGetLivenessResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// BrowseMemories operation middleware
func (sh *strictHandler) BrowseMemories(ctx echo.Context, params BrowseMemoriesParams) error {
	var request BrowseMemoriesRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.BrowseMemories(ctx.Request().Context(), request.(BrowseMemoriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "BrowseMemories")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(BrowseMemoriesResponseObject); ok {
		return validResponse.VisitBrowseMemoriesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ImportMemory operation middleware
func (sh *strictHandler) ImportMemory(ctx echo.Context) error {
	var request ImportMemoryRequestObject

	if reader, err := ctx.Request().MultipartReader(); err != nil {
		return err
	} else {
		request.Body = reader
	}

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ImportMemory(ctx.Request().Context(), request.(ImportMemoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ImportMemory")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ImportMemoryResponseObject); ok {
		return validResponse.VisitImportMemoryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetMemory operation middleware
func (sh *strictHandler) GetMemory(ctx echo.Context, memoryId MemoryId) error {
	var request GetMemoryRequestObject

	request.MemoryId = memoryId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMemory(ctx.Request().Context(), request.(GetMemoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMemory")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetMemoryResponseObject); ok {
		return validResponse.VisitGetMemoryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// EnhanceMemoryWithCodex operation middleware
func (sh *strictHandler) EnhanceMemoryWithCodex(ctx echo.Context, memoryId MemoryId) error {
	var request EnhanceMemoryWithCodexRequestObject

	request.MemoryId = memoryId

	var body EnhanceMemoryWithCodexJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			return err
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.EnhanceMemoryWithCodex(ctx.Request().Context(), request.(EnhanceMemoryWithCodexRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EnhanceMemoryWithCodex")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(EnhanceMemoryWithCodexResponseObject); ok {
		return validResponse.VisitEnhanceMemoryWithCodexResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetMemoryContent operation middleware
func (sh *strictHandler) GetMemoryContent(ctx echo.Context, memoryId MemoryId) error {
	var request GetMemoryContentRequestObject

	request.MemoryId = memoryId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMemoryContent(ctx.Request().Context(), request.(GetMemoryContentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMemoryContent")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetMemoryContentResponseObject); ok {
		return validResponse.VisitGetMemoryContentResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListProcessingLogs operation middleware
func (sh *strictHandler) ListProcessingLogs(ctx echo.Context, memoryId MemoryId, params ListProcessingLogsParams) error {
	var request ListProcessingLogsRequestObject

	request.MemoryId = memoryId
	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListProcessingLogs(ctx.Request().Context(), request.(ListProcessingLogsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProcessingLogs")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListProcessingLogsResponseObject); ok {
		return validResponse.VisitListProcessingLogsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RebuildMemory operation middleware
func (sh *strictHandler) RebuildMemory(ctx echo.Context, memoryId MemoryId) error {
	var request RebuildMemoryRequestObject

	request.MemoryId = memoryId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RebuildMemory(ctx.Request().Context(), request.(RebuildMemoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RebuildMemory")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RebuildMemoryResponseObject); ok {
		return validResponse.VisitRebuildMemoryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListUnderstandingRuns operation middleware
func (sh *strictHandler) ListUnderstandingRuns(ctx echo.Context, memoryId MemoryId) error {
	var request ListUnderstandingRunsRequestObject

	request.MemoryId = memoryId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListUnderstandingRuns(ctx.Request().Context(), request.(ListUnderstandingRunsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListUnderstandingRuns")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListUnderstandingRunsResponseObject); ok {
		return validResponse.VisitListUnderstandingRunsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetUnderstandingRun operation middleware
func (sh *strictHandler) GetUnderstandingRun(ctx echo.Context, memoryId MemoryId, runId RunId) error {
	var request GetUnderstandingRunRequestObject

	request.MemoryId = memoryId
	request.RunId = runId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUnderstandingRun(ctx.Request().Context(), request.(GetUnderstandingRunRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUnderstandingRun")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetUnderstandingRunResponseObject); ok {
		return validResponse.VisitGetUnderstandingRunResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListRunLogs operation middleware
func (sh *strictHandler) ListRunLogs(ctx echo.Context, memoryId MemoryId, runId RunId) error {
	var request ListRunLogsRequestObject

	request.MemoryId = memoryId
	request.RunId = runId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListRunLogs(ctx.Request().Context(), request.(ListRunLogsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRunLogs")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListRunLogsResponseObject); ok {
		return validResponse.VisitListRunLogsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetReadiness operation middleware
func (sh *strictHandler) GetReadiness(ctx echo.Context) error {
	var request GetReadinessRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadiness(ctx.Request().Context(), request.(GetReadinessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadiness")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetReadinessResponseObject); ok {
		return validResponse.VisitGetReadinessResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SearchMemories operation middleware
func (sh *strictHandler) SearchMemories(ctx echo.Context) error {
	var request SearchMemoriesRequestObject

	var body SearchMemoriesJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SearchMemories(ctx.Request().Context(), request.(SearchMemoriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchMemories")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SearchMemoriesResponseObject); ok {
		return validResponse.VisitSearchMemoriesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Dxrbxu3ln+FmL1AgYuRLDuO22g/pYlzm0V6k7WTXWAjr0DNHElsOOSE5NhWDf33BQ/J0Tz1iB/rAhco",
	"UFkieQ7P+8XcRYnMcilAGB2N76KcKpqBAYV/vSmUlsp+YiIaR98LUKsojgTNIBpHifs1jnSyhIzaZWaV",
	"21+0UUwsovU6jj6wjJm+Ezj+WD0ghTktuInGL0dxNJcqoyYaR0yYFydRHGX0lmVFFo2PR6M4ypjwf8UB",
	"MBMGFqAQ8u+QSbV6n5bAc2qWG9hZ+DmOFHwvmII0GhtVQBWdEoOiYGlUgqnc76IQvSBUIe55/tpu1rkU",
	"GpAhX0QKShsqUiYW59cgzKVRQDP7WyKFAYG0NnBrjsD+PNDl71Ui60Sx3DBpcf7y+d3gF3IJ6hrU4BKE",
	"IXiwHpJzmixJSg0lcwY8JUyT/7j8+M9hN6L1Uz8puVCgNUE0NJlLzuUNpGS2IlIAMaAyJignCmYF4ymR",
	"ioBYUpFAZnHAbUMksUPcCaRM4fZ8s+wCvheg8c65kjkowxyhEinmTGVTBTlQU5OsOeUamui+ceuJW8/E",
	"glBBLNuuKbfo5IpJRRB8Fc0KKWZScqAiWscRE9qoIrFH6za9P+IHykmhQZGUKcCVZC4VMUsgcJtzljDj",
	"oRmqvw07Rc9/I2d/QGIs3Leg2DWkbzaCUCfKNyZQVOGWZjm3e+HWKJoYSKdWZNpQ4igDQ60I2H00TZnD",
	"/VPlXCfTLWTwwE6TsFGHrw6lq667FJYK1IBT4/ZlWLqHAsVRUdWYqTbUgN33NwXzaBz929HG/B15OTuq",
	"Kdkl7miijbC6ju66yrlSUrUvkMgU6txwJmkqpJnOZSE675OCoYzrg9kBt0xbuZ5mJT0p5x/n0fjrdmo0",
	"GbG+aqs6aKsjUhBK0rCcsCyXyhCriZwlhmhJEs7QGCRUEAWJvAZlRVsUnNMZB4c8Cp3WdAG7xQdpuFnf",
	"Rf13NOmzDymIBGpSlMrC4lH1NBU/MyqPF0U2s24mmPoqF5nWBUxTKw0d/LPrdU6TxqYZ47xruVRswUTb",
	"iJw7xZUqJjkvFkzE1oB6kudKXoOwNoqYJTWEag3KQIrmxdJj2AXqmvIC2pA+r3JI0e4TXLE5bbaqHdji",
	"Ii6fOjh3EQhLwq8BYFz66jhQMy5taBx58tn/GZbZj39oKTyUCp975GJDZc+hcL0aViV5++TmHeMGOlQ3",
	"MH07d1u/2iOokapKDvheUK6jGN03ZcJ+XCigBtTULKlo/DmVaopbojjioHVYU37eLLg6lMeOvYWGFH0R",
	"3NLEIHfJHOnAxKKDz7spX147wO8i929AuVle+GCnTXJrXgtdpZz81nPFgpspBmKte/5WZFQMFNDUXoDg",
	"UsJlQu3vMblZgkB7xRaFgrRbS0BpPGyXafIId931ParpG2l130CK4Vb7xhC+Dhd22j1Nwr7O62/M+zaj",
	"7mz5ZZFlVK1aqDvI5VnbriCCm6/jPlsZmGr2Z926MmHOTqNOg1oG7nGIY6dLqpGFOTUGlGXf/+olPXl5",
	"NvhKB/PR4NXV3dnp+m9dTJozDnqlDWTTBJUnnVJTQ8UaloG3LHWB3n5cJlM2Z/c9r+C8lNAODqaMlmaz",
	"xyNQPrVY9RoiBZwadg19YBocbx/az/RSXBthrQDnJXK64pKmJKFKMecmqCCXl+chpo+jlNmdNv43tcho",
	"9U+8jxdAe1kBe4QotYAtJB7n/oztWztVcR0fAO8dZbzceFVS6feCG5ZT1aEclsbd9PuVy9mQfF4C0ZiO",
	"kRQMJEYTZjT53coFsaaazJXMiNcTMmdKm+FEvLMBgEikSHih2TX4zWjZrJ+2yPykic8OBngQ087es7m1",
	"/iwdTkRUybtnTFDM1zN6+wHEworS8ej0l5c/n41G99a7++rZdr1qUNcLOLFriF3jrL0ljLOrNudz8SmG",
	"pzaGYikQ1h0stfSrDu5XJW80qIE/JXUQwyZiJALWwMEmXz4JlGrVnehVNRWFp0s5nUl/i+lBW+Zogtiq",
	"Quwf+dfE/KIQGPq3orxgrgvF23S4CDf+cvGByDneOshtKm8EGgoQaS6Z6CZ06nLaaaW6wQxkepeHa+TC",
	"m3SZKkVXKC00MXrv8zCN6DildMqlJ9zH3LjFD+Su/RktXMIV20Tsl59PPu1q5NqBQnuRqoFtm2YCbs00",
	"KWuLO/xlM/VGFPpvEOBuUYFpd+1gp9+ecTkrw5JG/YgKKVhCObn87fXg5OUZ2nIF8yD1LMsKY093Rj6K",
	"fySuuU9YtWe9xMnQgYZ335DlIYKx/eKfctWDBGyPWETayFSNjFVed925G6c6+7p05JOSCWjNxOKDXHTo",
	"iDGQ5Wa6r7Dst6ysO/pEhrM5JKsECy1GSh7FkTapLIz7AEpZYsgU+FQWJvff24qqTcumCrQt5MZRgUWf",
	"OAIssPVnQ/tep7/sdI866D3sjRVPbWiW76+JRhUisTrWVfJuVqq75HFDsbgqDVVkPEO3l91qgvYQXqV2",
	"4BN6lf+0LatPnIr2BWylngpquusBzv1OXe3ksEDD1526ghYb4lrvPjWgGtRrC0NtczOQrCLXPriLFBeF",
	"eAhOtuPKJ2PmJVCVLPu7RiXAFi156GM+VIcy9s3Q8Z1dVmZXu+7mNm27W18F7TAmlafZu96bQXGUew3a",
	"BnOjalXq7EMPf368B+vxQi3iZNQkS0inD5MUhNMO1tEHTgjqt2ri1UWlmm4eXKH0vdxKiTLGFs3ttNIz",
	"fYwCJrrZw+3O9rqnO3QnlX6kHlbters27zOtj22Th/uVyXp/bYtZ6J9uA+aarOu4t2w+RxCWqV5Iyy/a",
	"Eup/um9EuVW8XFTVDF17ZKzOtL1bBdpQ5bSwlS10fp97MI8cS+egEo/wts7raNSZ0256r/mS6o5K6ptC",
	"KRCG1O5GcPHwh5jk4Oxk0kUh+qoOFTJU5kRKQ3hQsv0jlVUI7eKp719tGSDod1Kbe+8tBIeITM5y4ExA",
	"3aMsCk5Vl5Z2Cqlrhj/QLW+oEkws7hNlt3Kq8pI1RjZkIQ5is1PmLkMtIhDsvQi2IoqjtxIBveszZxZb",
	"Juayo1P6+fMnrNQq7P/60STbKuXE+V7yXzYMHpLX4W+mcbCrsHXva6bZjMNEmCXqngJsaJQzA7iXUIEz",
	"ZSwFYbBIE34OJWI5x84HVsywM2GYqUzKpOT1p/dRpScbjYbHw5FvtQuas2gcvRiOhi9cuW2JDDzi7Br+",
	"tJ8WgCrk+tNM4iBf9A8wH9g1CEfB2vTdyWjUGLSjuZt2YVIc4YBCbc5um79q9Ls7JuhsGyh3Sa+lErVo",
	"+4G4UOKM3iwh+WY7GWYJjkXNHZZo1Irw12iJIKMre8QRUtBrgqdDs3RvCiU0uVlKDo7HDDRhgiiwBAcS",
	"qlJodYhUqZvmqZPTdULC9iiuTZj2xC2bJUdufHQd71zoR1XXV4/Is0qJvINfr0lOF2BlNtx2aCXx9AER",
	"8EFOt6wol9WiRgnXzWtIi+MFqTAjiEYpDXXhOHJxBHo1qTuE5EuOoa2s9S4DIgoyyoQmVhdJIQzjVkIn",
	"ou6XfZGJKKDJEjSh1dFQjSbGHeqYioItJsLGy2629d+dyXCtO3kj9KadRqxV9NKI1qZAfJ1F0ROhLabC",
	"MMr5akg+uoGpsvm6pJokMsuYCbNTdhues7GyE+GkIiY2aJdCQIKtxFSCJkJiMzEB7s8caNtTrBFgOBGI",
	"DaEKCFYZLDBJjkcj8jv7dUjKAbzSLDJNFPzhWoc3zCyJtdYTcTp6RWYwlwpCw70k2gwWTGhnQ+v66bvV",
	"ZcbjePerTFcNqc1CQ/vIOvJBqIXuJ7jNnvi67id9K3GH4nZONfsROj/UFxLL8V1F7C+LxJrEecE3ohXC",
	"PD8Q5cK+MWmO2EyEveeY3E28y5lE47tJxNJJNJ5EJ+nZ/DQ9poPT9OxkcArzF4NXs5NkcEbpz/Pj+Sg9",
	"S04mUTzZFPlxm+/2jI5PXpy+PPv5l1d0lqQwP/RvPHnTMsCjq6YlT92SspEwicb2iHjS7ifgZjuDOAy7",
	"OtoLuMiGFLig0mlwxBid2DsNRsefR6Mx/vc/k2i9xqgshCQ1vnypx+ebsKXBlO4cpcWa6aFcwbAetyxA",
	"gKJ86sNkJoUnLuYwuMQPXFpMrRxOonVlNv05DNXjuB5vDNeHKfr/bzdk4b96GviJlZMUB5B1bR5ZKmsW",
	"w1QyFdY4YyLs8Dt+8bT0gdsEINUVh/OT9v7JuQFE6+VTsc3TxVU+CBPoqCrO0DsWZ3itFsxgQUUzwnB2",
	"vowHnM8t1Zcws0fMcRde5qy3xegVj/Wo0Z4fqOmhWvD9NkuxxWAdEz94EuasYqSBS+fIRSG8Mpw+qbBB",
	"GpI0qSwSm+gEnwU0ufgPMGF9eG7QybZDg/nyRdb6qofjR5jlD6pZ/vjux6HEPWHrG8y8rXkInp4IuEHK",
	"+DFstPNIQKw/kJC2+5jUDt3riQjvgRRLlvgciHzehKJZod3rB6ayoD49z4smou99UUfE5p8/uWv+NzNL",
	"3LU1dvtx6ep7cLVuv03zutd1WrnuqPcB27PUiidyW/7xGZ7pgnsXGO+QmpqgPKkPQ9vuXegMSK4gp8on",
	"I0z4fEwW6WAmC2v2RV6Y0qnVTM25f+zGV6VjRJEbUK0ZsqhyyYoVqsWE/R7kqEKL7Z7Em+vdDuXvR3+v",
	"U7E9LbszjrM0DDE4CYE0sYG6HrYGdE3pZ37SRBupbFqyGQbGhz9VPsvEQMiQ3JCrkMT4w74JeSOcVVkC",
	"TcM7Xw/yLdO51CwMNNSRviwWC6c1IWvAumAY4xzueAh8/pkuOl6eVKp9NkGKyfdCWhjUpvmY2BIQhpkV",
	"MXSxHcb6+XvWt55YhG5YWp8MfDJPy+Wiv/j33g6Rp6CJXYVs9oGhr9Zo97AsZSne1VWyCXUBTtNhfWDa",
	"1KZ3OsqAXa/Da+NHB7zJPvit+clo1yjHrtfmj1l1bE9SdWeGfpFlmVWZUK0th+1Chfb5a4kVGJLXbuSE",
	"MGjNFkfwCJriG8aPEoleGrroDkTLtAEjVWYINTKzE8aY4xPtilptbbtw2G7Nj/4Vox2M0+tyZAM7Kwpo",
	"urLqFcpRTRn2bKga+rqoHh7LqELo3kDG6kyzG/2oDawwDNhBKwu67BmGFFnADejwWumvYoT0pnRcr1Z6",
	"6j6lFSqEPrrDf1Jka2GkKQSPKQMdE1VtxRGVCKdCT+s8Va7AIOC/SllECmhLwqMIwu6Wp/unZ/aTmGa4",
	"1zYeF4XwodlzimQ0oVrLhNGy12Vtyl+kjoYmpPMSVDxLKUKvtnU04gJoyp7HbIQvTGO9xDpjIwlNEshN",
	"4JbePS3hz0ioaO7tm5vQOEbc3xF/H8yaS9wxCbG2ThJK/FQMwTlnYged3QhMhl08A9x2cSApDOiJaP3z",
	"CxqLjiSjIqXY3FagWVr4N60D25XCxk9nm9dNP1c6/49RLKxP1/9Qj/f+wPuFpkF2HGwZeH12bPXVXf08",
	"OmYnJ08D38loIgvusvkZbJwzpKXwWsQqottULkf/zaCQs3NEUFMoygecikVBFx5aRbu8Ql0hck4fnY2r",
	"I/oBR8/C3JdbF8URvjqOjmjOjq5HmGf5c8M/0hK0dx2X35R1lcp3dYtb+cGjt75a/98A",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
