//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ServerUrlLocalMemorydServer defines the Server URL for Local memoryd server
const ServerUrlLocalMemorydServer = "/api/v0"

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for UnderstandingAttemptStatus.
const (
	UnderstandingAttemptStatusDone    UnderstandingAttemptStatus = "done"
	UnderstandingAttemptStatusFailed  UnderstandingAttemptStatus = "failed"
	UnderstandingAttemptStatusQueued  UnderstandingAttemptStatus = "queued"
	UnderstandingAttemptStatusRunning UnderstandingAttemptStatus = "running"
)

// Valid indicates whether the value is a known member of the UnderstandingAttemptStatus enum.
func (e UnderstandingAttemptStatus) Valid() bool {
	switch e {
	case UnderstandingAttemptStatusDone:
		return true
	case UnderstandingAttemptStatusFailed:
		return true
	case UnderstandingAttemptStatusQueued:
		return true
	case UnderstandingAttemptStatusRunning:
		return true
	default:
		return false
	}
}

// Defines values for UnderstandingDetailsStatus.
const (
	UnderstandingDetailsStatusDone    UnderstandingDetailsStatus = "done"
	UnderstandingDetailsStatusFailed  UnderstandingDetailsStatus = "failed"
	UnderstandingDetailsStatusQueued  UnderstandingDetailsStatus = "queued"
	UnderstandingDetailsStatusRunning UnderstandingDetailsStatus = "running"
)

// Valid indicates whether the value is a known member of the UnderstandingDetailsStatus enum.
func (e UnderstandingDetailsStatus) Valid() bool {
	switch e {
	case UnderstandingDetailsStatusDone:
		return true
	case UnderstandingDetailsStatusFailed:
		return true
	case UnderstandingDetailsStatusQueued:
		return true
	case UnderstandingDetailsStatusRunning:
		return true
	default:
		return false
	}
}

// CostEstimate defines model for CostEstimate.
type CostEstimate struct {
	AmountUsd   float64 `json:"amount_usd"`
	Basis       string  `json:"basis"`
	PricingDate *string `json:"pricing_date,omitempty"`
	PricingUrl  *string `json:"pricing_url,omitempty"`
}

// DerivedContent Independent text artifact belonging to its containing Run.
type DerivedContent struct {
	BlobHash string `json:"blob_hash"`
	ByteSize int64  `json:"byte_size"`

	// Content Literal UTF-8 text content.
	Content     string             `json:"content"`
	ContentType string             `json:"content_type"`
	Id          openapi_types.UUID `json:"id"`

	// Provenance Optional opaque plugin-defined JSON metadata.
	Provenance interface{} `json:"provenance,omitempty"`

	// Scope Optional opaque plugin-defined JSON metadata.
	Scope interface{} `json:"scope,omitempty"`
}

// DuplicateMemory defines model for DuplicateMemory.
type DuplicateMemory struct {
	Id openapi_types.UUID `json:"id"`
}

// Error defines model for Error.
type Error struct {
	// Code Example: memory_not_found
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`

	// ExistingMemory Present on a duplicate import conflict so clients can recover.
	ExistingMemory *DuplicateMemory `json:"existing_memory,omitempty"`
	Message        string           `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status  HealthResponseStatus `json:"status"`
	Version *string              `json:"version,omitempty"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// ImportContext Stored provenance from the first successful import.
type ImportContext struct {
	FilesystemCreatedAt  *time.Time `json:"filesystem_created_at,omitempty"`
	FilesystemModifiedAt *time.Time `json:"filesystem_modified_at,omitempty"`
	FullPath             *string    `json:"full_path,omitempty"`
	OriginalFilename     string     `json:"original_filename"`
	RelativePath         *string    `json:"relative_path,omitempty"`
}

// ImportContextInput Optional client-observed provenance sent as one application/json
// multipart part. The original filename comes from the Blob part. Omitted
// values remain unknown; malformed timestamps reject the import.
type ImportContextInput struct {
	FilesystemCreatedAt  *time.Time `json:"filesystem_created_at,omitempty"`
	FilesystemModifiedAt *time.Time `json:"filesystem_modified_at,omitempty"`
	FullPath             *string    `json:"full_path,omitempty"`
	RelativePath         *string    `json:"relative_path,omitempty"`
}

// ImportMultipart defines model for ImportMultipart.
type ImportMultipart struct {
	// File One Blob of at most 100 MiB with a nonblank filename in
	// Content-Disposition. The server detects its Media Type from content
	// first and may fall back to a valid, specific part Content-Type.
	File openapi_types.File `json:"file"`

	// ImportContext Optional client-observed provenance sent as one application/json
	// multipart part. The original filename comes from the Blob part. Omitted
	// values remain unknown; malformed timestamps reject the import.
	ImportContext *ImportContextInput `json:"import_context,omitempty"`
}

// MemoryDetail defines model for MemoryDetail.
type MemoryDetail struct {
	// ContentUrl Relative URL of the content download endpoint.
	ContentUrl *string `json:"content_url,omitempty"`

	// ImportContext Stored provenance from the first successful import.
	ImportContext ImportContext        `json:"import_context"`
	Memory        MemorySummary        `json:"memory"`
	Understanding UnderstandingDetails `json:"understanding"`
}

// MemoryPage defines model for MemoryPage.
type MemoryPage struct {
	Items      []MemorySummary `json:"items"`
	NextCursor *string         `json:"next_cursor,omitempty"`
}

// MemorySummary defines model for MemorySummary.
type MemorySummary struct {
	// BlobHash Canonical SHA-256 Blobref of the immutable Blob.
	BlobHash           string             `json:"blob_hash"`
	ByteSize           int64              `json:"byte_size"`
	Id                 openapi_types.UUID `json:"id"`
	ImportedAt         time.Time          `json:"imported_at"`
	MediaType          string             `json:"media_type"`
	OriginalCreatedAt  *time.Time         `json:"original_created_at,omitempty"`
	OriginalFilename   string             `json:"original_filename"`
	OriginalModifiedAt *time.Time         `json:"original_modified_at,omitempty"`
}

// Statistics defines model for Statistics.
type Statistics struct {
	Usage *TokenUsage `json:"usage,omitempty"`
}

// TokenUsage defines model for TokenUsage.
type TokenUsage struct {
	CacheWriteInputTokens *int64 `json:"cache_write_input_tokens,omitempty"`
	CachedInputTokens     *int64 `json:"cached_input_tokens,omitempty"`
	InputTokens           *int64 `json:"input_tokens,omitempty"`
	OutputTokens          *int64 `json:"output_tokens,omitempty"`
	ReasoningOutputTokens *int64 `json:"reasoning_output_tokens,omitempty"`
	TotalTokens           *int64 `json:"total_tokens,omitempty"`
}

// UnderstandingAttempt defines model for UnderstandingAttempt.
type UnderstandingAttempt struct {
	CompletedAt *time.Time                `json:"completed_at,omitempty"`
	Diagnostics *UnderstandingDiagnostics `json:"diagnostics,omitempty"`
	Id          openapi_types.UUID        `json:"id"`

	// PluginId Configured plugin ID; empty when no plugin is selected.
	PluginId  string                     `json:"plugin_id"`
	QueuedAt  time.Time                  `json:"queued_at"`
	StartedAt *time.Time                 `json:"started_at,omitempty"`
	Status    UnderstandingAttemptStatus `json:"status"`
}

// UnderstandingAttemptStatus defines model for UnderstandingAttempt.Status.
type UnderstandingAttemptStatus string

// UnderstandingDetails defines model for UnderstandingDetails.
type UnderstandingDetails struct {
	// ActiveRun The last complete successful Run; failed attempts do not replace it.
	ActiveRun     *UnderstandingRun          `json:"active_run"`
	LatestAttempt *UnderstandingAttempt      `json:"latest_attempt"`
	Status        UnderstandingDetailsStatus `json:"status"`
}

// UnderstandingDetailsStatus defines model for UnderstandingDetails.Status.
type UnderstandingDetailsStatus string

// UnderstandingDiagnostics defines model for UnderstandingDiagnostics.
type UnderstandingDiagnostics struct {
	Error    string `json:"error"`
	ExitCode *int   `json:"exit_code,omitempty"`

	// Stderr Captured plugin diagnostics; may contain private source content.
	Stderr string `json:"stderr"`

	// Stdout Captured plugin stdout, including invalid protocol output.
	Stdout string `json:"stdout"`
}

// UnderstandingRun defines model for UnderstandingRun.
type UnderstandingRun struct {
	Artifacts   []DerivedContent   `json:"artifacts"`
	AttemptId   openapi_types.UUID `json:"attempt_id"`
	CompletedAt time.Time          `json:"completed_at"`

	// CostEstimate Optional API-equivalent estimate, not subscription charges.
	CostEstimate  *CostEstimate      `json:"cost_estimate,omitempty"`
	CreatedAt     time.Time          `json:"created_at"`
	Id            openapi_types.UUID `json:"id"`
	PluginId      string             `json:"plugin_id"`
	PluginVersion string             `json:"plugin_version"`
	SourceBlobref string             `json:"source_blobref"`

	// Statistics Optional plugin-reported Run totals.
	Statistics *Statistics `json:"statistics,omitempty"`
	Warnings   []string    `json:"warnings"`
}

// Cursor defines model for Cursor.
type Cursor = string

// Limit defines model for Limit.
type Limit = int32

// MemoryId defines model for MemoryId.
type MemoryId = openapi_types.UUID

// BrowseMemoriesParams defines parameters for BrowseMemories.
type BrowseMemoriesParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ImportMemoryMultipartRequestBody defines body for ImportMemory for multipart/form-data ContentType.
type ImportMemoryMultipartRequestBody = ImportMultipart

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetLiveness Check whether the process is alive
	// (GET /livez)
	GetLiveness(w http.ResponseWriter, r *http.Request)
	// BrowseMemories Browse committed Memories
	// (GET /memories)
	BrowseMemories(w http.ResponseWriter, r *http.Request, params BrowseMemoriesParams)
	// ImportMemory Durably import one Blob as a Memory
	// (POST /memories/import)
	ImportMemory(w http.ResponseWriter, r *http.Request)
	// DeleteMemory Delete one Memory and its Blob
	// (DELETE /memories/{memoryId})
	DeleteMemory(w http.ResponseWriter, r *http.Request, memoryId MemoryId)
	// GetMemory Get committed Memory details
	// (GET /memories/{memoryId})
	GetMemory(w http.ResponseWriter, r *http.Request, memoryId MemoryId)
	// GetMemoryContent Download and verify a Memory's immutable Blob
	// (GET /memories/{memoryId}/content)
	GetMemoryContent(w http.ResponseWriter, r *http.Request, memoryId MemoryId)
	// GetReadiness Check whether the server can accept requests
	// (GET /readyz)
	GetReadiness(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetLiveness operation middleware
func (siw *ServerInterfaceWrapper) GetLiveness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLiveness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BrowseMemories operation middleware
func (siw *ServerInterfaceWrapper) BrowseMemories(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params BrowseMemoriesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BrowseMemories(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ImportMemory operation middleware
func (siw *ServerInterfaceWrapper) ImportMemory(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ImportMemory(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteMemory operation middleware
func (siw *ServerInterfaceWrapper) DeleteMemory(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "memoryId" -------------
	var memoryId MemoryId

	err = runtime.BindStyledParameterWithOptions("simple", "memoryId", r.PathValue("memoryId"), &memoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "memoryId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteMemory(w, r, memoryId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMemory operation middleware
func (siw *ServerInterfaceWrapper) GetMemory(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "memoryId" -------------
	var memoryId MemoryId

	err = runtime.BindStyledParameterWithOptions("simple", "memoryId", r.PathValue("memoryId"), &memoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "memoryId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMemory(w, r, memoryId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMemoryContent operation middleware
func (siw *ServerInterfaceWrapper) GetMemoryContent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "memoryId" -------------
	var memoryId MemoryId

	err = runtime.BindStyledParameterWithOptions("simple", "memoryId", r.PathValue("memoryId"), &memoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "memoryId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMemoryContent(w, r, memoryId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/livez", wrapper.GetLiveness)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/readyz", wrapper.GetReadiness)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/memories", wrapper.BrowseMemories)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/memories/{memoryId}", wrapper.DeleteMemory)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/memories/{memoryId}", wrapper.GetMemory)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/memories/{memoryId}/content", wrapper.GetMemoryContent)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/memories/import", wrapper.ImportMemory)

	return m
}

type GetLivenessRequestObject struct {
}

type GetLivenessResponseObject interface {
	VisitGetLivenessResponse(w http.ResponseWriter) error
}

type GetLiveness200JSONResponse HealthResponse

func (response GetLiveness200JSONResponse) VisitGetLivenessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type BrowseMemoriesRequestObject struct {
	Params BrowseMemoriesParams
}

type BrowseMemoriesResponseObject interface {
	VisitBrowseMemoriesResponse(w http.ResponseWriter) error
}

type BrowseMemories200JSONResponse MemoryPage

func (response BrowseMemories200JSONResponse) VisitBrowseMemoriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type BrowseMemories400JSONResponse Error

func (response BrowseMemories400JSONResponse) VisitBrowseMemoriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ImportMemoryRequestObject struct {
	Body *multipart.Reader
}

type ImportMemoryResponseObject interface {
	VisitImportMemoryResponse(w http.ResponseWriter) error
}

type ImportMemory201JSONResponse MemorySummary

func (response ImportMemory201JSONResponse) VisitImportMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type ImportMemory400JSONResponse Error

func (response ImportMemory400JSONResponse) VisitImportMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ImportMemory409JSONResponse Error

func (response ImportMemory409JSONResponse) VisitImportMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ImportMemory413JSONResponse Error

func (response ImportMemory413JSONResponse) VisitImportMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type ImportMemory500JSONResponse Error

func (response ImportMemory500JSONResponse) VisitImportMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteMemoryRequestObject struct {
	MemoryId MemoryId `json:"memoryId"`
}

type DeleteMemoryResponseObject interface {
	VisitDeleteMemoryResponse(w http.ResponseWriter) error
}

type DeleteMemory204Response struct {
}

func (response DeleteMemory204Response) VisitDeleteMemoryResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteMemory404JSONResponse Error

func (response DeleteMemory404JSONResponse) VisitDeleteMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetMemoryRequestObject struct {
	MemoryId MemoryId `json:"memoryId"`
}

type GetMemoryResponseObject interface {
	VisitGetMemoryResponse(w http.ResponseWriter) error
}

type GetMemory200JSONResponse MemoryDetail

func (response GetMemory200JSONResponse) VisitGetMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMemory404JSONResponse Error

func (response GetMemory404JSONResponse) VisitGetMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetMemoryContentRequestObject struct {
	MemoryId MemoryId `json:"memoryId"`
}

type GetMemoryContentResponseObject interface {
	VisitGetMemoryContentResponse(w http.ResponseWriter) error
}

type GetMemoryContent200ResponseHeaders struct {
	ContentDisposition *string
	ETag               *string
}

type GetMemoryContent200AsteriskResponse struct {
	Body          io.Reader
	Headers       GetMemoryContent200ResponseHeaders
	ContentType   string
	ContentLength int64
}

func (response GetMemoryContent200AsteriskResponse) VisitGetMemoryContentResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", response.ContentType)
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	if response.Headers.ContentDisposition != nil {
		w.Header().Set("Content-Disposition", fmt.Sprint(*response.Headers.ContentDisposition))
	}
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetMemoryContent404JSONResponse Error

func (response GetMemoryContent404JSONResponse) VisitGetMemoryContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetMemoryContent500JSONResponse Error

func (response GetMemoryContent500JSONResponse) VisitGetMemoryContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetMemoryContent507JSONResponse Error

func (response GetMemoryContent507JSONResponse) VisitGetMemoryContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(507)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadinessRequestObject struct {
}

type GetReadinessResponseObject interface {
	VisitGetReadinessResponse(w http.ResponseWriter) error
}

type GetReadiness200JSONResponse HealthResponse

func (response GetReadiness200JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetLiveness Check whether the process is alive
	// (GET /livez)
	GetLiveness(ctx context.Context, request GetLivenessRequestObject) (GetLivenessResponseObject, error)
	// BrowseMemories Browse committed Memories
	// (GET /memories)
	BrowseMemories(ctx context.Context, request BrowseMemoriesRequestObject) (BrowseMemoriesResponseObject, error)
	// ImportMemory Durably import one Blob as a Memory
	// (POST /memories/import)
	ImportMemory(ctx context.Context, request ImportMemoryRequestObject) (ImportMemoryResponseObject, error)
	// DeleteMemory Delete one Memory and its Blob
	// (DELETE /memories/{memoryId})
	DeleteMemory(ctx context.Context, request DeleteMemoryRequestObject) (DeleteMemoryResponseObject, error)
	// GetMemory Get committed Memory details
	// (GET /memories/{memoryId})
	GetMemory(ctx context.Context, request GetMemoryRequestObject) (GetMemoryResponseObject, error)
	// GetMemoryContent Download and verify a Memory's immutable Blob
	// (GET /memories/{memoryId}/content)
	GetMemoryContent(ctx context.Context, request GetMemoryContentRequestObject) (GetMemoryContentResponseObject, error)
	// GetReadiness Check whether the server can accept requests
	// (GET /readyz)
	GetReadiness(ctx context.Context, request GetReadinessRequestObject) (GetReadinessResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetLiveness operation middleware
func (sh *strictHandler) GetLiveness(w http.ResponseWriter, r *http.Request) {
	var request GetLivenessRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLiveness(ctx, request.(GetLivenessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLiveness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLivenessResponseObject); ok {
		if err := validResponse.VisitGetLivenessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// BrowseMemories operation middleware
func (sh *strictHandler) BrowseMemories(w http.ResponseWriter, r *http.Request, params BrowseMemoriesParams) {
	var request BrowseMemoriesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.BrowseMemories(ctx, request.(BrowseMemoriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "BrowseMemories")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(BrowseMemoriesResponseObject); ok {
		if err := validResponse.VisitBrowseMemoriesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ImportMemory operation middleware
func (sh *strictHandler) ImportMemory(w http.ResponseWriter, r *http.Request) {
	var request ImportMemoryRequestObject

	if reader, err := r.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ImportMemory(ctx, request.(ImportMemoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ImportMemory")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ImportMemoryResponseObject); ok {
		if err := validResponse.VisitImportMemoryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteMemory operation middleware
func (sh *strictHandler) DeleteMemory(w http.ResponseWriter, r *http.Request, memoryId MemoryId) {
	var request DeleteMemoryRequestObject

	request.MemoryId = memoryId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteMemory(ctx, request.(DeleteMemoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteMemory")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteMemoryResponseObject); ok {
		if err := validResponse.VisitDeleteMemoryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMemory operation middleware
func (sh *strictHandler) GetMemory(w http.ResponseWriter, r *http.Request, memoryId MemoryId) {
	var request GetMemoryRequestObject

	request.MemoryId = memoryId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMemory(ctx, request.(GetMemoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMemory")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMemoryResponseObject); ok {
		if err := validResponse.VisitGetMemoryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMemoryContent operation middleware
func (sh *strictHandler) GetMemoryContent(w http.ResponseWriter, r *http.Request, memoryId MemoryId) {
	var request GetMemoryContentRequestObject

	request.MemoryId = memoryId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMemoryContent(ctx, request.(GetMemoryContentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMemoryContent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMemoryContentResponseObject); ok {
		if err := validResponse.VisitGetMemoryContentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadiness operation middleware
func (sh *strictHandler) GetReadiness(w http.ResponseWriter, r *http.Request) {
	var request GetReadinessRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadiness(ctx, request.(GetReadinessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadiness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadinessResponseObject); ok {
		if err := validResponse.VisitGetReadinessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFpbc9u4kv4rXdipmt0pWlauM+M8JfHsjLeSTcpxzkvso4LIpoQJCDBAQ7bGpf9+CgBJ8SbLlySVF5Uk",
	"go1GX76+4Zqluii1QkWWHV2zkhteIKEJv147Y7Xx34RiR+yLQ7NmCVO8QHbE0vg0YTZdYsH9MlqX/okl",
	"I9SCbTYJeyMKQbsoyPCwTSDDnDtJ7OjZNGG5NgUndsSEoiePWcIKfiUKV7CjR9Npwgqhql9JvbFQhAs0",
	"Yee3WGizPsmazUtOy+3eRf04YQa/OGEwY0dkHLbZaThwTmSs2aY536ZeHMWlLf1hSRSc0P/mWSZIaMXl",
	"e6NLNCTQsqOcS4sJK1t/XTNeaKdo5mzW2TbTbi6Rtc46bZhQrpj7oyZszq0IVAqh3qBa0LItk5pZv6VI",
	"hVrMsoq/nQuckePa3ErqU5vlmoWLZlM9/xtT8jSP0YgVZq+1IlQUdWxTI0ovGXbETlSGJaoMFQHhFQE3",
	"JHKeEsxRarUQagGkQZCFVCviQvl/Tp2asL4Q51LPZ0tul9GSidD4Hf5tl/zxs+cHn/hBPj34/eL6+dPN",
	"T2xEPvM14cyKf7CjA6Ho+dNxFTTmlrB01/neCELDJXw8+9+D3+IJq7WTMR6qZ7P4YERHIruFYQbJrFBx",
	"leKQpXdltErQJf/iEErpFkIdZJgLhRn834d3/w8FEs848QkLNq7Lh9Pp2U/ge6uytvh7Ymh+jhuYK6VI",
	"OWF0+KD7jlncSmJD5sb2+sMYbYY7pDoL4sErXpRyiy4zpWmWa6dGVZQhcSHtbqSIaDRgAq+EJe+mRXNg",
	"LuW7nB19umY/GczZEfuvwy2uH1YQddiX1OYi6Wn0vUHrHVEr4JDVy0EUpTbBbnMpUgKrIZXC04aUKzCY",
	"6hUab8/KSck9ZAXmNwkr0Fq+wP1wEmS4XT8m/b+QS1qeoi21sjhUgyVOLnxD5R31E9OfW4S2kl+hseHA",
	"+5iqKI4xcxJkEmDtasTtP5A2mMHWDSE3ugBaIuTCWALr0hStzZ2sxDvEs1xItGtLWMxSg5wwm3HqxgdO",
	"eECiwIHoR07dIlfoTOTiofSclLMQVMdwShuxEIrLmd82xtyRVQYlJ7HCXXR6+hgS3auaE1U62huNdwBb",
	"tPIDPbdoVl11Bj/hFrRC4GX0FKHV4d9Wq3NVOEmi5IbAf0zgbIlQMw8185DqAu3WMF5JPa/WvysEEWbn",
	"asWlQwsGCy4UOPVZ6Uv1AgouvdIwA68tS7wo/SIvgUCqMqlz9UCjeqgR3dFobmEOO7T9thb4EBY8yyPB",
	"S1UC1zlwgkJbgkfTKbwVr+BS0BI4KK3mkqvPW4UJda6qTObgWNhS22BSUb/BRgxkSJiSDRnLW8wEh7N1",
	"Wbl/FcfOVcQArjIo+BpyLiXMefrZZzocVlyKLAFbYipykQaTgHpbTyzqtRH4XCge0uqCXzX53/Tpb89+",
	"fT6djuggGscs3WLXTVFjxJv6bhkkPOaJMdAch0A3FjZjkK/Sza5+TitTgI+nb7yOvFVXL0CmL5XUPANU",
	"WanFjlTqAcdkIXLV0fWm1+IJP7ii8CrYJMypDI0lrjLPxp63P7YXH1f5QF+6FSODA/X32q2A91UE7uVF",
	"hEX3y50OWu3FjeHht8IrmqVNxbgnfPTOGFnYfYJ638EhOjl/14Jec6WVSLmED3+9PHj87Hnwd4N5bU6i",
	"KBx5HsODEH+/b9Fwy1w+6v2OQFt46NldRjSR9GtkFreL9c2qr5B97KslWqfvFhZDVrvyHTPBD8RJWBKp",
	"vWNV7+rU93b5+Zn+jOpjeGdzMRrrWivuxknK0yXOLo0gnAmP4TPypOx9Kl1PKnsolQe+rh096H2D3Grl",
	"i6iHUiJNXN739TEdd2LCSyIsShqLnb7SfKjjZoIvlN6a9q3MtBu0WhQ2F/0t79CvCL2DmchGcFyrXCxc",
	"KKfCKjg5fgFeLGu4XKICpesHwoJFiSlhNpoSfHHo7oijlrh5qJiHhWlkhCXMOOXNkCUs08oTy7mQmI2U",
	"rWOQt5Vas0n7kBf7zOt424Lo9SPTkIYbp+5pF6dOjfQXfJosuSWozbddBp869QLi8YFHu7eQaVCawGAp",
	"eYogaLTLIDmhpRnfess9WK59bdSMv4UKG4312E/a4t+vw64Pd/WIdcNqYJN4JWhWN652WHAL5ixlaMxY",
	"klVS2zVbiPIi1DZV0xZKI1bcK1w7k+KNPVBLmXa0f6+4LgGhUum8KECoUDv5Op10qiVEdJ/s7fdFOTVb",
	"N+fdK/1Tp4ZSr1vYt8+ue13ykfS6Mo7ZLfH0VvFh5C1LM2yPMG7lRp3Bx+ZiZzvl5fuTAy/0FZeoCOqN",
	"kuDi1s2blyBdcrNAG7rP92lT3Cfq7Hq6u1uYsGjNs3ksLO45d7Dd/PJWIm/lpDcIvOrIG4wJrodYCAlL",
	"lOwlNx65umY6YK9riWNhqGWb3ZjUk+BAXh3l9oy2xV7S8qihR25COpnrIWD8dXb2PiCN8fOkXJvYRXDG",
	"oCK59l0yiQUqLxqpfaUYq034lx9CgpUixQm8PFfV3yK2+5xFc7ASVvjSkZYeeEqDVYtwvg6bRAq+wSMs",
	"iAwVhZLnXFXP61aGzkOjKBSgoatDgloThMz7DGt1rNl08mgyDSlwiYqXgh2xJ5Pp5EmsXpdBhYdSrPAf",
	"/22BwWk8OIX2pB+Hsj+R3ogVKrQ2TD9jPz28+Xg6bXVm/Nd+b9P/tx2Q3mSivXZ90NMwHSiN9gmAFxP3",
	"bMdBka3rffZ6ielnn+fREqP++m94oXFvxJ/YMmzJQvF0GCRYIfKoHF4ZfWnxbb0s6Uy/d/jfdslhHG1v",
	"kr0LqzH65uIbCrvV6BkR9Eso+QK9sdWnDf7/9CsyEEdjO5TsEQMtBV+IIbqv5qgLnxfGzje01FJrt1Fo",
	"V7+HsX4P4KvtSN7wsQzNQl13fL1XGiRnFPCc0AQP9E0CC9wgZM7wuVxD6eZS2KXPRlV2rrzpbXGgYXQC",
	"LyPVdrLTayifq/9u+rFxo//ptIxLNEXgwY8KMYPW9KBKZM6Vn7AtkWfgyVeFP5AGWnKKDITbFBNopnwN",
	"xoh6NODxJ/S2AzA+nf4+gWOdOo+A0Mlq/Cs+JpdoqjFDgC1ha01GrOq6U9WIr7uV1cpXOlv3jKw53qEn",
	"fuDHw7e3s367f9ONSFW63vOzR1/Zz5o26Li596x4/QM4m9//9++zf+ptKAtzYwt8a4+Ri0dPvg8XcbZj",
	"RnyqJR/SGqTPNANvz76Xhqp5elXrzjHXBqGFL1tw6aHkcQVNFYEtonlBN563Dy+v67tPm4iVPuUaouZ7",
	"NAVXMVGKa2yLxySAZhc0Tp2ySUBXWuK56rbXwWCOBlUawURUQ9GYJxl0tiIf9aZk7O2cq/riTwVkda8W",
	"+IILNQZDx4HXFgx1kODp8KBnW8F73ut0DC7RB4NArfagp9/Vgxv8gExjBORw92NgFYHHYA0j5xg3iGRn",
	"arhLcl87V6mmgjtE0LayCPlQzeaihflp6cJ434bOFAxiUyWsiV2UeFfsB1bfn0iDiAH15aAdyrtbptpc",
	"hdxc7ACCw5ZUbjaMukWx1z5+OfylK8/hvHrkOuVQms21icb1q1QtpG60RGHAD3eCypsJsVigpXO15CuE",
	"OaKCFZpQgUXgsFRVYb1AHfDEp1n1DdjhsH/kro9bLKK+m4sCvtasp9STPVdk/zjji3FUqk/jh1oJfHE6",
	"AJ837pjBoSJBayC+uHmPzY9l/d8x0vYV/HOF7cJCIaz1gKENpNoYV9as/frtWTtR1uW5SIXXriVt+GJQ",
	"+B7Xlxy8XQfrXTdB/mfbG15/E5wwyLP1jW2EU+SZ+DH6CFUpFUoUnq3DTZo0xbLJ9+z+zkJFI+Wq/+5o",
	"j8FTC29E4fbu/YZ+Ut3FietYwsJdF3bIS3G4moaWQEX3ur6YXtHfJM0/jUY3F5v/DAA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
