//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ServerUrlLocalMemorydServer defines the Server URL for Local memoryd server
const ServerUrlLocalMemorydServer = "/api/v0"

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for UnderstandingAttemptState.
const (
	UnderstandingAttemptStateDone    UnderstandingAttemptState = "done"
	UnderstandingAttemptStateFailed  UnderstandingAttemptState = "failed"
	UnderstandingAttemptStateQueued  UnderstandingAttemptState = "queued"
	UnderstandingAttemptStateRunning UnderstandingAttemptState = "running"
)

// Valid indicates whether the value is a known member of the UnderstandingAttemptState enum.
func (e UnderstandingAttemptState) Valid() bool {
	switch e {
	case UnderstandingAttemptStateDone:
		return true
	case UnderstandingAttemptStateFailed:
		return true
	case UnderstandingAttemptStateQueued:
		return true
	case UnderstandingAttemptStateRunning:
		return true
	default:
		return false
	}
}

// Defines values for UnderstandingDetailsStatus.
const (
	UnderstandingDetailsStatusDone       UnderstandingDetailsStatus = "done"
	UnderstandingDetailsStatusFailed     UnderstandingDetailsStatus = "failed"
	UnderstandingDetailsStatusNotStarted UnderstandingDetailsStatus = "not_started"
	UnderstandingDetailsStatusQueued     UnderstandingDetailsStatus = "queued"
	UnderstandingDetailsStatusRunning    UnderstandingDetailsStatus = "running"
)

// Valid indicates whether the value is a known member of the UnderstandingDetailsStatus enum.
func (e UnderstandingDetailsStatus) Valid() bool {
	switch e {
	case UnderstandingDetailsStatusDone:
		return true
	case UnderstandingDetailsStatusFailed:
		return true
	case UnderstandingDetailsStatusNotStarted:
		return true
	case UnderstandingDetailsStatusQueued:
		return true
	case UnderstandingDetailsStatusRunning:
		return true
	default:
		return false
	}
}

// CostEstimate defines model for CostEstimate.
type CostEstimate struct {
	AmountUsd   float64 `json:"amount_usd"`
	Basis       string  `json:"basis"`
	PricingDate *string `json:"pricing_date,omitempty"`
	PricingUrl  *string `json:"pricing_url,omitempty"`
}

// DerivedContent Independent text artifact belonging to its containing Run.
type DerivedContent struct {
	BlobHash string `json:"blob_hash"`
	ByteSize int64  `json:"byte_size"`

	// Content Literal UTF-8 text content.
	Content     string             `json:"content"`
	ContentType string             `json:"content_type"`
	Id          openapi_types.UUID `json:"id"`

	// Provenance Optional opaque plugin-defined JSON metadata.
	Provenance interface{} `json:"provenance,omitempty"`

	// Scope Optional opaque plugin-defined JSON metadata.
	Scope interface{} `json:"scope,omitempty"`
}

// DuplicateMemory defines model for DuplicateMemory.
type DuplicateMemory struct {
	Id openapi_types.UUID `json:"id"`
}

// Error defines model for Error.
type Error struct {
	// Code Example: memory_not_found
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`

	// ExistingMemory Present on a duplicate import conflict so clients can recover.
	ExistingMemory *DuplicateMemory `json:"existing_memory,omitempty"`
	Message        string           `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status  HealthResponseStatus `json:"status"`
	Version *string              `json:"version,omitempty"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// ImportContext Stored provenance from the first successful import.
type ImportContext struct {
	FilesystemCreatedAt  *time.Time `json:"filesystem_created_at,omitempty"`
	FilesystemModifiedAt *time.Time `json:"filesystem_modified_at,omitempty"`
	FullPath             *string    `json:"full_path,omitempty"`
	OriginalFilename     string     `json:"original_filename"`
	RelativePath         *string    `json:"relative_path,omitempty"`
}

// ImportContextInput Optional client-observed provenance sent as one application/json
// multipart part. The original filename comes from the Blob part. Omitted
// values remain unknown; malformed timestamps reject the import.
type ImportContextInput struct {
	FilesystemCreatedAt  *time.Time `json:"filesystem_created_at,omitempty"`
	FilesystemModifiedAt *time.Time `json:"filesystem_modified_at,omitempty"`
	FullPath             *string    `json:"full_path,omitempty"`
	RelativePath         *string    `json:"relative_path,omitempty"`
}

// ImportMultipart defines model for ImportMultipart.
type ImportMultipart struct {
	// File One Blob of at most 100 MiB with a nonblank filename in
	// Content-Disposition. The server detects its Media Type from content
	// first and may fall back to a valid, specific part Content-Type.
	File openapi_types.File `json:"file"`

	// ImportContext Optional client-observed provenance sent as one application/json
	// multipart part. The original filename comes from the Blob part. Omitted
	// values remain unknown; malformed timestamps reject the import.
	ImportContext *ImportContextInput `json:"import_context,omitempty"`
}

// MemoryDetail defines model for MemoryDetail.
type MemoryDetail struct {
	// ContentUrl Relative URL of the content download endpoint.
	ContentUrl *string `json:"content_url,omitempty"`

	// ImportContext Stored provenance from the first successful import.
	ImportContext ImportContext        `json:"import_context"`
	Memory        MemorySummary        `json:"memory"`
	Understanding UnderstandingDetails `json:"understanding"`
}

// MemoryPage defines model for MemoryPage.
type MemoryPage struct {
	Items      []MemorySummary `json:"items"`
	NextCursor *string         `json:"next_cursor,omitempty"`
}

// MemorySummary defines model for MemorySummary.
type MemorySummary struct {
	// BlobHash Canonical SHA-256 Blobref of the immutable Blob.
	BlobHash           string             `json:"blob_hash"`
	ByteSize           int64              `json:"byte_size"`
	Id                 openapi_types.UUID `json:"id"`
	ImportedAt         time.Time          `json:"imported_at"`
	MediaType          string             `json:"media_type"`
	OriginalCreatedAt  *time.Time         `json:"original_created_at,omitempty"`
	OriginalFilename   string             `json:"original_filename"`
	OriginalModifiedAt *time.Time         `json:"original_modified_at,omitempty"`
}

// RebuildStatus defines model for RebuildStatus.
type RebuildStatus struct {
	Attempt   UnderstandingAttempt `json:"attempt"`
	MemoryId  openapi_types.UUID   `json:"memory_id"`
	StatusUrl string               `json:"status_url"`
}

// Statistics defines model for Statistics.
type Statistics struct {
	Usage *TokenUsage `json:"usage,omitempty"`
}

// TokenUsage defines model for TokenUsage.
type TokenUsage struct {
	CacheWriteInputTokens *int64 `json:"cache_write_input_tokens,omitempty"`
	CachedInputTokens     *int64 `json:"cached_input_tokens,omitempty"`
	InputTokens           *int64 `json:"input_tokens,omitempty"`
	OutputTokens          *int64 `json:"output_tokens,omitempty"`
	ReasoningOutputTokens *int64 `json:"reasoning_output_tokens,omitempty"`
	TotalTokens           *int64 `json:"total_tokens,omitempty"`
}

// UnderstandingAttempt defines model for UnderstandingAttempt.
type UnderstandingAttempt struct {
	CompletedAt *time.Time                `json:"completed_at,omitempty"`
	Diagnostics *UnderstandingDiagnostics `json:"diagnostics,omitempty"`
	Id          openapi_types.UUID        `json:"id"`

	// PluginId Configured plugin ID; empty when no plugin is selected.
	PluginId  string                    `json:"plugin_id"`
	QueuedAt  time.Time                 `json:"queued_at"`
	StartedAt *time.Time                `json:"started_at,omitempty"`
	Status    UnderstandingAttemptState `json:"status"`
}

// UnderstandingAttemptState defines model for UnderstandingAttemptState.
type UnderstandingAttemptState string

// UnderstandingDetails defines model for UnderstandingDetails.
type UnderstandingDetails struct {
	// ActiveRun The last complete successful Run; failed attempts do not replace it.
	ActiveRun     *UnderstandingRun          `json:"active_run"`
	LatestAttempt *UnderstandingAttempt      `json:"latest_attempt"`
	Status        UnderstandingDetailsStatus `json:"status"`

	// StatusUrl Process-local polling URL; absent for durable history after restart.
	StatusUrl *string `json:"status_url,omitempty"`
}

// UnderstandingDetailsStatus defines model for UnderstandingDetails.Status.
type UnderstandingDetailsStatus string

// UnderstandingDiagnostics defines model for UnderstandingDiagnostics.
type UnderstandingDiagnostics struct {
	Error    string `json:"error"`
	ExitCode *int   `json:"exit_code,omitempty"`

	// Stderr Captured plugin diagnostics; may contain private source content.
	Stderr string `json:"stderr"`

	// Stdout Captured plugin stdout, including invalid protocol output.
	Stdout string `json:"stdout"`
}

// UnderstandingRun defines model for UnderstandingRun.
type UnderstandingRun struct {
	Artifacts   []DerivedContent   `json:"artifacts"`
	AttemptId   openapi_types.UUID `json:"attempt_id"`
	CompletedAt time.Time          `json:"completed_at"`

	// CostEstimate Optional API-equivalent estimate, not subscription charges.
	CostEstimate  *CostEstimate      `json:"cost_estimate,omitempty"`
	CreatedAt     time.Time          `json:"created_at"`
	Id            openapi_types.UUID `json:"id"`
	PluginId      string             `json:"plugin_id"`
	PluginVersion string             `json:"plugin_version"`
	SourceBlobref string             `json:"source_blobref"`

	// Statistics Optional plugin-reported Run totals.
	Statistics *Statistics `json:"statistics,omitempty"`
	Warnings   []string    `json:"warnings"`
}

// Cursor defines model for Cursor.
type Cursor = string

// Limit defines model for Limit.
type Limit = int32

// MemoryId defines model for MemoryId.
type MemoryId = openapi_types.UUID

// BrowseMemoriesParams defines parameters for BrowseMemories.
type BrowseMemoriesParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ImportMemoryMultipartRequestBody defines body for ImportMemory for multipart/form-data ContentType.
type ImportMemoryMultipartRequestBody = ImportMultipart

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetLiveness Check whether the process is alive
	// (GET /livez)
	GetLiveness(w http.ResponseWriter, r *http.Request)
	// BrowseMemories Browse committed Memories
	// (GET /memories)
	BrowseMemories(w http.ResponseWriter, r *http.Request, params BrowseMemoriesParams)
	// ImportMemory Durably import one Blob as a Memory
	// (POST /memories/import)
	ImportMemory(w http.ResponseWriter, r *http.Request)
	// DeleteMemory Delete one Memory and its Blob
	// (DELETE /memories/{memoryId})
	DeleteMemory(w http.ResponseWriter, r *http.Request, memoryId MemoryId)
	// GetMemory Get committed Memory details
	// (GET /memories/{memoryId})
	GetMemory(w http.ResponseWriter, r *http.Request, memoryId MemoryId)
	// GetMemoryContent Download and verify a Memory's immutable Blob
	// (GET /memories/{memoryId}/content)
	GetMemoryContent(w http.ResponseWriter, r *http.Request, memoryId MemoryId)
	// RebuildMemory Request a Memory Rebuild
	// (POST /memories/{memoryId}/rebuild)
	RebuildMemory(w http.ResponseWriter, r *http.Request, memoryId MemoryId)
	// GetReadiness Check whether the server can accept requests
	// (GET /readyz)
	GetReadiness(w http.ResponseWriter, r *http.Request)
	// GetRebuildStatus Poll a retained process-local Rebuild
	// (GET /rebuild-status/{rebuildId})
	GetRebuildStatus(w http.ResponseWriter, r *http.Request, rebuildId openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetLiveness operation middleware
func (siw *ServerInterfaceWrapper) GetLiveness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLiveness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BrowseMemories operation middleware
func (siw *ServerInterfaceWrapper) BrowseMemories(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params BrowseMemoriesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BrowseMemories(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ImportMemory operation middleware
func (siw *ServerInterfaceWrapper) ImportMemory(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ImportMemory(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteMemory operation middleware
func (siw *ServerInterfaceWrapper) DeleteMemory(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "memoryId" -------------
	var memoryId MemoryId

	err = runtime.BindStyledParameterWithOptions("simple", "memoryId", r.PathValue("memoryId"), &memoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "memoryId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteMemory(w, r, memoryId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMemory operation middleware
func (siw *ServerInterfaceWrapper) GetMemory(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "memoryId" -------------
	var memoryId MemoryId

	err = runtime.BindStyledParameterWithOptions("simple", "memoryId", r.PathValue("memoryId"), &memoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "memoryId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMemory(w, r, memoryId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMemoryContent operation middleware
func (siw *ServerInterfaceWrapper) GetMemoryContent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "memoryId" -------------
	var memoryId MemoryId

	err = runtime.BindStyledParameterWithOptions("simple", "memoryId", r.PathValue("memoryId"), &memoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "memoryId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMemoryContent(w, r, memoryId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RebuildMemory operation middleware
func (siw *ServerInterfaceWrapper) RebuildMemory(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "memoryId" -------------
	var memoryId MemoryId

	err = runtime.BindStyledParameterWithOptions("simple", "memoryId", r.PathValue("memoryId"), &memoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "memoryId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RebuildMemory(w, r, memoryId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRebuildStatus operation middleware
func (siw *ServerInterfaceWrapper) GetRebuildStatus(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "rebuildId" -------------
	var rebuildId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "rebuildId", r.PathValue("rebuildId"), &rebuildId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "rebuildId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRebuildStatus(w, r, rebuildId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/livez", wrapper.GetLiveness)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/readyz", wrapper.GetReadiness)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/memories", wrapper.BrowseMemories)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/memories/{memoryId}", wrapper.DeleteMemory)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/memories/{memoryId}", wrapper.GetMemory)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/memories/{memoryId}/rebuild", wrapper.RebuildMemory)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/rebuild-status/{rebuildId}", wrapper.GetRebuildStatus)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/memories/{memoryId}/content", wrapper.GetMemoryContent)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/memories/import", wrapper.ImportMemory)

	return m
}

type GetLivenessRequestObject struct {
}

type GetLivenessResponseObject interface {
	VisitGetLivenessResponse(w http.ResponseWriter) error
}

type GetLiveness200JSONResponse HealthResponse

func (response GetLiveness200JSONResponse) VisitGetLivenessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type BrowseMemoriesRequestObject struct {
	Params BrowseMemoriesParams
}

type BrowseMemoriesResponseObject interface {
	VisitBrowseMemoriesResponse(w http.ResponseWriter) error
}

type BrowseMemories200JSONResponse MemoryPage

func (response BrowseMemories200JSONResponse) VisitBrowseMemoriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type BrowseMemories400JSONResponse Error

func (response BrowseMemories400JSONResponse) VisitBrowseMemoriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ImportMemoryRequestObject struct {
	Body *multipart.Reader
}

type ImportMemoryResponseObject interface {
	VisitImportMemoryResponse(w http.ResponseWriter) error
}

type ImportMemory201JSONResponse MemorySummary

func (response ImportMemory201JSONResponse) VisitImportMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type ImportMemory400JSONResponse Error

func (response ImportMemory400JSONResponse) VisitImportMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ImportMemory409JSONResponse Error

func (response ImportMemory409JSONResponse) VisitImportMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ImportMemory413JSONResponse Error

func (response ImportMemory413JSONResponse) VisitImportMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type ImportMemory500JSONResponse Error

func (response ImportMemory500JSONResponse) VisitImportMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteMemoryRequestObject struct {
	MemoryId MemoryId `json:"memoryId"`
}

type DeleteMemoryResponseObject interface {
	VisitDeleteMemoryResponse(w http.ResponseWriter) error
}

type DeleteMemory204Response struct {
}

func (response DeleteMemory204Response) VisitDeleteMemoryResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteMemory404JSONResponse Error

func (response DeleteMemory404JSONResponse) VisitDeleteMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetMemoryRequestObject struct {
	MemoryId MemoryId `json:"memoryId"`
}

type GetMemoryResponseObject interface {
	VisitGetMemoryResponse(w http.ResponseWriter) error
}

type GetMemory200JSONResponse MemoryDetail

func (response GetMemory200JSONResponse) VisitGetMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMemory404JSONResponse Error

func (response GetMemory404JSONResponse) VisitGetMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetMemoryContentRequestObject struct {
	MemoryId MemoryId `json:"memoryId"`
}

type GetMemoryContentResponseObject interface {
	VisitGetMemoryContentResponse(w http.ResponseWriter) error
}

type GetMemoryContent200ResponseHeaders struct {
	ContentDisposition *string
	ETag               *string
}

type GetMemoryContent200AsteriskResponse struct {
	Body          io.Reader
	Headers       GetMemoryContent200ResponseHeaders
	ContentType   string
	ContentLength int64
}

func (response GetMemoryContent200AsteriskResponse) VisitGetMemoryContentResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", response.ContentType)
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	if response.Headers.ContentDisposition != nil {
		w.Header().Set("Content-Disposition", fmt.Sprint(*response.Headers.ContentDisposition))
	}
	if response.Headers.ETag != nil {
		w.Header().Set("ETag", fmt.Sprint(*response.Headers.ETag))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetMemoryContent404JSONResponse Error

func (response GetMemoryContent404JSONResponse) VisitGetMemoryContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetMemoryContent500JSONResponse Error

func (response GetMemoryContent500JSONResponse) VisitGetMemoryContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetMemoryContent507JSONResponse Error

func (response GetMemoryContent507JSONResponse) VisitGetMemoryContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(507)
	_, err := buf.WriteTo(w)
	return err
}

type RebuildMemoryRequestObject struct {
	MemoryId MemoryId `json:"memoryId"`
}

type RebuildMemoryResponseObject interface {
	VisitRebuildMemoryResponse(w http.ResponseWriter) error
}

type RebuildMemory202ResponseHeaders struct {
	CacheControl *string
}

type RebuildMemory202JSONResponse struct {
	Body    RebuildStatus
	Headers RebuildMemory202ResponseHeaders
}

func (response RebuildMemory202JSONResponse) VisitRebuildMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type RebuildMemory404JSONResponse Error

func (response RebuildMemory404JSONResponse) VisitRebuildMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RebuildMemory409ResponseHeaders struct {
	CacheControl *string
}

type RebuildMemory409JSONResponse struct {
	Body    RebuildStatus
	Headers RebuildMemory409ResponseHeaders
}

func (response RebuildMemory409JSONResponse) VisitRebuildMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type RebuildMemory503JSONResponse Error

func (response RebuildMemory503JSONResponse) VisitRebuildMemoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadinessRequestObject struct {
}

type GetReadinessResponseObject interface {
	VisitGetReadinessResponse(w http.ResponseWriter) error
}

type GetReadiness200JSONResponse HealthResponse

func (response GetReadiness200JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRebuildStatusRequestObject struct {
	RebuildId openapi_types.UUID `json:"rebuildId"`
}

type GetRebuildStatusResponseObject interface {
	VisitGetRebuildStatusResponse(w http.ResponseWriter) error
}

type GetRebuildStatus200ResponseHeaders struct {
	CacheControl *string
}

type GetRebuildStatus200JSONResponse struct {
	Body    RebuildStatus
	Headers GetRebuildStatus200ResponseHeaders
}

func (response GetRebuildStatus200JSONResponse) VisitGetRebuildStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRebuildStatus404ResponseHeaders struct {
	CacheControl *string
}

type GetRebuildStatus404JSONResponse struct {
	Body    Error
	Headers GetRebuildStatus404ResponseHeaders
}

func (response GetRebuildStatus404JSONResponse) VisitGetRebuildStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetLiveness Check whether the process is alive
	// (GET /livez)
	GetLiveness(ctx context.Context, request GetLivenessRequestObject) (GetLivenessResponseObject, error)
	// BrowseMemories Browse committed Memories
	// (GET /memories)
	BrowseMemories(ctx context.Context, request BrowseMemoriesRequestObject) (BrowseMemoriesResponseObject, error)
	// ImportMemory Durably import one Blob as a Memory
	// (POST /memories/import)
	ImportMemory(ctx context.Context, request ImportMemoryRequestObject) (ImportMemoryResponseObject, error)
	// DeleteMemory Delete one Memory and its Blob
	// (DELETE /memories/{memoryId})
	DeleteMemory(ctx context.Context, request DeleteMemoryRequestObject) (DeleteMemoryResponseObject, error)
	// GetMemory Get committed Memory details
	// (GET /memories/{memoryId})
	GetMemory(ctx context.Context, request GetMemoryRequestObject) (GetMemoryResponseObject, error)
	// GetMemoryContent Download and verify a Memory's immutable Blob
	// (GET /memories/{memoryId}/content)
	GetMemoryContent(ctx context.Context, request GetMemoryContentRequestObject) (GetMemoryContentResponseObject, error)
	// RebuildMemory Request a Memory Rebuild
	// (POST /memories/{memoryId}/rebuild)
	RebuildMemory(ctx context.Context, request RebuildMemoryRequestObject) (RebuildMemoryResponseObject, error)
	// GetReadiness Check whether the server can accept requests
	// (GET /readyz)
	GetReadiness(ctx context.Context, request GetReadinessRequestObject) (GetReadinessResponseObject, error)
	// GetRebuildStatus Poll a retained process-local Rebuild
	// (GET /rebuild-status/{rebuildId})
	GetRebuildStatus(ctx context.Context, request GetRebuildStatusRequestObject) (GetRebuildStatusResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetLiveness operation middleware
func (sh *strictHandler) GetLiveness(w http.ResponseWriter, r *http.Request) {
	var request GetLivenessRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLiveness(ctx, request.(GetLivenessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLiveness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLivenessResponseObject); ok {
		if err := validResponse.VisitGetLivenessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// BrowseMemories operation middleware
func (sh *strictHandler) BrowseMemories(w http.ResponseWriter, r *http.Request, params BrowseMemoriesParams) {
	var request BrowseMemoriesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.BrowseMemories(ctx, request.(BrowseMemoriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "BrowseMemories")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(BrowseMemoriesResponseObject); ok {
		if err := validResponse.VisitBrowseMemoriesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ImportMemory operation middleware
func (sh *strictHandler) ImportMemory(w http.ResponseWriter, r *http.Request) {
	var request ImportMemoryRequestObject

	if reader, err := r.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ImportMemory(ctx, request.(ImportMemoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ImportMemory")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ImportMemoryResponseObject); ok {
		if err := validResponse.VisitImportMemoryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteMemory operation middleware
func (sh *strictHandler) DeleteMemory(w http.ResponseWriter, r *http.Request, memoryId MemoryId) {
	var request DeleteMemoryRequestObject

	request.MemoryId = memoryId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteMemory(ctx, request.(DeleteMemoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteMemory")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteMemoryResponseObject); ok {
		if err := validResponse.VisitDeleteMemoryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMemory operation middleware
func (sh *strictHandler) GetMemory(w http.ResponseWriter, r *http.Request, memoryId MemoryId) {
	var request GetMemoryRequestObject

	request.MemoryId = memoryId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMemory(ctx, request.(GetMemoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMemory")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMemoryResponseObject); ok {
		if err := validResponse.VisitGetMemoryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMemoryContent operation middleware
func (sh *strictHandler) GetMemoryContent(w http.ResponseWriter, r *http.Request, memoryId MemoryId) {
	var request GetMemoryContentRequestObject

	request.MemoryId = memoryId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMemoryContent(ctx, request.(GetMemoryContentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMemoryContent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMemoryContentResponseObject); ok {
		if err := validResponse.VisitGetMemoryContentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RebuildMemory operation middleware
func (sh *strictHandler) RebuildMemory(w http.ResponseWriter, r *http.Request, memoryId MemoryId) {
	var request RebuildMemoryRequestObject

	request.MemoryId = memoryId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RebuildMemory(ctx, request.(RebuildMemoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RebuildMemory")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RebuildMemoryResponseObject); ok {
		if err := validResponse.VisitRebuildMemoryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadiness operation middleware
func (sh *strictHandler) GetReadiness(w http.ResponseWriter, r *http.Request) {
	var request GetReadinessRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadiness(ctx, request.(GetReadinessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadiness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadinessResponseObject); ok {
		if err := validResponse.VisitGetReadinessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRebuildStatus operation middleware
func (sh *strictHandler) GetRebuildStatus(w http.ResponseWriter, r *http.Request, rebuildId openapi_types.UUID) {
	var request GetRebuildStatusRequestObject

	request.RebuildId = rebuildId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRebuildStatus(ctx, request.(GetRebuildStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRebuildStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRebuildStatusResponseObject); ok {
		if err := validResponse.VisitGetRebuildStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Fvdc9u2sv9XMLyd6b0dWlY+2zpPSdzb5kxyknGc8xL5aCByKaEBAQZYyFY9+t/PLABSJEVZsp16cl48",
	"kgguFvvx2y/4Osl0WWkFCm1ycp1U3PASEIz/9toZqw19Eio5Sb46MKskTRQvITlJsvA0TWy2gJLTMlxV",
	"9MSiEWqerNdp8laUAndRkP5hm0AOBXcSk5Nn4zQptCk5JieJUPjkcZImJb8SpSuTk0fjcZqUQsVvab2x",
	"UAhzMH7nd1Bqs3qTN5tXHBebvcv6cZoY+OqEgTw5QeOgzU7DgXMiT5ptmvOt68VBXNribxZFyRHoO89z",
	"gUIrLj8YXYFBATY5Kbi0kCZV66frhJfaKZw6m3e2zbWbSUhaZx03TChXzuioaTLjVngqpVBvQc1x0ZZJ",
	"zSxtKTKh5tM88rdzgTNyWJsbSX1us1yzcNFsqmd/QoZE8xSMWEL+WisEhUHHNjOiIskkJ8kblUMFKgeF",
	"DOEKGTcoCp4hm4HUai7UnKFmAi3LtEIuFP1y5tQo6QtxJvVsuuB2ESwZEQzt8G+74I+fPT/6zI+K8dGv",
	"F9fPn65/SAbkM1shTK34Czo6EAqfPx1WQWNuaZLtOt9bgWC4ZJ/O///ol3DCuHY0xEN8Ng0PBnQk8gMM",
	"00tmCYqrDLZZel8Fq2S64l8dsEq6uVBHORRCQc7+8fH9P1kJyHOOfJR4G9fV/en07MfzvVFZW/w9MTRf",
	"hw3MVVJkHCE4vNd9xywOktg2c0N7/WaMNts7ZDr34oErXlZygy5TpXFaaKcGVZQDciHtbqQIaLTFBFwJ",
	"i+SmZXNgLuX7Ijn5fJ38YKBITpL/Od7g+nGEqOO+pNYXaU+jHwxYckStGGd5vZyJstLG220hRYbMapZJ",
	"QbRZxhUzkOklGLJn5aTkBFme+XWalGAtn8N+OPEy3Kwfkv4fwCUuzsBWWlnYVoNFjs5/AkWO+jnRX1qE",
	"NpJfgrH+wPuYihSHmHnjZeJh7WrA7T+iNpCzjRuywuiS4QJYIYxFZl2WgbWFk1G823hWCAl2ZRHKaWaA",
	"I+RTjt34wBGOUJSwJfqBU7fIlToXhbgvPSfl1AfVIZzSRsyF4nJK24aYO7DKgOQolrCLTk8f20T3quaN",
	"qhzujcY7gC1Y+ZGeWTDLrjq9n3DLtALGq+ApQqvjP61WE1U6iaLiBhn9GbHzBbCaeVYzzzJdgt0Yxiup",
	"Z3H9+1IgQj5RSy4dWGag5EIxp74ofalesJJLUhrkjLRlkZcVLSIJeFLRpCbqnkZ1XyO6pdEcYA47tP2u",
	"Fvg2LBDLA8FLRYHrgnFkpbbIHo3H7J14xS4FLhhnSquZ5OrLRmFCTVTMZI5Oha209SYV9OttxLAcEDK0",
	"PmN5B7ng7HxVRfePcWyiAgZwlbOSr1jBpWQznn2hTIezJZciT5mtIBOFyLxJsHpbIhb02gh8JhT3aXXJ",
	"r5r8b/z0l2c/Px+PB3QQjGOabbDrpqgx4E19t/QSHvLEEGhOfaAbCpshyMd0s6ufs2gK7NPZW9IRWXV8",
	"geX6UknNcwYqr7TYkUrd45iJj1x1dL3ptXDCj64sSQXrNHEqB2ORq5zY2PP2p/bi05gP9KUbGdk6UH+v",
	"3Qr4ECNwLy9CKLsfbnXQuBc3hvvvCq5wmjUV457w0TtjYGH3Cep9tw7Ryfm7FvSaK61ExiX7+MfLo8fP",
	"nnt/N1DU5iTK0iHx6B/4+PuwRcOBuXzQ+y2BtiTo2V1GNJH0W2QWh8X6ZtU3yD721RKt03cLi21Wu/Id",
	"MsEzmDkh849Netmr3RGhrPBWvv4yvtPgzPRAWwgZ6WEV+oZy2jDZoTB0WDqlsCgye8sWhqvz/MOKkXP9",
	"BdQn/876YjCwt1bcjpOMZwuYXhqBMBUUsKZIpOxdynoild+Xyj1f1w7v9b4BbrWiivG+lFAjl3d9fUjH",
	"g04xkChQWX1flMoFnyu9Me2DzLQboVsU1hf9LW/RnPGNkujyvaClVSHmzteOfhV7c/qCkVhW7HIBiild",
	"PxCWWZCQIeSD+c9XB+6WQcMiN/cV86YKvy0aEvTAMLZvJNZs0D7gxYGmFXZoNQgCiSRNjFPkIUma5FrR",
	"OQsuJOSD7YPBrG07LGS+kjFO3dHazpwaaNFQpSG5RVY7RbuTcObUCxY4ZxHxLcs1UxqZgUryDJjAwUaN",
	"5AgWp61gdgeWm7A25Bzb7Rlqj0WTS9K76aIbD/vdLE2COZKaksBKS0mt409nb18wPvP1e6ENy53xOeBC",
	"WNRmxXiBYJgBz9hob6ewscaeANO2Aey1z9MuNnUtCequ49bp4UrgtO4+7vDMFnxbzMGYoUy5wjbktJDy",
	"hS9QY+edVUYsOZmcdiaDGxvZFnPtcP9eYV3KhMqkI1EwoXwBTM0W1JmWLESt/aoIcmq2bs67V/pnTm1L",
	"vZ5DHF4i9UYdAzVSNI5Dk72D4t7AWxan0J5DHeTInenV+mJnT+zlhzdHJPQll+RC9UapBxnrZs1LLFtw",
	"MwfrRwh36TXdJZruerq75ZsmwZqns1Ad3nF4ZLt580Eib+XaNwg8jlUMhCqFQJ75RCxI9pIbQsuumW6x",
	"17XEoRDbss1uvO1JcEteHeX2jLbFXtryqG2PXPs0udDbgPHH+fkHjzSGZwGxfSvIGQMK5YpanRJKUCSa",
	"gPShZcD+RZNkZqXIYMReTlT8WYSerbNgjpbCCsJ+XBDwVAZin3e28psECtSlE5aJHBT6unWi4vO6H6UL",
	"3+3zXQTfmkOBrTFQTj6TtMYOyXj0aDT2qX0FilciOUmejMajJ6EFsfAqPJZiCX/Rpzl4pyFw8j1mmmkn",
	"vwO+FUtQYK0fYYehiH/z8Xjcaq/Rx36Dmn7bTLlvMtHezMXraTshqUKkJTFxYjtM+2zdtEleLyD7Qvkr",
	"LiDor/8GCY2TEX9OFn7LxBeFx16CEZEH5fDK6EsL7+plaecKww7/2yw5DvcT1unehfEuxPribxR2q1s3",
	"IOiXrOJzIGOrT+v9/+k3ZCDMN3comRADLHpfCCG6r+agC8pMw/iCtdRSa7dRaFe/x6EJ48FX24G84VPl",
	"O766btuTVxpAZ1TM2MgDqdNjGTcQs7oVq9xMCrugfFjlE0Wmt8GBhtERexmotpOd3lRgov63aaqHjf6v",
	"0/evwJSeB5r3Qs5aI6CYyEwUjUkXwHNG5GNDg3r+uOAYGPBXYkasGdU2GCPq+Q7hjx9QeGB8Ov51xE51",
	"5ggBWSeroVcoJldg4qzIw5awtSYDVnXdKU5T6pZzXPlK56uekTXHOybiRzTjP9zO+jObdTcixYKh52eP",
	"vrGfNb3sYXPvWfHqO3A22v/Xh9k/IxvK/fDfMr6xx8DFoycPw0UY0JkBn2rJB7VmkjJNz9uzh9JQvBQR",
	"q+0ZFNoAa+HLBlx6KHkaoSkS2CAaCbrxvH14eV1fYFsHrKSUa6AEBlNyFRKlsMa2eEw9aHZB48wpm3p0",
	"xQVMVHdGwgwUYEBlAUxEnGyHPMmAs5F80JuSoWc1UfXtrQhkdcOd8TkXagiGTj2vLRjqIMHT7YOebwRP",
	"vNfpGLsECgaeWu1BTx/Ugxv8YLmGAMj+As+WVXgevTUMnGPYINKdqeEuyX3rXCWOdneIoG1lAfJZHLAG",
	"C6OR99yQb7POKJOFpopfE7oo4cLfd6y+3wG3Igarb3jtUN7tMtXmPuv6YgcQHLekcrNh1C2Kvfbx0/FP",
	"XXluXzoYuBO7Lc3m7kvj+jFV86kbLkAYRhM6r/JmzC/mYHGiFnwJbAag2BKMr8ACcFiMVVgvUHs8oTSr",
	"vsa8fWNj4MKWm8+DvpvbHr47GK8ajPbcc/7tnM+HUak+DU0mU/bVaQ98ZNwhgwOFAlcM+fzmPdbfl/U/",
	"YKTtK/jHiO3CslJYS4ChDcu0Ma6qWfv572ftjbKuKEQmSLsWteHzrcL3tL6pQnbtrXfVBPkfbe8GwoPh",
	"hAkD7f6F/1vRTnfUaS+zDCpkVaf3fqnNF+a8pmLjZlfNUgIudG5HE9WBjabkqwwshXa2FRc2l+OyBVdz",
	"X815JrjKKIOxbAYWGRSFNnjCwpjhOA4ZAmuecpwPLLjKZawiJdV/dJ+vHgew17qsAGndEJ1QkFqqyvwl",
	"Mu2QkR3ljkgPJTrxbsGueP34m5lx9xLDYHtBwWU9NWKXhFBeiq26MSp11INXmpEfEcgaLbsMffcY9i3r",
	"qb0SPicZ1smdNMDzFUWFaEmEYW1jup+Un40fqETb4cd0AjAE0U7xJRd+MvWCptdtCwsn74PmWaztaqBk",
	"UbK7qyIvyxt7pWfAc/F9NEtjv8j3YcgEUEdPqy3W7m+fRhoZV/13dzVSI+YfhdT6+Dp+j/VjFFv/CiZy",
	"/58cTqGQzLoKjIU8AAInuJCrDUhEvaab5FcCEUonSm/mqewcTOkhvcbZiN4ki42N1JMCj8IBVSEfwk+v",
	"2rbf/Y3qPcDBgcEVjSlMLboolf8SyAw6CV7rb5qnLa2ndR2dElTF0NgelN/1gB1b/6ClZHwjwG4icSMS",
	"bGVKA//215j9vf7vz7tU8MGwU+9/vjyv9fAnrEvSxF9SSI55JY6XY59CxUNc19xFj12nzS/N8dYX6/8M",
	"AA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
